### ISSUE TITLE
Autocomplete `struct{.field =}` in initializer?

### ISSUE THREAD

**Issue by Jarred-Sumner** [zigtools/zls#1004]
It would be a very nice improvement if zls was able to autocomplete the following:
```zig
const MyStruct = struct {
    foo: u32 = 0,
};

pub fn main() anyerror!void {
   var my = MyStruct{
     .
 //  ^~~~~ cursor here
//   | foo       u32 |
   };
}
```

it should show the list of possible fields from `MyStruct`, like it does if using:
```zig
var my = MyStruct{};
my.f
// ^~~~~ cursor here
```

Currently, it shows the generic list of all possible `.` values. 

An example of with TypeScript in an object literal:
<img width="918" alt="image" src="https://user-images.githubusercontent.com/709451/218936931-74a725b7-879c-44fd-b5d8-45f7f8a3f303.png">

**Comment by SuperAuguste** [comment]
Absolutely possible, especially with named struct inits. Anonymous inits will be more difficult because the type has to be inferred, but, in theory, that can be delegated to the comptime interpreter when it's more complete.

**Comment by dLedda** [comment]
Would also like to see this. Just beginning Zig and this feature is really important for learning about different builtins.

**Comment by nullptrdevs** [comment]
I have the impression they'll announce it after https://github.com/zigtools/zls/pull/1116 is merged :grin:
