### ISSUE TITLE
Global cache dir is now needed for build runner

### ISSUE THREAD

**Issue by leecannon** [zigtools/zls#1008]
Turns out this code is completely wrong: https://github.com/zigtools/zls/blob/c3f58538e8507f54964eb5e77b665e8bbaba66ac/src/special/build_runner.zig#L73-L78

Passing "ZLS_DONT_CARE" as the global cache root isn't going to cut it anymore as we actually have to open a dir for it to construct a `std.Build.Cache.Directory` the question is what should we do instead.

We could use zig's code for determining the global cache path https://github.com/ziglang/zig/blob/7199d7c77715fe06606c5c89595e6852b3fa8c20/src/introspect.zig#L82-L105

Or we just use the local cache as the global cache as well?

**Comment by nektro** [comment]
can also parse it out of `zig env`

**Comment by leecannon** [comment]
Looking at zig's code it's pretty small and the meat of it (`std.fs.getAppDataDir`) is in the std.

**Comment by leecannon** [comment]
@nektro good catch, especially as we already call `zig env`
I will get a PR going.
