### ISSUE TITLE
build failed with error: extra capture in for loop

### ISSUE THREAD

**Issue by treeshateorcs** [zigtools/zls#1012]
### Zig Version

0.11.0-dev.1691+476bdc8b0

### Zig Language Server Version

8bd5358748fff14268d9b4e48ca5b5cd30d7b973

### Steps to Reproduce

git clone --recurse-submodules https://github.com/zigtools/zls
cd zls
zig build -Doptimize=ReleaseSafe

### Expected Behavior

build succeeds

### Actual Behavior

src/main.zig:228:27: error: extra capture in for loop
        for (pairs) |*pair, i| pair.* = .{ fields[i].name, @intToEnum(ArgId, fields[i].value) };
                          ^
src/main.zig:228:27: note: run 'zig fmt' to upgrade your code automatically
error: zls...
error: The following command exited with error code 1:
/opt/homebrew/Cellar/zig/HEAD-476bdc8/bin/zig build-exe /Users/tho/Developer/zig/zls/src/main.zig -OReleaseSafe --cache-dir /Users/tho/Developer/zig/zls/zig-cache --global-cache-dir /Users/tho/.cache/zig --name zls --pkg-begin build_options /Users/tho/Developer/zig/zls/zig-cache/options/zXipf1a9MMA8v-NbSCDhpES8FOh-BlLYjqBorTwKgNVoKnJAr9GXMbkUhlks08nO --pkg-end --pkg-begin known-folders /Users/tho/Developer/zig/zls/src/known-folders/known-folders.zig --pkg-end --pkg-begin tres /Users/tho/Developer/zig/zls/src/tres/tres.zig --pkg-end --pkg-begin diffz /Users/tho/Developer/zig/zls/src/diffz/DiffMatchPatch.zig --pkg-end --enable-cache 
error: the following build command failed with exit code 1:
/Users/tho/Developer/zig/zls/zig-cache/o/84940bc0ff960c713373db00093a2e80/build /opt/homebrew/Cellar/zig/HEAD-476bdc8/bin/zig /Users/tho/Developer/zig/zls /Users/tho/Developer/zig/zls/zig-cache /Users/tho/.cache/zig -Doptimize=ReleaseSafe

**Comment by nektro** [comment]
fixed by #1011

**Comment by treeshateorcs** [comment]
yep. 1011.diff fixes it. thank you
