### ISSUE TITLE
invalid ast check error `tuple field has a name`

### ISSUE THREAD

**Issue by nektro** [zigtools/zls#1028]
### Zig Version

0.11.0-dev.1711+dc1f50e50

### Zig Language Server Version

0.11.0-dev.280+964613c

### Steps to Reproduce

```zig
const S = struct {
    a: u32,
    b: u32,
};

const Submission = union(enum) {
    open: struct { *S, [:0]const u8, u32 },
};
```

### Expected Behavior

no error

### Actual Behavior

title error pointing at `[`

**Comment by nektro** [comment]
nvm upstream issue, errors with zig too sorry

**Comment by SuperAuguste** [comment]
No worries
