### ISSUE TITLE
folding range in wrong spot for container with doc comment on first field

### ISSUE THREAD

**Issue by nektro** [zigtools/zls#1030]
### Zig Version

0.11.0-dev.1837+4789cc024

### Zig Language Server Version

0.11.0-dev.280+964613c

### Steps to Reproduce

```zig
const B = struct {
    /// doc comment
    a: u32,
    b: u32,
};
```

### Expected Behavior

all 3 structs below to have the down caret on the `const` line

### Actual Behavior

![image](https://user-images.githubusercontent.com/5464072/222799404-b8c14480-c1eb-43a5-a0d5-46d96f3563c0.png)

**Comment by Techatrix** [comment]
This should have been fixed by https://github.com/zigtools/zls/commit/97f7fd77c61088d8e501b0927b4d8b254fda42ca.

**Comment by nektro** [comment]
confirmed
