### ISSUE TITLE
Go to definition not working with usingnamespace

### ISSUE THREAD

**Issue by kristianhasselknippe** [zigtools/zls#104]
Hi! Very cool that you've gotten this project so far already. Keep it up! :)

I noticed that i'm not able to use "go to definition" on declarations imported using `usingnamespace`.

**Comment by alexnask** [comment]
@kristianhasselknippe  
Hi, at the moment `usingnamespace` is not supported at all, so neither completions, nor hover or goto definition will work with symbols introduced by it.  

This is the next sizeable feature that I plan to work on :)

**Comment by alexnask** [comment]
This should be working now
