### ISSUE TITLE
ZLS fails to find zig in path and segfaults

### ISSUE THREAD

**Issue by nextdimension** [zigtools/zls#1047]
zls fails to find zig in path

### Zig Version

0.11.0-dev.1913+95f6a5935

### Zig Language Server Version

b8eb6aab7f905a7b29edbe2265a65e2b2e79ae31

### Steps to Reproduce

Update zls from the master branch
confirm zls and zig are added to path
run zls or run  nvim or vscode and zls fails to find zig in path

With a zls.json file with zig exe + lib path specificed, I get a segfault.
with a zls.json and only zig exe path specificed I get a segfault.

Note: Prior to today I was on a commit from 1 week ago and everything was working ok.

### Expected Behavior

No seg fault
ZLS can find zig in path
ZLS works as LS
### Actual Behavior

ZLS segfaults
ZLS fails to find zig in path

**Comment by Techatrix** [comment]
Could you post the entire log output of ZLS including the segfault stack trace.
In VS-Code you will it here: Bottom Panel -> Output -> Zig Language Server
Make sure to use a debug build of ZLS so that you get a stack trace.

**Comment by nextdimension** [comment]
This is now fixed,
I used zig 0.11.0-dev.1932+c93e0d861 and zls ef4a0607fbdb266cb62a321faedcf5a8f8d2f3ff
