### ISSUE TITLE
fail to update

### ISSUE THREAD

**Issue by 20kano** [zigtools/zls#1054]
### Zig Version

0.11.0-dev.1929+4ea2f441d

### Zig Language Server Version

how to check?

### Steps to Reproduce

On ArchLinux and VSCode, execute "Zig Language server: Check for Server Updates".

### Expected Behavior

No error.

### Actual Behavior

![範囲を選択_001](https://user-images.githubusercontent.com/119773193/224519957-698ed5d2-4322-4a25-8bac-4438ceea86ef.png)

**Comment by SuperAuguste** [comment]
This was due to a bug that was fixed in 421a05ae5ff843fe6bdefc1a6179dfddb879871d. My recommendation is run `Zig Language Server: Stop` and *then* run `Zig Language Server: Check for Updates`. This should resolve the EBUSY errors. Thanks!

**Comment by 20kano** [comment]
Thanks, tried stop and run, but hmmm.. got same error.

**Comment by 20kano** [comment]
delete _Zls: Path_ and install again, seems to work.

**Comment by 20kano** [comment]
fixed at 0.11.0-dev.325+0475d86
