### ISSUE TITLE
`@import("root")` resolves to `root.zig`

### ISSUE THREAD

**Issue by Jarred-Sumner** [zigtools/zls#1070]
### Zig Version

0.11.0-dev.1934+10c74631b

### Zig Language Server Version

HEAD

### Steps to Reproduce

1. go to definition on `@import("root")`
<img width="418" alt="image" src="https://user-images.githubusercontent.com/709451/225441199-a14f6b58-910b-447c-ab76-ac4ae0c26e21.png">
2. opens root.zig
<img width="515" alt="image" src="https://user-images.githubusercontent.com/709451/225441217-4c688c7a-0b8c-433d-bf01-d24ea1b95195.png">

### Expected Behavior

open the project root

### Actual Behavior

opens root.zig

**Comment by SuperAuguste** [comment]
Probably because of [this](https://github.com/oven-sh/bun/blob/acd361855ab67be451a92b80c38ce8bfc899d275/build.zig#L223) (which is "root.zig") being the first root that zls takes from the module list.

**Comment by Jarred-Sumner** [comment]
oh, sorry that is very reasonable.
