### ISSUE TITLE
Failed to find zls executable on MacOS

### ISSUE THREAD

**Issue by anta40** [zigtools/zls#1098]
### Zig Version

0.11.0-dev.2297+28d6dd75a

### Zig Language Server Version

0.11.0-dev.357+9a7d262

### Steps to Reproduce

First install [coc-zig](https://github.com/UltiRequiem/coc-zig):
`:CocInstall coc-zig`

Next is install zls, like described in the [manual](https://github.com/zigtools/zls#from-source). Then put zls in PATH.

Then edit the coc-settings.json like this
```
{
    "clangd.path": "/usr/local/opt/llvm/bin/clangd",
    "d.servedPath": "/Users/andre/.config/coc/extensions/coc-dlang-data/serve-d",

    "zig": {
        "command": "zls",
        "filetypes": [
            "zig"
        ]
    }
}
```

I'm on MacOS Monterey, BTW.

### Expected Behavior

When editing zig codes with vim/nvim, they will be highlighted properly.

### Actual Behavior

nvim gave this error:
`"[coc.nvim] Failed to find the zls executable! Please specify its path in your settings.`

**Comment by SuperAuguste** [comment]
Please see https://github.com/UltiRequiem/coc-zig#configuration; I imagine you need to set `"zig.path": "zls"` :)

**Comment by anta40** [comment]
Ahh I see. Now zls works.
