### ISSUE TITLE
unrecognized parameter: '--pkg-begin'

### ISSUE THREAD

**Issue by chrboesch** [zigtools/zls#1099]
### Zig Version

0.11.0-dev.2312+dd66e0add

### Zig Language Server Version

0.11.0-dev.357+9a7d262

### Steps to Reproduce

After a view minutes working with Neovim zls crashes.

### Expected Behavior

No crash.

### Actual Behavior

 After the crash, LSP-log shows the error:
```
[ERROR][2023-03-29 13:35:23] .../vim/lsp/rpc.lua:733	"rpc"	"zls"	"stderr"	"error: (store ): Failed to execute build runner to collect build configuration, command:\n/home/chris/.local/lib/zig/zig run /home/chris/.cache/zls/build_runner.zig --cache-dir /home/chris/.cache/zls --pkg-begin @build@ /home/chris/workspace/zig/test/build/3/build.zig --pkg-end -- /home/chris/.local/lib/zig/zig /home/chris/workspace/zig/test/build/3 zig-cache ZLS_DONT_CARE\nError: error: unrecognized parameter: '--pkg-begin'\n\nerror: (store ): Failed to load build configuration for file:///home/chris/workspace/zig/test/build/3/build.zig (error: error.RunFailed)\n"
```

**Comment by leecannon** [comment]
Your zls is too old to function with a recent version of zig master as the build runner and modules have changed in a backwards incompatible way.

**Comment by chrboesch** [comment]
Hm, I tried `git pull` on master to compile the latest version and get `Already up to date`.

**Comment by leecannon** [comment]
The command to execute the build runner that zls master uses is `zig build --build-runner build_runner.zig` (from `populateBuildConfigurationArgs` in DocumentStore.zig) this change was made in https://github.com/zigtools/zls/pull/1029.

Your zls is using the old build runner execution arguments with `--pkg-begin @build@ /home/chris/workspace/zig/test/build/3/build.zig --pkg-end` that zig master no long supports.

**Comment by chrboesch** [comment]
Ok, I will see if Mason changed my zls which I built yesterday. I put it always in the path `/home/chris/.local/share/nvim/mason/packages/zls/bin/` and that should work.

**Comment by chrboesch** [comment]
Indeed Mason changed my zls with its own build. Sorry for that issue. :disappointed:
