### ISSUE TITLE
The connected server does not support method textdocument/hover. [Emacs] 

### ISSUE THREAD

**Issue by ask6155** [zigtools/zls#110]
I connected ZLS to Emacs LSP and it works fine only when I edit a file and save it I get this error and the LSP server automatically stops. So it means I have to start it again everytime I save.

`Error running timer: (error "The connected server(s) does not support method textDocument/hover
To find out what capabilities support your server use ‘M-x lsp-describe-session’ and expand the capabilities section.")
`

**Comment by cmyka1b2c3d4** [comment]
``Error (use-package): lsp-ui/:config: The connected server(s) does not support method textDocument/hover.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section``

Sorry if this is the wrong place for it but is this related or did I screw up my emacs config?

**Comment by InterplanetaryEngineer** [comment]
This seems to be an error on the client side. Having not installed lsp-ui, I do not see this error, and ‘M-x lsp-describe-session’ shows
```
* Capabilities
    ...
    * hoverProvider: t
```

**Comment by psygo** [comment]
I'm having the same error when trying out LSP with TypeScript.

**Comment by Ivanknmk** [comment]
I fixed it by adding :after lsp to lsp-ui.

```(use-package lsp-ui
    :after lsp
    :hook (lsp-mode . lsp-ui-mode)
    :config
    (setq lsp-ui-sideline-enable t)
    (setq lsp-ui-sideline-show-hover nil)
    (setq lsp-ui-doc-position 'bottom)
    (lsp-ui-doc-show))```
