### ISSUE TITLE
error: no package named '@dependencies' available within package 'root'

### ISSUE THREAD

**Issue by bsolomon-bw** [zigtools/zls#1118]
### Zig Version

0.11.0-dev.2402+885300567

### Zig Language Server Version

55b1aeb

### Steps to Reproduce

I've built Zig from source at `885300567` against LLVM 15.0.7 as distributed via Homebrew on an x86_64 Mac running macOS 12.4.  Then, I cloned zls from tip, changed directories to it, and ran `zig build -Doptimize=ReleaseSafe`.

This has been going on for a while.  I haven't bisected (zig or zls) to identify when it started yet.

### Expected Behavior

ZLS should build correctly.

### Actual Behavior

After completing semantic analysis, the build fails with:

```
❯ zig build -Doptimize=ReleaseSafe -freference-trace
/Users/x/meta/build/zig/lib/build_runner.zig:13:34: error: no package named '@dependencies' available within package 'root'
pub const dependencies = @import("@dependencies");
                                 ^~~~~~~~~~~~~~~
referenced by:
    dependency__anon_10186: /Users/x/meta/build/zig/lib/std/Build.zig:1435:30
    build: /Users/x/meta/build/zls-test/build.zig:88:27
    runBuild__anon_7763: /Users/x/meta/build/zig/lib/std/Build.zig:1503:37
    steps__anon_6154: /Users/x/meta/build/zig/lib/build_runner.zig:891:20
    usage__anon_6147: /Users/x/meta/build/zig/lib/build_runner.zig:918:9
    usageAndErr__anon_5939: /Users/x/meta/build/zig/lib/build_runner.zig:1006:5
    main: /Users/x/meta/build/zig/lib/build_runner.zig:297:9
    callMain: /Users/x/meta/build/zig/lib/std/start.zig:619:32
    initEventLoopAndCallMain: /Users/x/meta/build/zig/lib/std/start.zig:553:34
    callMainWithArgs: /Users/x/meta/build/zig/lib/std/start.zig:503:12
    main: /Users/x/meta/build/zig/lib/std/start.zig:518:34
```

**Comment by truemedian** [comment]
How did you build zig? This error only happens when you have a build of zig with the package manager omitted.

**Comment by bsolomon-bw** [comment]
Oh, yeah that's got to be it.  I don't remember seeing anything about that in the build instructions for Zig, though.  In fact, I didn't even realize it was merged.  Can you point me to the docs for how to enable it in the build by any chance?  Here's my CMake invocation:

```sh
PATH="$(brew --prefix llvm@15)/bin:${PATH}" cmake .. -G Ninja \
  -DCMAKE_C_COMPILER=clang     \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DCMAKE_PREFIX_PATH="$(readlink -f $(brew --prefix llvm@15))" \
  -DCMAKE_PREFIX_PATH="$(brew --prefix z3)"   \
  -DCMAKE_PREFIX_PATH="$(brew --prefix zstd)" \
  -DCMAKE_BUILD_TYPE=Release
```

**Comment by nullptrdevs** [comment]
Definitely an issue with your Zig build. What I would check:
- make sure `zig version` reports the correct version
- check if issue occurs building other projects
- that dir path tells me you're not installing it (ninja/make install) and you're actually using zig2 which does indeed
```
> ~/lab/zig/build/zig2 build
/home/rad/lab/zig/lib/build_runner.zig:13:34: error: no package named '@dependencies' available within package 'root'
pub const dependencies = @import("@dependencies");
```

**Comment by jbsolomon** [comment]
Hi @nullptrdevs -- same guy, different account -- yes, I got the version I reported from `zig version`.  I haven't built too many things with Zig, but I usually keep this repo built from tip.  Yeah, I'm using zig2.  But using the install target doesn't seem to do anything.

**Comment by nullptrdevs** [comment]
Running `ninja install` should result in the creation of a `./stage3` dir; look for zig in `./stage3/bin/` :crossed_fingers: .

**Comment by jbsolomon** [comment]
Sweet!  That worked.  Thanks for the guidance.

**Comment by bsolomon-bw** [comment]
PEBKAC
