### ISSUE TITLE
comptime interpreter pitfall

### ISSUE THREAD

**Issue by leecannon** [zigtools/zls#1126]
I have seen an increase in issues recently that have been caused by people turning the comptime interpreter on.
Looking purely at the description of the option why _wouldn't_ someone who wants all the features of zls turn it on?

I think this is a mistake with the current state of it, we should make it much clearer that this option is currently experimental at best.

**Comment by SuperAuguste** [comment]
Good call, I added this as an easy toggle for occasional tinkering but clearly that isn’t conveyed. “dangerous_comptime_experiments_do_not_enable” is a name I’m partial towards :P
