### ISSUE TITLE
Need to create zls.json manually?

### ISSUE THREAD

**Issue by 20kano** [zigtools/zls#1127]
Isn't zls.json generated automatically?
Do I have to create it manually?
I have removed it by accident...

**Comment by 20kano** [comment]
Are the vls.json file and the VSCode Setting linked?
It doesn't seem to be.

**Comment by nullptrdevs** [comment]
Now that you mention it.. there used to be a setup/config option.. what OS are you using?

on *nix OSs it's at `~/.config/zls.json`
https://github.com/zigtools/zls/blob/master/schema.json offers an overview of the settings and here's an example
```
{
  "zig_exe_path": "/home/rad/lab/zig/build/zig",
  "enable_snippets": true,
  "enable_ast_check_diagnostics": true,
  "enable_autofix": true,
  "enable_import_embedfile_argument_completions": true,
  "warn_style": true,
  "semantic_tokens": "none",
  "enable_inlay_hints": true,
  "inlay_hints_show_builtin": true,
  "inlay_hints_exclude_single_argument": true,
  "inlay_hints_hide_redundant_param_names": true,
  "inlay_hints_hide_redundant_param_names_last_token": true,
  "operator_completions": true,
  "include_at_in_builtins": false,
  "max_detail_length": 1048576,
  "skip_std_references": true,
  "highlight_global_var_declarations": true,
  "use_comptime_interpreter": false
}
```

**Comment by 20kano** [comment]
Linux, Thanks!

**Comment by Techatrix** [comment]
Looks like this question has been answered. If there any more questions, feel free to head over to the [discussions](https://github.com/zigtools/zls/discussions) page.
