### ISSUE TITLE
Folding does not work correctly.

### ISSUE THREAD

**Issue by 20kano** [zigtools/zls#1131]
### Zig Version

0.11.0-dev.2571+31738de28

### Zig Language Server Version

0.11.0-dev.378+5457cec

### Steps to Reproduce

Empty parentheses.

Related to https://github.com/ziglang/vscode-zig/issues/97

### Expected Behavior

This behavior is without ZLS.
![範囲を選択_007](https://user-images.githubusercontent.com/119773193/231984929-29cefb44-4789-4df0-894a-bc4b0e070be3.png)

### Actual Behavior
`} else {` is missing.
![範囲を選択_008](https://user-images.githubusercontent.com/119773193/231985070-8eb1b3ad-0019-4509-a876-c070247acb6c.png)

**Comment by 20kano** [comment]
Other example.
std.log.zig:121

![範囲を選択_016](https://user-images.githubusercontent.com/119773193/232412006-b4b9438d-5a85-4818-b9f4-b616a5e1dc38.png)

without zls
![範囲を選択_017](https://user-images.githubusercontent.com/119773193/232412044-3151bd67-47df-4697-9917-0a1d71fe6878.png)

with zls
![範囲を選択_018](https://user-images.githubusercontent.com/119773193/232412080-e2e8708a-88e7-4653-8a22-f5aff425f33d.png)

**Comment by iacore** [comment]
Please paste the example code as text.
