### ISSUE TITLE
Couldn't find Zig Language Server (ZLS) executable at "/home/janne/.vscode-server/data/User/globalStorage/ziglang.vscode-zig/zls_install/zls"

### ISSUE THREAD

**Issue by nurpax** [zigtools/zls#1137]
### Zig Version

0.11.0-dev.1893+277015960

### Zig Language Server Version

0.3.2

### Steps to Reproduce

Start zig project with VScode by running `code .` in my zig project root.

This used to work for several weeks, I suddenly started getting this today:

![image](https://user-images.githubusercontent.com/297823/232422743-5a6acbe6-e799-4a46-8634-6aa78df776a3.png)

Directory `/home/janne/.vscode-server` doesn't exist.  I wonder if zls is looking into the wrong directory somehow?

I did use ZLS yesteray with Windows WSL, maybe VSCode WSL extension installation changed something that broke ZLS?

### Expected Behavior

I'd expect ZLS to start without problems in VSCode.

### Actual Behavior

Zig language extension in VSCode errors with:

```Couldn't find Zig Language Server (ZLS) executable at "/home/janne/.vscode-server/data/User/globalStorage/ziglang.vscode-zig/zls_install/zls"```

**Comment by nurpax** [comment]
Something had a added this line:

`    "zig.zls.path": "/home/janne/.vscode-server/data/User/globalStorage/ziglang.vscode-zig/zls_install/zls",`

into my VSCode user settings json file.  I deleted that line and restarted VSCode and it works now.

Maybe this got added when I started VSCode from within a WSL shell with `code .` that starts a VSCode remote session?  I'm keeping this open in case it's useful information for the developers.

**Comment by sansseriff** [comment]
Yes it has something to do with remotes, maybe also wsl. I setup zls on a remote computer named artemis, and now that I'm doing local development again, it's still looking at the remote path. 

<img width="339" alt="artemis" src="https://github.com/zigtools/zls/assets/43612007/83030736-3a6d-4817-87b1-5d87a13fcc19">

**Comment by brdjns** [comment]
Has a fix been found for this? I got this problem on WSL as well but deleting the line and reinstalling the Zig language extension failed to fix it.

**Comment by sansseriff** [comment]
Until there's a real fix, I had to uninstall vscode, delete it's appdata folder, and reinstall. 

For windows: https://stackoverflow.com/questions/47689536/how-to-completely-uninstall-vs-code-on-windows

Maybe you can get it  working just by deleting some zls folder in `%USER%\\.vscode\extensions`. Not sure.

**Comment by Techatrix** [comment]
this is an issue with the vscode-zig extension which is being tracked [here](https://github.com/ziglang/vscode-zig/issues/111).
