### ISSUE TITLE
zls not able to find symbol declarations at all for  some libraries

### ISSUE THREAD

**Issue by nurpax** [zigtools/zls#1139]
### Zig Version

0.11.0-dev.1893+277015960

### Zig Language Server Version

0.3.2

### Steps to Reproduce

Zls release from VSCode, not sure if it's ZLS or VSCode extension version.

I have a couple of projects that I work on where I'm finding that VSCode/ZLS is very much struggling to find any symbols.  ZLS works with files in the same directory and it's able to correctly look into standard library definitions. But pretty much anything else that I link in my build.zig doesn't work.

Are there some limitations in ZLS that prevent it from being able to resolve symbols across file/module boundaries?  For example, in this repo https://github.com/nurpax/zig-imgui/, I'm finding that opening file `examples/example_sokol_app.zig`, none of the symbols in the `imgui` module can be found.

Does ZLS somehow bypass build.zig or does it struggle with `std.build.LibExeObjStep.addAnonymousModule`?

Right now I'm looking for some workarounds in case there's something that can be done in build.zig to build the project differently to make it work better with ZLS.  

### Expected Behavior

Git clone: https://github.com/nurpax/zig-imgui/

Open `zig-imgui/examples/example_sokol_app.zig`, try to ctrl-click on any symbols prefixed with `imgui`.

I'd expect VSCode to take me to that particular symbol's definition.

### Actual Behavior

Ctrl-click does nothing.

**Comment by foxnne** [comment]
I have the same issue with `zgui`, zig-gamedev's dear imgui bindings. However, other libraries seem to work fine. I also do get `.` completion for zgui but hover/goto do not work. Q

**Comment by SuperAuguste** [comment]
Sorry, haven't been able to go through issues recently. Is this still broken for you? Could you try updating zls and Zig to latest and seeing if it works? Sometimes the build system/build system changes are finnicky and this could be a zls version mismatch. Thanks!

**Comment by nurpax** [comment]
I'm usually on Zig master, but I've been using zls through VSCode, e.g., just letting `ziglang.vscode-zig` install ZLS whichever way it does that. 

I now built zls from GitHub source and will try  if it works better.  Just noting: https://github.com/ziglang/vscode-zig#readme doesn't mention how to point the VSCode extension to point to my own zls nor does it suggest that this should be done.  If building zls from source (and trying to match it with zig dev version somehow?) is the recommended thing to do, perhaps the VSCode extension author could mention what's the most "stable" way to use this extension?

I will share my findings when I've had some time with my own build of ZLS.

**Comment by nurpax** [comment]
Filed a separate bug for the ArrayList type inference problem: https://github.com/zigtools/zls/issues/1166

I imagine you're aware of limitations such as this but thought a minimal repro case is anyway welcome.

I'm closing this bug and will file more specific issues as I have time to dig up minimal repros for them.
