### ISSUE TITLE
Immediate crash on startup

### ISSUE THREAD

**Issue by noxabellus** [zigtools/zls#115]
I've only just started trying to mess with zig today so perhaps I've missed something but I followed the directions building in readme and when I run the built executable I get a crash immediately after resolving standard library; this is the full log
```
Found zig in PATH: /home/nox/.local/bin/zig
Using zig executable /home/nox/.local/bin/zig
Resolved standard library from executable: /home/nox/.local/bin/lib/zig

MissingCarriageReturn; exiting!incorrect alignment
/home/nox/.local/lib/zig/std/heap.zig:146:51: 0x2363af in std.heap.PageAllocator.shrink (zls)
        const old_mem = @alignCast(mem.page_size, old_mem_unaligned);
                                                  ^
/home/nox/.local/lib/zig/std/mem.zig:279:44: 0x25d241 in std.mem.Allocator.free (zls)
        const shrink_result = self.shrinkFn(self, non_const_ptr[0..bytes_len], Slice.alignment, 0, 1);
                                           ^
/home/nox/zig/zls/src/main.zig:1194:54: 0x25ee10 in main (zls)
    defer if (zig_exe_path) |exe_path| allocator.free(exe_path);
                                                     ^
/home/nox/.local/lib/zig/std/start.zig:252:37: 0x2373ad in std.start.posixCallMainAndExit (zls)
            const result = root.main() catch |err| {
                                    ^
/home/nox/.local/lib/zig/std/start.zig:123:5: 0x2370ef in std.start._start (zls)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
Aborted (core dumped)
```

**Comment by alexnask** [comment]
Weird.  
Can you post your `zig version`?  
Also, what editor are you using?

**Comment by noxabellus** [comment]
zig version `0.6.0+09cded209`, downloaded from the site today
I was trying to use this with vs code, but opening a zig file with the extension activated results in two alerts which say
`Couldn't start client Zig Language Server Client`
and
`A request has failed. See the output for more information.`
and the output then says
```
[Error - 4:41:53 PM] Starting client failed
Launching server using command ~/.local/bin/zls failed.
```
Its only after running it manually from a terminal that I see the full log I posted originally.

My OS/distro is Pop!_OS 19.10 which is based on Ubuntu 19.10

**Comment by alexnask** [comment]
The error trace from the allocator looks like a standard library error.  

This error (or a similar one) is expected when launching the server manually, I am pretty sure all terminal emulators use `\n` newlines and the input expects HTTP headers (with `\r\n` newlines) and is probably not the error happening in VSCode.  

You should be able to see debug output in VSCode in the output tab like shown below  
![image](https://user-images.githubusercontent.com/265903/84580115-bb007080-addc-11ea-99a4-b0b068a6154d.png)

It would be very helpful if you could post the log, we have lots of VSCode users on linux and this is the firest time I hear of this issue :)

**Comment by noxabellus** [comment]
The output log I've posted in my second comment is all that I get
![image](https://user-images.githubusercontent.com/13547335/84580671-94234980-ad9e-11ea-9a5b-7336430fdff8.png)

**Comment by alexnask** [comment]
@noxabellus  
Ah, sorry I somehow missed this.  
It looks like VSCode can't spawn the process at all, can you try using the full absolute path without `~`, with `/home/<user>/`?

**Comment by noxabellus** [comment]
Well, I changed it
`"zigLanguageClient.path": "/home/nox/.local/bin/zls"`
but the error message still has the ~/ path
`Launching server using command ~/.local/bin/zls failed.`

**Comment by noxabellus** [comment]
Okay some new developments here;

I moved my install from `~/.local` to `/usr` and that stopped the error. Absolutely no idea why this would be the case.

That said, the extension only works if I have another zig extension enabled which provides syntax highlighting ([Zig](https://marketplace.visualstudio.com/items?itemName=tiehuis.zig)) 

Additionally, the default path that zls looks for the standard library is non typical for a linux install, `/usr/bin/lib/zig` instead of `/usr/lib/zig`, so I had to move it in order to finally get everything working

**Comment by alexnask** [comment]
@noxabellus  

Yes, we currently depend on the Zig extension (we mention this in the zls-vscode repository but I guess it should be made clearer in this repo as well).  
Hopefully with the next release of LSP we will do our own syntax highlighting and remove this dependency.  

The change of path fixing this is surprising, probably some permission issue although you did say you could run it manually so I really don't know 🤷   

The directory structure zls looks for by default mirrors the way the tarball downloads from the site are organized.  
You can point `zig_lib_path` in your zls.json file to the `lib/zig` directory instead, this is just the fallback option when none is provided, I assumed most users would use the tarballs from the site.  

Anyway, thanks for the patience, I hope you find it useful.  
You can find me on the zig IRC or discord if you have any questions btw, I hope you enjoy zig :)

**Comment by creationix** [comment]
FWIW, I'm seeing the exact same issue.

- Ubuntu `20.04`
- Zig `0.6.0+626b5ecca`
- Zls `108a2dbd64f764d414940870c6193642506e1e44` 
- VSCode `1.45.1`

I've got both the zig extension and the zls extension installed.  

![image](https://user-images.githubusercontent.com/89353/85932644-791f0200-b893-11ea-8bea-741c0375510a.png)

**Comment by creationix** [comment]
```zig
[debug-main] Found zig in PATH: /home/tim/zig-linux-x86_64-0.6.0+626b5ecca/zig

[debug-main] Using zig executable /home/tim/zig-linux-x86_64-0.6.0+626b5ecca/zig

[debug-main] Got workspace folders in initialization.

[debug-main] Loaded folder file:///home/tim/test-zig

[debug-main] ClientCapabilities{ .supports_snippets = true, .supports_semantic_tokens = true, .hover_supports_md = true, .completion_doc_supports_md = true, .supports_workspace_folders = true }

[debug-main] Took 0ms to process method initialize

[debug-main] Took 0ms to process method initialized

[debug-doc_store] Opened document: file:///home/tim/test-zig/src/main.zig

[debug-doc_store] Opened document: file:///home/tim/test-zig/build.zig

[debug-doc_store] Document is a build file, extracting packages...

[debug-doc_store] Finished zig run for build file file:///home/tim/test-zig/build.zig

[debug-main] Took 15ms to process method textDocument/didOpen

incorrect alignment
[debug-main] Took 0ms to process method textDocument/documentSymbol

[debug-main] Took 0ms to process method textDocument/completion

/home/tim/zig-linux-x86_64-0.6.0+626b5ecca/lib/zig/std/heap.zig:146:51: 0x24880f in std.heap.PageAllocator.shrink (zls)
        const old_mem = @alignCast(mem.page_size, old_mem_unaligned);
                                                  ^
/home/tim/zig-linux-x86_64-0.6.0+626b5ecca/lib/zig/std/mem.zig:279:44: 0x26f771 in std.mem.Allocator.free (zls)
        const shrink_result = self.shrinkFn(self, non_const_ptr[0..bytes_len], Slice.alignment, 0, 1);
                                           ^
/home/tim/zig-linux-x86_64-0.6.0+626b5ecca/lib/zig/std/json.zig:1638:35: 0x2f41f1 in std.json.parseFree (zls)
                    allocator.free(value);
                                  ^
/home/tim/zig-linux-x86_64-0.6.0+626b5ecca/lib/zig/std/json.zig:1602:33: 0x2841a9 in std.json.parseFree (zls)
                return parseFree(@TypeOf(v), v, options);
                                ^
/home/tim/zig-linux-x86_64-0.6.0+626b5ecca/lib/zig/std/json.zig:1619:26: 0x27606d in std.json.parseFree (zls)
                parseFree(field.field_type, @field(value, field.name), options);
                         ^
/home/tim/zls/src/main.zig:1453:29: 0x2712de in main (zls)
    defer std.json.parseFree(Config, config, config_parse_options);
                            ^
/home/tim/zig-linux-x86_64-0.6.0+626b5ecca/lib/zig/std/start.zig:252:37: 0x24984d in std.start.posixCallMainAndExit (zls)
            const result = root.main() catch |err| {
                                    ^
/home/tim/zig-linux-x86_64-0.6.0+626b5ecca/lib/zig/std/start.zig:123:5: 0x24958f in std.start._start (zls)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
```

**Comment by alexnask** [comment]
@creationix  
Tahnks for reporting this.  
Is it happening spontaneously or are you stopping the server?  
This is an issue in the cleanup code after the main loop is done, we should only ever get there when the text editor sends us a shutdown notification.  
I will be switching to a [the adma slab allocator soon](https://github.com/suirad/adma) which will probably fix this issue (unless it's a bug in the `parseFree` implementation, not sure).

**Comment by creationix** [comment]
This happens immediately at startup as soon as I trigger the first autocomplete.  I type `std.` and it blows up.
