### ISSUE TITLE
Can not compile with latest zig.

### ISSUE THREAD

**Issue by 20kano** [zigtools/zls#1155]
### Zig Version

0.11.0-dev.2777+b95cdf0ae

### Steps to Reproduce

```
git clone https://github.com/zigtools/zls
cd zls
zig build -Doptimize=ReleaseSafe
```

### Expected Behavior

No error.

### Actual Behavior

```
> zig build -Doptimize=ReleaseSafe
error: EndOfStream
```

**Comment by nektro** [comment]
this bug was fixed just recently, you might need to update Zig

**Comment by 20kano** [comment]
ok, I'll try, thanks.

**Comment by gwd666** [comment]
Again same error with version `0.12.0-dev.1861+412999621`
