### ISSUE TITLE
ZLS rejects for-loop with two arguments (slice, range)

### ISSUE THREAD

**Issue by rseichter** [zigtools/zls#1161]
### Zig Version

0.11.0-dev.2892+fd6200eda

### Zig Language Server Version

0.11.0-dev.401+b4bcbee

### Steps to Reproduce

Use zig init-exe to create a minimal project. Modify src/main.zig to print the slice of command line arguments created by `std.process.argsAlloc()` .

### Expected Behavior

ZLS should support the `for (someslice, 0..) |someitem, index| { ... }` type loop.

### Actual Behavior

(Edit: Updated to latest ZLS version. Problem persists.)

ZLS rejects the valid code segment with the error message `expected ')', found ','` :

<img width="497" alt="Bildschirmfoto 2023-04-30 um 14 58 29" src="https://user-images.githubusercontent.com/30873939/235354690-3beba476-75f0-4604-8463-dff1f200aa4c.png">

I am aware that this has been reported before in issue #1146 , which was closed. The workaround of removing `~/Library/Application Support/zls.json` does not apply, because this file does not exist on my Mac.

**Comment by truemedian** [comment]
Your zls version is a month old. You need to update

**Comment by leecannon** [comment]
Your ZLS version seems to be very old, master is `0.11.0-dev.401+b4bcbee` which means yours is 61 commits behind.

**Comment by rseichter** [comment]
Are you guys certain about the version number? I build ZLS afresh just now:
```
❯ git clone git@github.com:zigtools/zls.git ; cd zls
❯ zig build -Doptimize=ReleaseSafe
❯ zig-out/bin/zls --version
0.11.0-dev.401+b4bcbee
```

**Comment by oopsmonk** [comment]
have the same issue, configure and versions are:
```shell
$ zls --version
0.11.0-dev.402+94882d2
$ /snap/bin/zig version
0.11.0-dev.2939+289234744
$ cat .config/zls.json 
{
    "$schema": "https://raw.githubusercontent.com/zigtools/zls/master/schema.json",
    "zig_exe_path": "/snap/bin/zig",
    "enable_snippets": true,
    "enable_ast_check_diagnostics": true,
    "enable_autofix": false,
    "enable_import_embedfile_argument_completions": true,
    "warn_style": true,
    "enable_semantic_tokens": true,
    "enable_inlay_hints": true,
    "operator_completions": true,
    "include_at_in_builtins": false,
    "max_detail_length": 1048576
}
```

**Comment by nullptrdevs** [comment]
Here's a theory - client/editor configuration issue. Unfortunately it's not straightforward to tell if you're using/actually running latest, but some ideas:
* see if you get a completion for `@inco` (builtin `@inComptime()`, quite recent)
* try adding a debug statement in `main` or `Server`, recompiling and see if it shows up in the logs

**Comment by leecannon** [comment]
@oopsmonk I really don't know what to say, i'm using zig and zls master and the multi-object for loops works for me.

**Comment by oopsmonk** [comment]
> Here's a theory - client/editor configuration issue. Unfortunately it's not straightforward to tell if you're using/actually running latest, but some ideas:
> 
> * see if you get a completion for `@inco` (builtin `@inComptime()`, quite recent)
> * try adding a debug statement in `main` or `Server`, recompiling and see if it shows up in the logs

thanks for your hint. it was related to editor configuration.
I'm using Neovim with `mason-lspconfig.nvim` plugin. the problem is `mason-lspconfig` uses a prebuilt `zls 0.10.0` which is in `.local/share/nvim/mason/packages/zls/bin/zls`
My problem is solved after overriding the default path. :)

**Comment by leecannon** [comment]
okay, that would have been much easier to figure out with https://github.com/zigtools/zls/pull/1165

**Comment by oopsmonk** [comment]
@rseichter if you are using Neovim + Mason as well, refer to https://github.com/oopsmonk/NvimConfig/commit/5b2feb324396f04160b2bf027479f9258477ec18#diff-0fc5c43f6f1d7605fd7d16c088ba6b83f096eee8e2049517407bbaa27aa3a4f7

**Comment by rseichter** [comment]
> the problem is `mason-lspconfig` uses a prebuilt `zls 0.10.0` which is in `.local/share/nvim/mason/packages/zls/bin/zls`

Oho, that is quite a nasty pitfall, thank you for the pointer. When I replace this outdated binary with a softlink to the `zls` I built from source, the issue is resolved for me as well. I have opened a [discussion](https://github.com/williamboman/mason.nvim/discussions/1283) in the hope for additional feedback from William Bowman.

**Comment by rseichter** [comment]
Closing this issue, because it is not a bug of ZLS, but caused by an outdated `zls` binary in a [Mason package](https://github.com/mason-org/mason-registry/tree/main/packages/zls).
