### ISSUE TITLE
Incorrect enum autocomplete results in switch expression

### ISSUE THREAD

**Issue by Jarred-Sumner** [zigtools/zls#1188]
### Zig Version

0.11.0-dev.2571+31738de28

### Zig Language Server Version

HEAD

### Steps to Reproduce

ZLS shows autocomplete results for the return type in the function definition instead of the current type in the expression.

<img width="647" alt="image" src="https://github.com/zigtools/zls/assets/709451/b939a862-09cb-470b-afe6-dff041a2f268">

Something like this should reproduce it:
```zig
const First = enum { abc, def };
const Second = enum { foo, bar };

pub fn to(this: First) Second {
    return switch (this) {
        .abc => .foo,
       // always shows `Second` even when the current expression should filter to `First`
    };
}
```

### Expected Behavior

The list should filter to the correct type

### Actual Behavior

It autocompletes the wrong type

**Comment by Jarred-Sumner** [comment]
This is not fixed
<img width="780" alt="image" src="https://github.com/zigtools/zls/assets/709451/5f06f02c-2cff-4f85-941b-a48c23cf0561">

**Comment by Techatrix** [comment]
> This is not fixed

I've created a new issue for this special case #1535
