### ISSUE TITLE
Optimization: There are currently a large number of `read` syscall

### ISSUE THREAD

**Issue by Hanaasagi** [zigtools/zls#1189]
Every time I input, zls will use a large number of "read" system calls to read the request header from lsp, as shown in the following figure.

![2023-05-15_01-14](https://github.com/zigtools/zls/assets/9482395/4d3fa08d-97aa-4ed1-a811-ab8588fb8b26)

There is no use of a buffer in this code.

https://github.com/zigtools/zls/blob/91645612e61118af89b23d6766d47532b473827d/src/Header.zig#L24

This function is implemented by reading the bytes one by one.

https://github.com/ziglang/zig/blob/2ce9122a009efa0a5d2857a0d29ad3d77a81dff1/lib/std/io/reader.zig#L113-L133

I think we can change to https://ziglang.org/documentation/master/std/#A;std:io.BufferedReader and check the delimiter in the buffer.

**Comment by nektro** [comment]
you can alleviate this pressure by using `std.io.bufferedReader()`

**Comment by Hanaasagi** [comment]
Thanks for your friendly reminder. I found that there was a mistake in my Nvim configuration. It was not using my own compiled zls, but instead was using the zls provided by Mason (an LSP server manager) which was version 0.10.0. After switching to the latest version, the issue was resolved.

Thank you.
