### ISSUE TITLE
Zig master changed json API

### ISSUE THREAD

**Issue by kuon** [zigtools/zls#1190]
### Zig Version

0.11.0-dev.3138+87de8212ad

### Zig Language Server Version

91645612e61118af89b23d6766d47532b473827d

### Steps to Reproduce

Compile ZLS

### Expected Behavior

Should compile

### Actual Behavior

Error:

```
src/main.zig:337:52: error: expected type 'mem.Allocator', found 'Config'
        defer std.json.parseFree(Config, new_config.config, .{ .allocator = allocator });
                                         ~~~~~~~~~~^~~~~~~
```

Zig master changed the JSON API, `parseFree` arguments changed (`allocator` no longer an option) and `TokenStream` removed.

**Comment by xdBronch** [comment]
https://github.com/ziglang/zig/pull/15602
corresponding pr with the needed info
