### ISSUE TITLE
Modules not resolved

### ISSUE THREAD

**Issue by Deecellar** [zigtools/zls#1196]
### Zig Version

0.11.0-dev.3218+b873ce1e0

### Zig Language Server Version

0.11.0-dev.426+668d82d

### Steps to Reproduce

Minimal Reproduction at: https://github.com/Deecellar/xenia_glass/tree/157859dcc0a037be4e3af78f9737c847fa0ccdb6

- Start a new project
- Create a Build.zig.zon
- Reference the dependency in your project via modules

### Expected Behavior

Modules should be autocompleted

### Actual Behavior

It's not detecting them as modules

**Comment by Deecellar** [comment]
I am dumb =D

**Comment by sqrtroot** [comment]
Can you explain what error you made? I am seeing the same behavior I think.

**Comment by adworacz** [comment]
Same here - my zls instance is not resolving modules properly. This is with Neovim.

Please explain what your solution was.

**Comment by nullptrdevs** [comment]
> Same here - my zls instance is not resolving modules properly. This is with Neovim.
> 
> Please explain what your solution was.

Would be best to file a new issue, preferably with logs or at least a repository link.
