### ISSUE TITLE
autofix - handle edge case when comment follows capture

### ISSUE THREAD

**Issue by travisstaloch** [zigtools/zls#1204]
Follow up to #1202 which partially addresses #689

From https://github.com/zigtools/zls/pull/1202#discussion_r1207638446

We need to be able to autofix this which isn't currently implemented
```zig
if (1 == 1) |a|
    //a
    {}
```

**Comment by jowi-dev** [comment]
I'd like to take this one!

**Comment by jowi-dev** [comment]
@SuperAuguste out of curiosity - what is the expected outcome here?

should the snippet above become
```
if (1 == 1) |a|
// a 
```

?

**Comment by SuperAuguste** [comment]
Yep, that's correct @jowi-dev! :)
