### ISSUE TITLE
Unable to display inlay hints with Zig

### ISSUE THREAD

**Issue by junnplus** [zigtools/zls#1207]
Originated from:
https://github.com/junnplus/lsp-setup.nvim/issues/49#issuecomment-1563684632

I carefully examined the nvim log and read through the relevant code of zls. I found that when requesting `textDocument/inlayHint` for the first time, `enable_inlay_hints` was false, which resulted in an empty result being returned.

This is my configuration.
```lua
settings = {
    zls = {
        enable_inlay_hints = true,
        inlay_hints_show_builtin = true,
        inlay_hints_exclude_single_argument = true,
        inlay_hints_hide_redundant_param_names = true,
        inlay_hints_hide_redundant_param_names_last_token = true,
    }
}
```

nvim will send a `workspace/didChangeConfiguration` request before requesting inlay hints, but zls cannot correctly recognize the configuration with `zls` sections when processing this request.

zls will initiate a `workspace/configuration` request later to obtain the configuration, which will require viewing the configuration with the `zls` section.

```
[DEBUG][2023-05-28 17:01:16] .../vim/lsp/rpc.lua:387	"rpc.receive"	{
  id = "i_haz_configuration",
  jsonrpc = "2.0",
  method = "workspace/configuration",
  params = {
    items = { {
        section = "zls.enable_snippets"
      }, {
        section = "zls.enable_ast_check_diagnostics"
      }, {
        section = "zls.enable_autofix"
      }, {
        section = "zls.enable_import_embedfile_argument_completions"
      }, {
        section = "zls.semantic_tokens"
      }, {
        section = "zls.enable_inlay_hints"
      }, {
        section = "zls.inlay_hints_show_builtin"
```

So, why is the configuration different between the requests before and after?

**Comment by Hanaasagi** [comment]
https://github.com/neovim/neovim/blob/2028d1e2bc9fbba66552610b141df962cc550f88/runtime/lua/vim/lsp.lua#L1345-L1347

Neovim will pass the `settings` as the JSON-RPC parameter. Your settings include a nested table item `zls`. Perhaps you could try

```lua
require('lspconfig')['zls'].setup { capabilities = capabilities ,settings = { enable_inlay_hints = true } }
```

**Comment by junnplus** [comment]
> Neovim will pass the settings as the JSON-RPC parameter. Your settings include a nested table item zls. Perhaps you could try

I don't think you understood my point. I know that putting `enable_inlay_hints` directly into the `settings` works, but what confuses me is why the hierarchy for getting configuration is different between `workspace/configuration` and `workspace/didChangeConfiguration`. In other words, why doesn't putting `enable_inlay_hints` in `settings.zls` work?
