### ISSUE TITLE
cannot show all struct fields when `usingnamespace` and `@field` together

### ISSUE THREAD

**Issue by axojhf** [zigtools/zls#1219]
### Zig Version

0.11.0-dev.3329+1ab008d89

### Zig Language Server Version

5d53f0104fe6742a28592094f9f7de5060a6f07c

### Steps to Reproduce

Clone `https://github.com/ZigEmbeddedGroup/espressif-esp`, using Visual Studio Code to open `src/example/blinky.zig`, the fields of `microzig.chip` can not be fully displayed

### Expected Behavior

show all fields using `pub usingnamespace @field`

### Actual Behavior

Only show the `types` field

**Comment by nullptrdevs** [comment]
38a199813a1018305d4e85233950c2e6c8ca30a1
