### ISSUE TITLE
Improvement: Use JSON5 alongside JSON for config files

### ISSUE THREAD

**Issue by Himujjal** [zigtools/zls#1222]
Although not an urgent issue, I would like to add a PR for letting developers use JSON5 files as an option for configuration files.

I created a library [Himujjal/zig-json5](https://github.com/Himujjal/zig-json5) which allows one to use JSON5 in a way the standard library JSON parser/serializer API works without developers needing much effort. Its a one file library which is feature-frozen and only basic bug fixes are to be made if someone finds any (Till now, I haven't found for my use case).

Advantages over JSON:

1. Better comments (Single line and multi-line)
2. Unquoted keys
3. Trailing commas

Post the PR: ZLS can simply point to `zls.json5` as a first priority config file. If not found, revert to `zls.json`.

The implementation is easy to do. But a discussion is what I want.

NOTE: Awesome, awesome work on ZLS. I sometimes take reference from this repo for many of my Zig code!

**Comment by SuperAuguste** [comment]
In my opinion, this feels like scope-creep to me (a lot of extra work for a minor feature).

Nowadays, we're focusing more on in-editor configuration, which also tends to have a better editing experience (VSCode JSON configuration files are actually JSON5 I believe).
