### ISSUE TITLE
Getting inlay hints for method calls, but not normal function calls

### ISSUE THREAD

**Issue by bertie-wheen** [zigtools/zls#1240]
### Zig Version

0.11.0-dev.3395+1e7dcaa3a

### Zig Language Server Version

0.11.0-dev.480+83c9a7b

### Steps to Reproduce

Not sure that it matters, but I'm using ZLS through VSCode.

If you write a normal function call, e.g.:

`foo(a, b);`

nothing happens, but if you write a method call, e.g.:

`foo.bar(a, b);`

it'll display hints, e.g.:

`foo.bar(`_baz:_ `a, `_quux:_ `b);`

Note that it is specifically methods - if `bar` isn't a method, just a normal function that's a member of `foo`, then hints aren't displayed.

I don't know if this is a bug with my installation of if for some reason this is simply how it is.

If the former, I'd appreciate pointers as to what might be wrong, and if the latter, I'd like to recommend more general inlay hints.

### Expected Behavior

Have inlay hints for all functions, methods or not.

### Actual Behavior

Only have inlay hints for methods, and not other functions.

**Comment by Techatrix** [comment]
does #1258 resolve your issue? If not, can you provide a code snipped that reproduces the issue.

**Comment by bertie-wheen** [comment]
I'd disabled them, and re-enabling them now (with the latest version of ZLS) it seems (though this is admittedly at a bit of a glance, sorry) that I'm now getting inlay hints for methods and bare functions, but not namespaced functions, i.e. I don't get inlays for

`var stdout = std.io.bufferedWriter(std.io.getStdOut().writer());`,

where I'd expect

`var stdout = std.io.bufferedWriter(`underlying_stream: `std.io.getStdOut().writer());`

(as I have single argument inlays enabled), but I do for

`try stdout.writer().writeAll("foo\n");`,

where I get

`try stdout.writer().writeAll(`bytes: `"foo\n");`.

I don't get inlay hints for

    const bufferedWriter = std.io.bufferedWriter;
    var stdout = bufferedWriter(std.io.getStdOut().writer());

either, but if I write

    pub fn bufferedWriter(underlying_stream: anytype) std.io.BufferedWriter(4096, @TypeOf(underlying_stream)) {
        return std.io.bufferedWriter(underlying_stream);
    }

then for

`var stdout = bufferedWriter(std.io.getStdOut().writer());`

I do get the expected inlay hint

`var stdout = bufferedWriter(`underlying_stream: `std.io.getStdOut().writer());`

**Comment by bertie-wheen** [comment]
Yep, that seems to have fixed it.
