### ISSUE TITLE
sublime text: scope not updated while traversing scopes

### ISSUE THREAD

**Issue by ryuukk** [zigtools/zls#1247]
### Zig Version

0.11.0

### Zig Language Server Version

f8e8371f04d4cf342a5e88b670cbfdc356e6d3d8

### Steps to Reproduce

- Setup zls to work with sublime text as per documentation https://install.zigtools.org/
- ``const std = @import("std");``
- type ``std.`` (without pressing tab)

### Expected Behavior

It should show me symbols from ``std.zig`` file

### Actual Behavior

It just keep fuzzy search from the moment i typed ``s``

screencast:

- As i type ``std.``

https://github.com/zigtools/zls/assets/44361234/456c18c3-9d27-47cf-8469-dcac1fae7529

- I type ``std`` then i press TAB, then i press ``.``, now it shows proper symbols

https://github.com/zigtools/zls/assets/44361234/5b83e372-e6de-41dd-a113-a18042d71e02

**Comment by Techatrix** [comment]
I will be closing this since you correctly identified that this is an issue with sublime text LSP.
