### ISSUE TITLE
Port JSON code to the new API

### ISSUE THREAD

**Issue by leecannon** [zigtools/zls#1251]
Pulled out from https://github.com/zigtools/zls/issues/1248

As part of getting zls building on zig master after changes to the std json api in https://github.com/zigtools/zls/pull/1249 a temporary [wrapper](https://github.com/zigtools/zls/blob/master/src/legacy_json.zig) providing the old api was created as a stopgap to fix the build. 

@FalsePattern

**Comment by nullptrdevs** [comment]
Am I correct in thinking that the possible approaches are:

A: Keep Parsed(T) and pass it around
   - Pro: easy - access via `.value`, free up with `.deinit()`
   - Con: unknown size of `.arena`, probably insignificant for `BuildConfig` and `BuildAssociatedConfig`, and `Env` doesn't live long enough
               modifying values has to use and would grow `.arena`, ie `Config`

B: Implement `T.dupe()` and `T.deinit()` methods

C: use A or B depending on usage
