### ISSUE TITLE
error - building zls on windows

### ISSUE THREAD

**Issue by hgabe** [zigtools/zls#126]
Hello

I am getting ".\build.zig:1:28: error: invalid carriage return, only '\n' line endings are supported const std = @import("std");"
after zig build using Windows x64

Now I used the master next
"Semantic Analysis [531/1123] .\src\zinput\src\main.zig:1:28: error: invalid carriage return, only '\n' line endings are supported
const std = @import("std");"

**Comment by alexnask** [comment]
Hi, all files are commited to the repo with LF line endings.  
Your git settings are probably set to replace them with CRLF in your working copy.  
I believe there is some way to overwrite this in the repository, let me take a look and I should be able to fix this in a couple of minutes.

**Comment by alexnask** [comment]
This should be ok as of 02eabf533ea605443c95577dfa217390bec6ef51, can you pull and give it a shot (not sure if you need to make a clean clone for this change)?

**Comment by hgabe** [comment]
@alexnask  yea I'll do that now

**Comment by hgabe** [comment]
@alexnask  I reconfigure my core.autocrlf to input clone the repository again and compilation worked
so this issue can be closed

**Comment by alexnask** [comment]
Cheers!
