### ISSUE TITLE
Error building zls: "no member named 'reader' in struct 'std.fs.file.File'"

### ISSUE THREAD

**Issue by kbipp** [zigtools/zls#127]
**System**: Ubuntu 18.04 under WSL
**Zig version**: 0.6.0

Steps to reproduce:

1. Execute "git clone --recurse-submodules https://github.com/zigtools/zls"
2. Change into "zls" directory and run "zig build"
3. You should see the following error:
> ./src/main.zig:1355:37: error: no member named 'reader' in struct 'std.fs.file.File'
    const reader = std.io.getStdIn().reader();

**Comment by alexnask** [comment]
Hi, we currently only support building with zig in master branch.  
You can download a nightly release on the [Zig website](https://ziglang.org/download/)

**Comment by kbipp** [comment]
Sorry, I forgot to specify that I downloaded the version on master, which according to "zig version" is "0.6.0"

**Comment by alexnask** [comment]
@kbipp  
Master switched to using reader/write a week ago or so (see [here](https://github.com/ziglang/zig/blob/130c7fd23b9f23aa5afad2eb1744ffab9e193715/lib/std/fs/file.zig#L711))  
You may have an older version in PATH or you didnt copy the newest stdlib but just the executable (or something similar)
