### ISSUE TITLE
Doom Emacs instructions are out of date

### ISSUE THREAD

**Issue by gagbo** [zigtools/zls#1272]
The instructions on install.zigtools.org for Doom Emacs are out of date. Now Doom has a [`:lang zig`](https://github.com/doomemacs/doomemacs/tree/master/modules/lang/zig) module, so the instructions should be:

- enable `:tools lsp`
- enable `:lang (zig +lsp)`
- run `doom sync` in a terminal

**Comment by SuperAuguste** [comment]
See [these updated instructions](https://github.com/zigtools/zls/wiki/Installation#doom-emacs) :)
