### ISSUE TITLE
zls segmentation fault

### ISSUE THREAD

**Issue by WoodyAtHome** [zigtools/zls#128]
Hello!

today I cloned (108a2db) and built zls on my Ubuntu 19.10, x86_64.

I'm using the zig ubuntu snap package (edge):
```
woody@lappi:~/sources/zig/zls$ zig version
0.6.0+ac6bf5306
```

I did the `zls build` and `zls build config` successfully.
```
woody@lappi:~/sources/zig/zls$ cat zig-cache/bin/zls.json
{"zig_lib_path":"/snap/zig/current/lib/zig/","enable_snippets":false,"warn_style":false}
```
I installed the VSCode extension and added in the settings the path to zls:

I created a new project with zig init-exe in a new folder. Starting VSCode, I get this:
```
Segmentation fault at address 0x7f5269781008
/snap/zig/1818/lib/zig/std/special/c.zig:95:25: 0x4094fb in memset (c)
        dest.?[index] = c;
                        ^
/snap/zig/1818/lib/zig/std/mem.zig:327:53: 0x2645ae in std.mem.Allocator.reallocAdvanced (zls)
        const new_byte_slice = try self.reallocBytes(old_byte_slice, Slice.alignment, byte_count, new_alignment,
                                                    ^
/snap/zig/1818/lib/zig/std/mem.zig:283:36: 0x263fc1 in std.mem.Allocator.realloc (zls)
        return self.reallocAdvanced(old_mem, old_alignment, new_n, .exact);
                                   ^
/snap/zig/1818/lib/zig/std/array_list.zig:204:48: 0x263e0e in std.array_list.ArrayListAligned(u8,null).shrink (zls)
            self.items = self.allocator.realloc(self.allocatedSlice(), new_len) catch |e| switch (e) {
                                               ^
/snap/zig/1818/lib/zig/std/io/reader.zig:70:38: 0x2bfb3b in std.io.reader.Reader(std.fs.file.File,std.os.ReadError,std.fs.file.File.read).readAllArrayList (zls)
                    array_list.shrink(start_index);
                                     ^
/snap/zig/1818/lib/zig/std/io/reader.zig:86:38: 0x285b9d in std.io.reader.Reader(std.fs.file.File,std.os.ReadError,std.fs.file.File.read).readAllAlloc (zls)
            try self.readAllArrayList(&array_list, max_size);
                                     ^
/home/woody/sources/zig/zls/src/main.zig:961:53: 0x277683 in loadConfig (zls)
    const file_buf = conf_file.reader().readAllAlloc(allocator, 0x1000000) catch return null;
                                                    ^
/home/woody/sources/zig/zls/src/main.zig:1470:23: 0x26fc1f in main (zls)
        if (loadConfig(exe_dir_path)) |conf| {
                      ^
/snap/zig/1818/lib/zig/std/start.zig:252:37: 0x249b3d in std.start.posixCallMainAndExit (zls)
            const result = root.main() catch |err| {
                                    ^
/snap/zig/1818/lib/zig/std/start.zig:123:5: 0x24987f in std.start._start (zls)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
[Info  - 11:23:47] Connection to server got closed. Server will restart.
```
No idea, what's wrong. Thx for help!

**Comment by alexnask** [comment]
@WoodyAtHome Hi, thanks for reporting, I will try to reproduce soon.  

What is your `zig version` btw?  
There were some allocator interface changes yesterday and I want to rule that out :)

**Comment by WoodyAtHome** [comment]
I extended the issue: Now you can find the zig version and I had to correct the path to std (in zls.json)

**Comment by alexnask** [comment]
@WoodyAtHome Thanks for updating the issue.  
I can't find this commit hash on the zig repo which is weird.  
Anyway I will be updating zls to master later today as pretty big changes happened yesterday, your zig version appears to be using the new allocator interface which may have broken some std lib code (judging by the `reallocAdvanced` in the code) so I will probably hit this issue as well.  

I will ping you here if I do and I fix it :)

**Comment by alexnask** [comment]
@WoodyAtHome This does seem to be caused by a couple of std library bugs.  
I introduced a workaround so I can go and fix them upstream then update here.  
I would apppreciate if you could test now (note that this now needs the latest master commit to build, idk how up to date the snap package is, the nightly build on the website is complete though)  
Thanks again :)

**Comment by WoodyAtHome** [comment]
Hi Alex,

you're pretty fast. With the snap-zig compiler I get compile errors and it is still the 0.6.0+ac6bf5306 version.
To compile the latest compiler by myself I would need to compile llvm-10 first. So I guess it's better to wait till tomorrow, then I should have automatically a zig compiler newer or equal 581d161. Sorry for being so slow.

**Comment by alexnask** [comment]
@WoodyAtHome Haha, it's okay let me know when you can test it :)  
FYI master builds are available [here](https://ziglang.org/download/) but I understand if you prefer just to keep zig up to date with your package manager.  

Cheers!

**Comment by WoodyAtHome** [comment]
> FYI master builds are available [here](https://ziglang.org/download/) but 

It is the same version as in the snap package. I already tried it this morning :-)

**Comment by WoodyAtHome** [comment]
Ok, snap package and master builds were updated, I tried and .......works! Thank you for you quick fix!

**Comment by WoodyAtHome** [comment]
Wow, is zig coding cool now...I like the tool tip with the help comments so much. Great.

**Comment by alexnask** [comment]
Cool, let me know if you stumble upon any other bugs, there are bound to be a couple of sneaky ones.  
This is great since they will result in upstream zig bug fixes :P
