### ISSUE TITLE
Hovering over a type shows the entire declaration

### ISSUE THREAD

**Issue by leecannon** [zigtools/zls#1301]
Hovering over a type shows the entire declaration with the doc comment at the bottom of the tooltip.

A declaration could be thousands or tens of thousands of lines long, we should not reply with the whole thing.

```zig
/// Comment
const S = struct {
    f: u32,

    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
    fn a() void {}
};

pub fn main() !void {
    var s: S = undefined;
    _ = s;
}
```
![image](https://github.com/zigtools/zls/assets/2286349/e2805f4c-6957-4756-8eb3-030f590dcee3)

**Comment by nullptrdevs** [comment]
I would be for this if it meant stripping the fn bodies but keeping signatures and fields info.

**Comment by FnControlOption** [comment]
@nullptrdevs For what it's worth, VS Code has a Peek Definition feature (but it still doesn't strip function bodies)
