### ISSUE TITLE
New de-aliasing/alias following hides declarations

### ISSUE THREAD

**Issue by InKryption** [zigtools/zls#1306]
### Zig Version

0.11.0-dev.3949+27a66191c

### Zig Language Server Version

0.11.0-dev.551+c3cd9a7

### Steps to Reproduce

Trigger auto-completion of a declaration, wherein the declaration is an alias of another declaration.

### Expected Behavior

For the alias name to be available in the list of auto-completions, alongside the declaration it is an alias of if these two happen to share a namespace.

### Actual Behavior

The alias name does not appear in the list of auto-completions, instead displaying the name of the declaration it is an alias of, displaying a duplicate entry for the aliased declaration if they happen to share a namespace.

Example in helix:
![Selection_001](https://github.com/zigtools/zls/assets/59504965/b90de24a-d531-40e4-89cc-663ed88abf3a)
![Selection_002](https://github.com/zigtools/zls/assets/59504965/82176dfc-20e5-4b9d-9f75-7eb1c05a2841)

**Comment by FnControlOption** [comment]
This likely explains the name restriction mentioned in #1273:

> For some reason, var decl alias resolution had some artificial restrictions like requiring that var decl name is the same as the right side of the field access.
