### ISSUE TITLE
no member named 'reader' in struct 'std.fs.file.File'

### ISSUE THREAD

**Issue by repr-man** [zigtools/zls#131]
I don't know if this is the correct place for this question, so please let me know if I should post it somewhere else.

I was following the instructions to set up zls for VSCode.  When I ran `zig build`, it gave me the following error:
```
./src/main.zig:1389:37: error: no member named 'reader' in struct 'std.fs.file.File'
    const reader = std.io.getStdIn().reader();
                                    ^
zls...The following command exited with error code 1:
/usr/lib/zig/0.6.0/zig build-exe /home/jex/zls/src/main.zig --pkg-begin build_options /home/jex/zls/zig-cache/zls_build_options.zig --pkg-end --cache-dir /home/jex/zls/zig-cache --name zls --pkg-begin known-folders /home/jex/zls/src/known-folders/known-folders.zig --pkg-end --cache on 

Build failed. The following command failed:
/home/jex/zls/zig-cache/o/1CL-wEqcEqAQFApdDMyZX4gUT1DYtLFtKqqSDpjI01an6D0WNGHapeP6zWlzsQbS/build /usr/lib/zig/0.6.0/zig /home/jex/zls /home/jex/zls/zig-cache
```
I am using the Ubuntu 18.04 package.  I don't know if this is a problem with the Zig package or with zls.  Could someone please direct me to the solution?

**Comment by alexnask** [comment]
Hi, we currently require a zig master branch build to compile zls.  
You can download nightly executables on [the website](https://ziglang.org/download/).

**Comment by repr-man** [comment]
Thanks for the help.  It worked great!
