### ISSUE TITLE
Commit a73897b34031e340c4ac28657bd4089da9688494 breaks ZLS

### ISSUE THREAD

**Issue by arrufat** [zigtools/zls#1314]
### Zig Version

0.11.0-dev.3970+7a8002a5c

### Zig Language Server Version

a73897b34031e340c4ac28657bd4089da9688494

### Steps to Reproduce

Build ZLS at commit a73897b34031e340c4ac28657bd4089da9688494.
Start an editor with ZLS configure (in my case, Kakoune + kak-lsp)

### Expected Behavior

Run normally, without any errors.

Let me know if there's anything else I can do to help debug this :)

### Actual Behavior

I get an error from my editor saying: `InternalError`.
Previous commit (5e5a55e8ef1f247a6332e1e954abd1e7a56e9e7e) works fine.

**Comment by leecannon** [comment]
@arrufat can you check if the issue is fixed by https://github.com/zigtools/zls/pull/1318

**Comment by arrufat** [comment]
Yes, that solved the issue, thank you!
