### ISSUE TITLE
Commit fb56ae120f08b23242df39a952bbcd831ce248c2 breaks ZLS

### ISSUE THREAD

**Issue by arrufat** [zigtools/zls#1324]
### Zig Version

0.11.0-dev.3987+2896266a0

### Zig Language Server Version

fb56ae120f08b23242df39a952bbcd831ce248c2

### Steps to Reproduce

Build commit fb56ae120f08b23242df39a952bbcd831ce248c2 and start an editing session.

### Expected Behavior

Run normally

### Actual Behavior

ZLS exits with this error: `ParseError`.

Let me know if there's anything I can do to help with the debugging.

**Comment by arrufat** [comment]
At least it's different from #1314, where it returned `InternalError` :)

**Comment by Techatrix** [comment]
does #1325 resolve your issue?

**Comment by rlbaker** [comment]
I alsouse nvim & zls and experienced the error reported in this issue. https://github.com/zigtools/zls/pull/1325 appears to resolve the issue for me.

**Comment by arrufat** [comment]
@Techatrix yes, that PR fixes it. Thank you!

**Comment by leecannon** [comment]
#1325 is merged
