### ISSUE TITLE
Feature Request: completions for slice iteration

### ISSUE THREAD

**Issue by prime31** [zigtools/zls#133]
When doing something like the following it would be awesome to have completions for the item:

```rust
for (some_slice) |item| {
    item.COMPLETE_ME
}```

**Comment by alexnask** [comment]
This works as long as the expression's type can be evaluated by zls, e.g.:  
```zig
var val: []std.fs.File = undefined;
for (val) |v| {
    // v. completes as expected       
}
```

Notably it doesn work for array list items fields because they are defined as `Slice` which depends on the alignment passed in to the type functon.

**Comment by prime31** [comment]
oh yeah, it does. I guess the ArrayList bit was what tripped me up since I have those damn things all over the place. I'm guessing its not possible to fetch the ArrayList item Type?

**Comment by alexnask** [comment]
I aim to support it at some point.  
The specific feature I would need for ArrayList if evaluation of comptime if (...) with nullable types (Slice depends on the alignment).  
Anyway, basic comptime evaluation engien is coming soonish
