### ISSUE TITLE
Support for workspace/configuration and workspace/didChangeConfiguration

### ISSUE THREAD

**Issue by CherryMan** [zigtools/zls#134]
This feature would allow the client to configure `zls` itself, so users can configure `zls` through their respective editor instead of using `zls.json`.

If this feature request is approved I'll gladly work on a PR.

**Comment by alexnask** [comment]
This sounds good to me, let me know if you want to work on it, I will implement it otherwise.

**Comment by tamago324** [comment]
Hello.
I am interested in developing this feature.

I don't think there is currently a mechanism for the server to send requests to the client, are there any plans to implement that?
I would like to implement a mechanism for sending requests, but I'm new to zig, so I would appreciate some advice if you can help me.
