### ISSUE TITLE
for info, in zinput/src, there's wrong carriage retrun..

### ISSUE THREAD

**Issue by ffred** [zigtools/zls#136]
Hi, just cloned zls here on Windows and it can't build because of the files in zinput/src having wrong carriage return.
build ok after changing carriage return in the two files.

**Comment by SuperAuguste** [comment]
Hey @ffred! This seems to be an issue with `git` that, sadly, happens much too often on Windows. The carriage returns were invalid as zinput does not have a gitattributes file and autocrlf seems to be enabled on Windows systems by default. I'll look into fixing this now!

**Comment by ffred** [comment]
nope, sorry..  just tried it again and still have to change the carriage return int the two zinput/src file to be able to build.

**Comment by SuperAuguste** [comment]
Interesting! It seems that this could be a `git submodules` sorta thing. I'll look into that potentially being the issue!

**Comment by ffred** [comment]
only have one .gitattributes in zls root directory..

**Comment by data-man** [comment]
https://stackoverflow.com/questions/2466959/git-removing-carriage-returns-from-source-controlled-files
---on Windows---
```sh
git config --global core.autocrlf true
git config --global core.safecrlf false
```
---on Linux---
```sh
git config --global core.autocrlf input
git config --global core.safecrlf false
```

**Comment by SuperAuguste** [comment]
Thanks for the help @data-man! I want to try to ensure that people in the future don't have to turn off autocrlf! I guess submodules stand in our way for now. The best solution is to get every dependency to have a `.gitattributes` and to update the submodules to the latest commit, but that will likely not happen immediately.

Sorry about all the trouble @ffred!

**Comment by ffred** [comment]
no problem.. that was easy to "solve" on my side. just wanted to let you know.
thanks.
