### ISSUE TITLE
Enable discussions for the organization

### ISSUE THREAD

**Issue by data-man** [zigtools/zls#137]
Example: https://github.com/nlohmann/json/discussions

Just the idea. :)

**Comment by SuperAuguste** [comment]
Hey @data-man! Thank you so much for the suggestion! After looking into it, this feature (at least in repo form) still seems to be in selective access mode, with only larger repos getting access to it. The second it enters public beta, we'll add it to our repos!

**Comment by data-man** [comment]
> The second it enters public beta, we'll add it to our repos!

Check it out now! :smile:

**Comment by SuperAuguste** [comment]
Thanks for the suggestion! It's up and running now:
https://github.com/zigtools/zls/discussions/235
