### ISSUE TITLE
ZLS 0.11?

### ISSUE THREAD

**Issue by jeffbdavenport** [zigtools/zls#1391]
Where is the tag for ZLS 0.11? I can't seem to find the right commit for zig 0.11

**Comment by Techatrix** [comment]
ZLS 0.11.0 has been [tagged](https://github.com/zigtools/zls/tree/0.11.0) but there is no github release yet...
@SuperAuguste

**Comment by SuperAuguste** [comment]
Sorry, doing now @Techatrix. :)
