### ISSUE TITLE
no member named 'extern_export_inline_token' in struct 'std.zig.ast.FnProto'

### ISSUE THREAD

**Issue by markfirmware** [zigtools/zls#140]
installing latest zig
    zig version 0.6.0+6b103324d

    installing latest zls - zig language server
    ./src/main.zig:215:43: error: no member named 'extern_export_inline_token' in struct 'std.zig.ast.FnProto'
                        const is_extern = func.extern_export_inline_token != null;
                                              ^
    ./src/main.zig:1129:5: note: referenced here
        try publishDiagnostics(arena, handle.*, configFromUriOr(req.params.textDocument.uri, config));
        ^
    ./src/analysis.zig:973:21: error: no member named 'init_node' in struct 'std.zig.ast.VarDecl'
            if (var_decl.init_node == null) continue;
                        ^
    ./src/document_store.zig:358:5: note: referenced here
        try analysis.collectImports(&import_strs, handle.tree);
        ^
    ./src/document_store.zig:467:5: note: referenced here
        try self.refreshDocument(handle, zig_lib_path);
        ^
    ./src/main.zig:1141:5: note: referenced here
        try document_store.applyChanges(handle, req.params.contentChanges.Array, local_config.zig_lib_path);
        ^
    ./src/analysis.zig:443:33: error: container 'std.zig.ast.Node' has no member called 'PrefixOp'
        if (deref_node.cast(ast.Node.PrefixOp)) |pop| {
                                    ^
    ./src/analysis.zig:1025:30: note: referenced here
                    .unwrapped = try resolveDerefType(store, arena, current_type, &bound_type_params),
                                 ^
    ./src/main.zig:930:9: note: referenced here
        if (try analysis.getFieldAccessType(&document_store, arena, handle, position.absolute_index, &tokenizer)) |result| {
            ^
    ./src/main.zig:1200:38: note: referenced here
                .field_access => |range| try completeFieldAccess(arena, id, handle, doc_position, range, this_config),
                                         ^
    ./src/analysis.zig:277:21: error: no member named 'init_node' in struct 'std.zig.ast.VarDecl'
            if (var_decl.init_node == null) return null;
                        ^
    ./src/main.zig:512:21: note: referenced here
                    if (try analysis.resolveVarDeclAlias(&document_store, arena, .{ .node = node, .handle = handle })) |result| {
                        ^
    ./src/main.zig:645:12: note: referenced here
        return try gotoDefinitionSymbol(id, arena, decl, resolve_alias);
               ^
    ./src/main.zig:1246:28: note: referenced here
                .var_access => try gotoDefinitionGlobal(arena, id, doc_position.absolute_index, handle, this_config, resolve_alias),
                               ^
    ./src/main.zig:1258:5: note: referenced here
        try gotoHandler(arena, id, req, config, true);
        ^
    ./src/references.zig:398:24: error: no member named 'body_node' in struct 'std.zig.ast.FnProto'
                if (fn_node.body_node) |body| {
                           ^
    ./src/rename.zig:39:36: note: called from here
        try references.symbolReferences(arena, store, decl_handle, encoding, true, RefHandlerContext{
                                       ^
    ./src/rename.zig:37:9: note: called from here
    ) !void {
            ^
    ./src/rename.zig:39:5: note: referenced here
        try references.symbolReferences(arena, store, decl_handle, encoding, true, RefHandlerContext{
        ^
    ./src/main.zig:741:5: note: referenced here
        try rename.renameSymbol(arena, &document_store, decl, new_name, &workspace_edit.changes.?, offset_encoding);
        ^
    ./src/main.zig:1350:28: note: referenced here
                .var_access => try renameDefinitionGlobal(arena, id, handle, doc_position.absolute_index, req.params.newName),
                               ^
    ./src/references.zig:398:24: error: no member named 'body_node' in struct 'std.zig.ast.FnProto'
                if (fn_node.body_node) |body| {
                           ^
    ./src/main.zig:785:36: note: called from here
        try references.symbolReferences(arena, &document_store, decl, offset_encoding, include_decl, &locs, std.ArrayList(types.Location).append);
                                       ^
    ./src/main.zig:782:160: note: called from here
    fn referencesDefinitionGlobal(arena: *std.heap.ArenaAllocator, id: types.RequestId, handle: *DocumentStore.Handle, pos_index: usize, include_decl: bool) !void {
                                                                                                                                                                   ^
    ./src/main.zig:785:5: note: referenced here
        try references.symbolReferences(arena, &document_store, decl, offset_encoding, include_decl, &locs, std.ArrayList(types.Location).append);
        ^
    ./src/main.zig:1373:28: note: referenced here
                .var_access => try referencesDefinitionGlobal(arena, id, handle, doc_position.absolute_index, include_decl),
                               ^
    ./src/analysis.zig:2096:21: error: no member named 'body_node' in struct 'std.zig.ast.FnProto'
                if (func.body_node) |body| {
                        ^
    ./src/semantic_tokens.zig:551:9: error: enum 'std.zig.ast.Id' has no field named 'PrefixOp'
            .PrefixOp => {
            ^
    /workspace/pluto/tools/zig/lib/zig/std/zig/ast.zig:401:20: note: 'std.zig.ast.Id' declared here
        pub const Id = enum {
                       ^
    ./src/semantic_tokens.zig:235:5: note: referenced here
        switch (node.id) {
        ^
    ./src/references.zig:239:9: error: enum 'std.zig.ast.Id' has no field named 'PrefixOp'
            .PrefixOp => {
            ^
    ./src/references.zig:375:45: note: called from here
                    try symbolReferencesInternal(arena, store, .{ .node = &handle.tree.root_node.base, .handle = handle }, decl_handle, encoding, context, handler);
                                                ^
    ./src/rename.zig:39:36: note: called from here
        try references.symbolReferences(arena, store, decl_handle, encoding, true, RefHandlerContext{
                                       ^
    ./src/rename.zig:37:9: note: called from here
    ) !void {
            ^
    /workspace/pluto/tools/zig/lib/zig/std/zig/ast.zig:401:20: note: 'std.zig.ast.Id' declared here
        pub const Id = enum {
                       ^
    ./src/references.zig:78:5: note: referenced here
        switch (node.id) {
        ^
    ./src/references.zig:239:9: error: enum 'std.zig.ast.Id' has no field named 'PrefixOp'
            .PrefixOp => {
            ^
    ./src/references.zig:375:45: note: called from here
                    try symbolReferencesInternal(arena, store, .{ .node = &handle.tree.root_node.base, .handle = handle }, decl_handle, encoding, context, handler);
                                                ^
    ./src/main.zig:785:36: note: called from here
        try references.symbolReferences(arena, &document_store, decl, offset_encoding, include_decl, &locs, std.ArrayList(types.Location).append);
                                       ^
    ./src/main.zig:782:160: note: called from here
    fn referencesDefinitionGlobal(arena: *std.heap.ArenaAllocator, id: types.RequestId, handle: *DocumentStore.Handle, pos_index: usize, include_decl: bool) !void {
                                                                                                                                                                   ^
    /workspace/pluto/tools/zig/lib/zig/std/zig/ast.zig:401:20: note: 'std.zig.ast.Id' declared here
        pub const Id = enum {
                       ^
    ./src/analysis.zig:10:20: error: no member named 'doc_comments' in struct 'std.zig.ast.FnProto'
            return func.doc_comments;
                       ^
    ./src/main.zig:421:9: error: enum 'std.zig.ast.Id' has no field named 'PrefixOp'
            .PrefixOp => {
            ^
    /workspace/pluto/tools/zig/lib/zig/std/zig/ast.zig:401:20: note: 'std.zig.ast.Id' declared here
        pub const Id = enum {
                       ^
    ./src/main.zig:335:5: note: referenced here
        switch (node.id) {
        ^
    ./src/analysis.zig:185:21: error: no member named 'name_token' in struct 'std.zig.ast.FnProto'
                if (func.name_token == null) return null;
                        ^
    ./src/analysis.zig:1354:86: error: enum 'std.zig.ast.Id' has no field named 'PrefixOp'
            .StringLiteral, .IntegerLiteral, .BuiltinCall, .Call, .Identifier, .InfixOp, .PrefixOp, .SuffixOp, .ControlFlowExpression, .ArrayInitializerDot, .SwitchElse, .SwitchCase, .For, .EnumLiteral, .PointerIndexPayload, .StructInitializerDot, .PointerPayload, .While, .Switch, .Else, .BoolLiteral, .NullLiteral, .Defer, .StructInitializer, .FieldInitializer, .If, .MultilineStringLiteral, .UndefinedLiteral, .AnyType, .Block, .ErrorSetDecl => return,
                                                                                         ^
    /workspace/pluto/tools/zig/lib/zig/std/zig/ast.zig:401:20: note: 'std.zig.ast.Id' declared here
        pub const Id = enum {
                       ^
    ./src/analysis.zig:1353:5: note: referenced here
        switch (child.id) {
        ^
    ./src/analysis.zig:741:9: error: enum 'std.zig.ast.Id' has no field named 'PrefixOp'
            .PrefixOp => {
            ^
    /workspace/pluto/tools/zig/lib/zig/std/zig/ast.zig:401:20: note: 'std.zig.ast.Id' declared here
        pub const Id = enum {
                       ^
    ./src/analysis.zig:570:5: note: referenced here
        switch (node.id) {
        ^
    ./src/analysis.zig:1134:28: error: no member named 'visib_token' in struct 'std.zig.ast.VarDecl'
                return var_decl.visib_token != null;
                               ^
    zls...The following command exited with error code 1:
    /workspace/pluto/tools/zig/zig build-exe /workspace/pluto/tools/zls/src/main.zig --pkg-begin build_options /workspace/pluto/tools/zls/zig-cache/zls_build_options.zig --pkg-end --cache-dir /workspace/pluto/tools/zls/zig-cache --name zls --pkg-begin known-folders /workspace/pluto/tools/zls/src/known-folders/known-folders.zig --pkg-end --cache on 
    
    Build failed. The following command failed:
    /workspace/pluto/tools/zls/zig-cache/o/rPMwsZiw2cjpDkL2hs7_0KJ1oRVcWLhpHECnHDfrmZa62kuTt3x5aFZvo1m11Vu6/build /workspace/pluto/tools/zig/zig /workspace/pluto/tools/zls /workspace/pluto/tools/zls/zig-cache -Ddata_version=master

**Comment by data-man** [comment]
#139

**Comment by data-man** [comment]
@alexnask @SuperAuguste 

I think an issue template will be useful for such issues. :)

**Comment by SuperAuguste** [comment]
I agree @data-man! I'm fixing all of these latest Zig version issues now!

**Comment by SuperAuguste** [comment]
Should be fixed!
