### ISSUE TITLE
Struct completion is broken

### ISSUE THREAD

**Issue by SuperAuguste** [zigtools/zls#141]
After the latest update, struct field completions seem to no longer work. I'm not sure why at this moment, but I'm looking further into it.

Reproducible code
```zig
pub const MyStruct = struct {
    pub const doritolicious = 10;

    dorito: u8,
    potato: bool
};

pub fn main() !void {
    const my_struct: MyStruct = undefined;
    // my_struct should complete with doritolicious, dorito, and potato, but only the first one appears
}
```

**Comment by alexnask** [comment]
Yes some container fields don't work, I will have time to start working on those bugfixes and some features starting tomorrow.

**Comment by alexnask** [comment]
This is fixed now, hover and goto still broken, fixing them atm.
