### ISSUE TITLE
Failure to download packages when running `zig build` on btrfs

### ISSUE THREAD

**Issue by daurnimator** [zigtools/zls#1428]
### Zig Version

0.11.0

### Zig Language Server Version

0.11.0

### Steps to Reproduce

Download the ZLS 0.11.0 release and run `zig build`

### Expected Behavior

Build ZLS

### Actual Behavior

```
$ zig version
0.11.0
$ zig build --help
Fetch Packages [1/3] known_folders... /var/lib/archbuild/extra-x86_64/daurnimator-0/build/zls/src/zls-0.11.0/build.zig.zon:8:21: error: hash mismatch: expected: 122048992ca58a78318b6eba4f65c692564be5af3b30fbef50cd4abeda981b2e7fa5, found: 1220206c698a1890d742a8b98acb16db99275d16f2e7fe2046c3d8f2249ed267ca71
            .hash = "122048992ca58a78318b6eba4f65c692564be5af3b30fbef50cd4abeda981b2e7fa5",
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~```

**Comment by thomab** [comment]
I got this too, but on master.

Did the top folder inside the tarballs always have the commit hash in the name? I didn't have any old ones to check.
If they were regenerated recently and if that's a new thing, I guess the hash would be different.

**Comment by kassane** [comment]
Same problem here.

Maybe related:
- https://github.com/ziglang/zig/issues/17064

**Comment by leecannon** [comment]
After deleting the global cache I hit this as well, issue occurs with both master and 0.11.0.

Does this mean the upstream content has changed?

If the dependencies are cached the build will continue to work which is why the CI is still green.

The hashes required now are:
```diff
--- a/build.zig.zon
+++ b/build.zig.zon
@@ -5,15 +5,15 @@
     .dependencies = .{
         .known_folders = .{
             .url = "https://github.com/ziglibs/known-folders/archive/fa75e1bc672952efa0cf06160bbd942b47f6d59b.tar.gz",
-            .hash = "122048992ca58a78318b6eba4f65c692564be5af3b30fbef50cd4abeda981b2e7fa5",
+            .hash = "1220206c698a1890d742a8b98acb16db99275d16f2e7fe2046c3d8f2249ed267ca71",
         },
         .diffz = .{
             .url = "https://github.com/ziglibs/diffz/archive/90353d401c59e2ca5ed0abe5444c29ad3d7489aa.tar.gz",
-            .hash = "122089a8247a693cad53beb161bde6c30f71376cd4298798d45b32740c3581405864",
+            .hash = "122090a5106337f6c86efeaecfedf14e1cd8f9944e8ba9c0c7fd9a9c54d860100ff7",
         },
         .binned_allocator = .{
             .url = "https://gist.github.com/antlilja/8372900fcc09e38d7b0b6bbaddad3904/archive/6c3321e0969ff2463f8335da5601986cf2108690.tar.gz",
-            .hash = "1220363c7e27b2d3f39de6ff6e90f9537a0634199860fea237a55ddb1e1717f5d6a5",
+            .hash = "122031b87e4aedc69cbc600a29aaf79317fa84d7fc4f9e619d947de121aaf637bb2a",
         },
     },
 }
```

**Comment by iacore** [comment]
maybe the way Github creates .tar.gz file is unstable

**Comment by leecannon** [comment]
I am no longer experiencing this issue on linux 6.5.3 (arch).

**Comment by jcalabro** [comment]
Hey there, I'm getting this error as well when I try to build from source. I'm running Fedora 38, and here's some more info (original issue here including zls/zig version #1491).

```
$ df -hT | rg '/$'
/dev/nvme0n1p6 btrfs     105G   32G   71G  31% /

$ uname -a
Linux jrazor-linux 6.4.15-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep  7 00:25:01 UTC 2023 x86_64 GNU/Linux
```

And here's the exact error:

```
$ zig build
Fetch Packages [1/3] known_folders... /home/jcalabro/go/src/github.com/jcalabro/zls/build.zig.zon:9:21: error: hash mismatch: expected: 1220bb12c9bfe291eed1afe6a2070c7c39918ab1979f24a281bba39dfb23f5bcd544, found: 1220206c698a1890d742a8b98acb16db99275d16f2e7fe2046c3d8f2249ed267ca71
            .hash = "1220bb12c9bfe291eed1afe6a2070c7c39918ab1979f24a281bba39dfb23f5bcd544",
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by iacore** [comment]
> Hey there, I'm getting this error as well when I try to build from source. I'm running Fedora 38, and here's some more info (original issue here including zls/zig version #1491).
> 
> ```
> $ df -hT | rg '/$'
> /dev/nvme0n1p6 btrfs     105G   32G   71G  31% /
> 
> $ uname -a
> Linux jrazor-linux 6.4.15-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep  7 00:25:01 UTC 2023 x86_64 GNU/Linux
> ```
> 
> And here's the exact error:
> 
> ```
> $ zig build
> Fetch Packages [1/3] known_folders... /home/jcalabro/go/src/github.com/jcalabro/zls/build.zig.zon:9:21: error: hash mismatch: expected: 1220bb12c9bfe291eed1afe6a2070c7c39918ab1979f24a281bba39dfb23f5bcd544, found: 1220206c698a1890d742a8b98acb16db99275d16f2e7fe2046c3d8f2249ed267ca71
>             .hash = "1220bb12c9bfe291eed1afe6a2070c7c39918ab1979f24a281bba39dfb23f5bcd544",
>                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

Upgrade your kernel version.

**Comment by travisstaloch** [comment]
here is the zig issue for this: https://github.com/ziglang/zig/issues/17282#issuecomment-1743586791

**Comment by Techatrix** [comment]
workaround landed in zig: https://github.com/ziglang/zig/issues/17282#issuecomment-1753500991
