### ISSUE TITLE
Add support for addPackagePath in build.zig

### ISSUE THREAD

**Issue by axzn** [zigtools/zls#143]
This is a feature request to add ZLS support for packages defined in `build.zig` though `std.build.LibExeObjStep.addPackagePath()`. A minimal test case for the desired feature would be:

**build.zig**
```zig
pub fn build(b: *@import("std").build.Builder) !void {
    const exe = b.addExecutable("zls-issue", "src/main.zig");
    exe.addPackagePath("package", "package/package.zig");
    exe.install();
}
```

**package/package.zig**
```zig
pub fn packageFunction() void {
    @import("std").debug.print("hi", .{});
}
```

**src/main.zig**
```zig
const package = @import("package");
pub fn main() void {
    package.packageFunction();
}
```

Given the test case above, it would be really nice to have ZLS properly index the `package/package.zig` from `const package = @import("package");` clause in `main.zig`.

*As a side note, thank you for making ZLS, it's an amazing tool!*

**Comment by alexnask** [comment]
Hi, thank for your interest in zls :)  
zls currently has basic package support (it will use all packages defined in a build.zig file for any source file in a subdirectory but not differentiate between different executable/test/lib steps).  
This example works as long as you have a zig (master branch) executable in path or specified in your zls.json configuration.  

Here is a screenshot of exactly this test project with package comppletions in action:  
![image](https://user-images.githubusercontent.com/265903/89124367-20b8d100-d4df-11ea-93c7-849bc344422d.png)

**Comment by axzn** [comment]
Sorry, looks like I must have had old ZLS or Zig installed.
Reinstalled both with master versions from scratch, and it works perfectly now, thanks!

**Comment by GideonUng** [comment]
I did a master build about 2 days ago with a zig build from the same day and this does not seem to work for me.
Has there been a regression or am i missing something?

**Comment by ryuukk** [comment]
it doesn't work for me too

**Comment by Leguu** [comment]
I've copied the example above perfectly, but am not receiving the package autocomplete. Tested with the master releases for both Zig and ZLS. Any help would be appreciated...

**Comment by RUSshy** [comment]
@Leguu can you show yout build.zig?

I had this issue i managed to fix it by fixing the build.zig, it had too many ``addExecutable``

Maybe zls don't handle that properly?

**Comment by alexnask** [comment]
@Leguu Hi, it could be one of a couple of issues.  
Either `zig` is not in PATH (or not found for some reason, e.g. your editor may be overriding the zls process environment and removing PATH) or your build.zig file is incorrect.  
I would try to manually add the `zig_exe_path` option in your `zls.json` configuration and see if that fixes it.
