### ISSUE TITLE
Enum, union and struct fields can't be inferred

### ISSUE THREAD

**Issue by TeamPuzel** [zigtools/zls#1431]
I'm not entirely sure what this zig feature is called exactly but I'm thinking of this
```c
// Full enum
std.Target.Cpu.Arch.wasm32
// Inferred
.wasm32
```
And also inferring structs with `.{}`

This doesn't work with zls making use of libraries harder, but it's most annoying in `build.zig`. That file relies heavily on nesting types multiple times and everything is split into many namespaces within std. I have to first guess then write the entire path to a type to get suggestions, then when I'm done I need to remove the path again, hopefully I don't need to edit it again. It makes a really cool zig feature tedious to use.

For reference a very similar style of inference is implemented in Apple's [sourcekit-lsp](https://github.com/apple/sourcekit-lsp).

**Comment by Techatrix** [comment]
Are you referring to something similar to these issues https://github.com/zigtools/zls/issues/376 https://github.com/zigtools/zls/issues/1188?
Could you give an example in code of what you would expect from ZLS?

**Comment by TeamPuzel** [comment]
Of course, here's an example:
```zig
const exe = b.addExecutable(.{
    .name = "Engine",
    .root_source_file = .{ .path = "src/main.zig" },
    .target = target,
    .optimize = optimize,
});
```
This pattern is the most annoying, far more than enums.

Zig itself can type check this since it can infer the type of the struct passed to addExecutable, however doing so prevents code completion for struct fields, forcing me to specify the exact path to the type to get completion or be able to view its source (since the type is inferred I can't click on it to view the source either)

**Comment by Techatrix** [comment]
ZLS can (but not always) infer the type of a struct init expression (`.{ ... }`) or give completions when initializing an enum.
![Screenshot from 2023-10-16 19-22-18](https://github.com/zigtools/zls/assets/19954306/d4cdb477-273e-40b5-9ebf-78ff981799d1)
![Screenshot from 2023-10-16 19-22-28](https://github.com/zigtools/zls/assets/19954306/d4d656de-b4b5-42ac-8322-0d09881ea855)
![Screenshot from 2023-10-16 19-21-14](https://github.com/zigtools/zls/assets/19954306/eae7357d-8e74-4c3c-b8eb-1978c3150f84)

Is there something that doesn't work or am I misunderstanding your issue?

**Comment by TeamPuzel** [comment]
<img width="497" alt="image" src="https://github.com/zigtools/zls/assets/94306330/bdab2630-2436-48ed-9753-732e4e213e0e">

Weird, this doesn't work for me, and never did.

**Comment by Techatrix** [comment]
What is your ZLS version and do you get completions on anything from the standard library?

**Comment by TeamPuzel** [comment]
Hm, okay, it does work in the latest version of zls. It didn't work back when I opened this issue, so I guess this must have been fixed/implemented since then. Thank you.
