### ISSUE TITLE
Show parameters when calling functions by pointer

### ISSUE THREAD

**Issue by Parzival-3141** [zigtools/zls#1438]
When calling functions by pointer, either as a `fn` or `*const fn`, ZLS won't show the list of parameters while typing or manually toggling.
```zig
const S = struct {
    foo: fn (a: i32, b: i32) i32,
    bar: *const fn (a: i32, b: i32) i32,
};

fn baz(a: i32, b: i32) i32 {
    return a + b;
}

pub fn main() void {
    const s = S{ .foo = baz, .bar = &baz };
    _ = s.foo(1, 2); // won't show parameters
    _ = s.bar(3, 4); // won't show parameters
    _ = s.bar.*(5, 6); // dereferencing bar will show parameters
}
```
Dereferencing makes it work, but this is annoying to do just to see parameters.
<img width="350" alt="Screenshot 2023-09-09 at 4 48 54 PM" src="https://github.com/zigtools/zls/assets/29632054/62c1eb62-06e1-42d5-b266-c16b1e110d6a">

Ideally this would work for all cases.

**Comment by Techatrix** [comment]
does #1541 resolve your issue?

**Comment by Parzival-3141** [comment]
Yes, thank you!
