### ISSUE TITLE
zls install instruction for neovim should no longer recommend nvim-lua/completion-nvim

### ISSUE THREAD

**Issue by bauripalash** [zigtools/zls#1456]
The Neovim plugin <https://github.com/nvim-lua/completion-nvim> has been archived and is no longer maintained. 
The Author and the official docs of neovim `lsp-config`[^1] recommends <https://github.com/hrsh7th/nvim-cmp/>.
Please update the site.

[^1]: https://github.com/neovim/nvim-lspconfig/wiki/Autocompletion

**Comment by Techatrix** [comment]
I have updated the [Installation Guide](https://github.com/zigtools/zls/wiki/Installation#nvim-lspconfig) for `nvim-lspconfig`. Instead of suggestion completion-nvim it instead directs to https://github.com/neovim/nvim-lspconfig for any non ZLS specific configuration like autocompletion.
