### ISSUE TITLE
function calls error in ~/.cache/zls/build_runner.zig

### ISSUE THREAD

**Issue by yuchunzhou** [zigtools/zls#1459]
### Zig Version

0.12.0-dev.494+a8d2ed806

### Zig Language Server Version

0.11.0

### Steps to Reproduce

the function calls code:
![截图 2023-09-23 20-43-54](https://github.com/zigtools/zls/assets/109280366/c27d5c95-c4b1-4c3e-8179-6db91701595c)
the function definition:
![截图 2023-09-23 20-44-03](https://github.com/zigtools/zls/assets/109280366/e0f5c5d1-0167-4d4e-ac19-a9fb25b48db8)
                                                                                                                                                                               

### Expected Behavior

the available_deps argument should be passed

### Actual Behavior

the available_deps argument is not passed

**Comment by yuchunzhou** [comment]
I don't know where the `~/.cache/zls/build_runner.zig` is generated, so i just post the last file.

**Comment by Techatrix** [comment]
ZLS 0.11.0 is only compatible with zig 0.11.0. Either update ZLS to master or use zig 0.11.0.
this change has been made in f02b3fa7a735c974f67c3a939927c079b1c7d161

**Comment by yuchunzhou** [comment]
> ZLS 0.11.0 is only compatible with zig 0.11.0. Either update ZLS to master or use zig 0.11.0. this change has been made in [f02b3fa](https://github.com/zigtools/zls/commit/f02b3fa7a735c974f67c3a939927c079b1c7d161)

Ok, i get it, thanks.
