### ISSUE TITLE
Granular builds for specific zig versions

### ISSUE THREAD

**Issue by menduz** [zigtools/zls#1472]
Hi friends, thanks for building this language server!

### Context and reach

As most zig developers, my workflow is almost always on the bleeding edge of the newest releases. I often take one day every two weeks to update all projects at once to the latest releases. Including zls. But since it is impossible to do all updates at once, I work with [devcontainers](https://code.visualstudio.com/docs/devcontainers/containers) to have granular versions per project.

The solution works perfectly when there are no breaking changes between the zig version of the container and zls, but when there is (and this happens a lot) I can only download the latest build for zls, which usually only works with the latest zig, and that may not be the case for all of my projects.

### Solution space exploration

1. Since builds are being built and uploaded using a specific zig version, I was thinking that maybe there can be one extra alias/indirection/redirection to download older versions by zig version. In that case, I would be able to change my scripts like this:  
   ```diff
   -wget -c https://zig.pm/zls/downloads/$(arch)-linux/bin/zls -O /usr/local/bin/zls
   +wget -c https://zig.pm/zls/downloads/$(arch)-linux-0.12.0-dev.587+eb072fa52/bin/zls -O /usr/local/bin/zls
   ```
1. Maybe there is a public .json somewhere with this exact information that I'm not able to find.
1. Any other ideas?

**Comment by Techatrix** [comment]
@SuperAuguste did some great work on our CI and we can now provide download URLs to non-master builds.
All metadata is about builds in collected into a single [index.json](https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/index.json) which should hopefully provide you with the necessary information.

download URLs would resolve like this:
`https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/<ZLS version>/<target>/zls[.exe]`
example:
`https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/0.12.0-dev.111+ebbae55/x86_64-linux/zls`

**Comment by menduz** [comment]
Oh that's amazing!

It seems like artifacts are being uploaded correctly but the index.json itself is outdated

**Comment by SuperAuguste** [comment]
Afaik it actually is up to date (ctrl+f "c9d99fcacb8b9a83b630397ed719ee83cc725031") - issue is red commits due to https://github.com/ziglang/zig/issues/17477.
