### ISSUE TITLE
Unwanted Buffer on save in Sublime Text

### ISSUE THREAD

**Issue by rawhuul** [zigtools/zls#1473]
### Zig Version

0.12.0-dev.596+2adb932ad

### Zig Language Server Version

0.10.0-dev.364+7ef2244

### Steps to Reproduce

- Open a `*.zig` source file in Sublime Text and save it

### Expected Behavior

The buffer is not expected on save, it must only appear on build or test commands

### Actual Behavior

![image](https://github.com/zigtools/zls/assets/84739019/083efca9-88b8-4221-9c76-174a92f8f4e1)

Currently, the default behaviour on save pops up this unwanted buffer which shows error if any in source file. (IDK whether it is sublime problem or zls problem but I never had this problem with any other language using LSP in Sublime Text)

```bash
~\tests\pop via ↯ v0.12.0-dev.596+2adb932ad ❯ subl --version
Sublime Text Build 4152
```

**Comment by Techatrix** [comment]
I recently updated the sublime text [installation instructions](https://github.com/zigtools/zls/wiki/Installation#sublime-text-4) because I was already aware of this issue. Could follow the given instructions and report back if this resolves your issue?

And also, your reported ZLS version appears to be very outdated, I would suggest to update to the latest master build of ZLS.

**Comment by rawhuul** [comment]
I am still getting same results after changes and I even updated to the latest zls.

ZLS version:
```bash
~\tests\pup via ↯ v0.12.0-dev.596+2adb932ad took 6s ❯ zls.exe --version
0.12.0-dev.100+155293e
```

My LSP config:
```json
{
  "lsp_format_on_save": true,
  "completion_insert_mode": "replace",
  "show_inlay_hints": true,
  "lsp_code_actions_on_save": {
      "source.fixAll": true,
  },
  "semantic_highlighting": true,
	"clients": {
    "zig": {
      "command": ["zls"],
      "enabled": true,
      "selector": "source.zig"
    }
  }
}
```

Screenshot:
![image](https://github.com/zigtools/zls/assets/84739019/899df5dc-66e7-461b-b5dc-cb4a04e7be3c)

**Comment by rawhuul** [comment]
I even tried with this config, but no success.

```json
// Settings in here override those in "LSP/LSP.sublime-settings"
{
  "show_diagnostics_panel_on_save": 0,
  "diagnostics_panel_include_severity_level": 1,
  "lsp_format_on_save": true,
  "completion_insert_mode": "replace",
  "show_inlay_hints": true,
  "lsp_code_actions_on_save": {
      "source.fixAll": true,
  },
  "log_server": [
    // "panel",
    "remote",
  ],
  "semantic_highlighting": true,
	"clients": {
    "zig": {
      "command": ["zls"],
      "enabled": true,
      "selector": "source.zig"
    }
  }
}
```

**Comment by Techatrix** [comment]
did you also edit Zig.sublime-settings?

**Comment by rawhuul** [comment]
Thanks changing zig package settings fixed it!!
