### ISSUE TITLE
Feature Request: Add auto semicolon completion

### ISSUE THREAD

**Issue by Ulrich-Tonmoy** [zigtools/zls#1475]
Since zls already auto format the unused variable and for semicolon it exactly gives the correct message in which column semicolon is missing so auto completing this would be a better experience as i am a JS dev so most of the time i forgot to add semicolon and the prettier formatter auto complete that. I guess it would be a great feature.

and

instead of this
```zig
const verices = [_]f32{
        -0.5, -0.5, 0,
        0.5,  -0.5, 0,
        0,    0.5,  0,
    };
```

this would be better
```zig
const verices = [_]f32{
        -0.5, -0.5, 0,
         0.5, -0.5, 0,
         0,    0.5, 0,
    };
```

**Comment by InKryption** [comment]
zls just uses zig fmt, it doesn't control formatting, so the second idea isn't relevant here

**Comment by SuperAuguste** [comment]
It would be doable using TextEdits like we do for autofix, though. I can try hacking this right now if you'd like to see how the UX feels - I have a suspicious it'll be pretty bad but you never know :)

**Comment by SuperAuguste** [comment]
@Ulrich-Tonmoy please let me know if [the linked PR](https://github.com/zigtools/zls/pull/1476) is to your liking. You can check out the branch (`auguste/add-semicolon-autoinsert`), then build ZLS locally and point your editor to `zls_repo_path/zig-out/bin/zls` and then mess around with it :)

**Comment by Ulrich-Tonmoy** [comment]
> zls just uses zig fmt, it doesn't control formatting, so the second idea isn't relevant here

i guess then i will just have to add +before these 😂

**Comment by Techatrix** [comment]
FYI: Zig has an open proposal for changes to alignment in zig fmt https://github.com/ziglang/zig/issues/17145
