### ISSUE TITLE
DidChangeTextDocument wrong text update when multiple changes are sent at once

### ISSUE THREAD

**Issue by temhelk** [zigtools/zls#1477]
### Zig Version

0.12.0-dev.596+2adb932ad

### Zig Language Server Version

7d6da02a63ec72b29387b16d4e80a22455b9a513

### Steps to Reproduce

I want to say sorry if I got something wrong here, in advance, kind of new to this.
I'm using Neovim - e46f5aab89 commit.

When I'm typing text quickly zls messes up the order of some characters and then displays incorrect diagnostics.
Restart of the server removes wrong diagnostics.

I tried logging the messages sent to zls, and it appears that it happens every time the DidChangeTextDocument message  contains multiple changes, and all these changes are perceived in reverse by the server.

Here is the example of that:
![image](https://github.com/zigtools/zls/assets/77777950/6e9b2999-c564-4f65-9a61-3231c63dec79)
I typed 'qwer', and the server thinks I typed 'qrew'.

The message in this case looks like that:
```json
{
  "jsonrpc": "2.0",
  "method": "textDocument\\/didChange",
  "params": {
    "contentChanges": [
      {
        "text": "w",
        "rangeLength": 0,
        "range": {
          "end": {
            "line": 7,
            "character": 5
          },
          "start": {
            "line": 7,
            "character": 5
          }
        }
      },
      {
        "text": "e",
        "rangeLength": 0,
        "range": {
          "end": {
            "line": 7,
            "character": 6
          },
          "start": {
            "line": 7,
            "character": 6
          }
        }
      },
      {
        "text": "r",
        "rangeLength": 0,
        "range": {
          "end": {
            "line": 7,
            "character": 7
          },
          "start": {
            "line": 7,
            "character": 7
          }
        }
      }
    ],
    "textDocument": {
      "uri": "file:\\/\\/\\/home\\/temhelk\\/Temp\\/zig\\/repro\\/src\\/main.zig",
      "version": 198
    }
  }
}
```

I tried debugging the issue a little bit, and it looks like the problem is located around here: https://github.com/zigtools/zls/blob/7d6da02a63ec72b29387b16d4e80a22455b9a513/src/diff.zig#L101

The ```changes``` contains changes in correct order, but then they get written in a way that they get reversed, here's a screenshot of how it happens over time:
![image](https://github.com/zigtools/zls/assets/77777950/a214ff94-3e23-4e99-9f30-699de6433995)

So it looks like that's the issue on zls side?

### Expected Behavior

The server should interpret changes correctly, in this case, it should not give any diagnostics.

### Actual Behavior

The server interprets changes in a wrong way, which results in it thinking that I wrote "qrew" instead of "qwer".

**Comment by Techatrix** [comment]
does #1478 fix  your issue?

**Comment by temhelk** [comment]
Yes, I think this issue is solved with that change.
