### ISSUE TITLE
many pointer completions

### ISSUE THREAD

**Issue by travisstaloch** [zigtools/zls#1483]
It seems like zls hasn't implemented completions for multipointer indexing.

```zig
const T = struct { foo: u8 };
const t_slice: []T = undefined;
const t_many: [*]T = undefined;
const works = t_slice[0].;
const doesnt_work = t_many[0].;
```

I would like to maybe work on this but I'm not sure where to start.  If anyone wants to coach me a little to help get me started, I will give it a try.  Or if it would just be easier for someone more familiar with the codebase to implement, I will refrain.

**Comment by Techatrix** [comment]
I think I found where the issue may be located:
https://github.com/zigtools/zls/blob/59732390380fdb93d933d6e8aaf8266b0de37411/src/analysis.zig#L757-L765
there is no code here that handles `ptr_type.size == .Many` or `ptr_type.size == .C`.
