### ISSUE TITLE
File for Divorce from Our Bad CI

### ISSUE THREAD

**Issue by SuperAuguste** [zigtools/zls#1487]
I'm sorry honey, it's [just not working out](https://www.youtube.com/watch?v=dQw4w9WgXcQ). Our relationship worked when we were younger, but we're both older now and [we've grown apart](https://www.youtube.com/watch?v=dQw4w9WgXcQ).

Let's just make the CI a bash script or something so we can run it locally and I don't have to force push it every time I want to test a change.

**Comment by Techatrix** [comment]
The CI has been changed to utilize the Zig build system a while ago. `zig build release` and `zig build publish` are your friend. Even locally publishing to the [release-worker](https://github.com/zigtools/release-worker) is possible.
