### ISSUE TITLE
Build Error: Zon Hash Mismatch

### ISSUE THREAD

**Issue by jcalabro** [zigtools/zls#1491]
### Zig Version

0.12.0-dev.696+9a001e1f7

### Zig Language Server Version

bec9b61f52e399827c4829ef325ec4844c0f701f

### Steps to Reproduce

Hey there! I'm getting a build error on Linux w/ latest zig and zls:

```
$ zig build
Fetch Packages [1/3] known_folders... /home/jcalabro/go/src/github.com/jcalabro/zls/build.zig.zon:9:21: error: hash mismatch: expected: 1220bb12c9bfe291eed1afe6a2070c7c39918ab1979f24a281bba39dfb23f5bcd544, found: 1220206c698a1890d742a8b98acb16db99275d16f2e7fe2046c3d8f2249ed267ca71
            .hash = "1220bb12c9bfe291eed1afe6a2070c7c39918ab1979f24a281bba39dfb23f5bcd544",
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected Behavior

Build zls successfully using the [install instructions](https://github.com/zigtools/zls#installation)

### Actual Behavior

Build fails with the error above

**Comment by nullptrdevs** [comment]
Hi, would you happen to be using [btrfs](https://github.com/zigtools/zls/issues/1428) ?

**Comment by jcalabro** [comment]
Indeed I am! Sorry, I missed that other issue. Closing this as a duplicate and will comment on the other one. Thanks!
