### ISSUE TITLE
resolution of return type of generic function wrong when signature includes anytype

### ISSUE THREAD

**Issue by nektro** [zigtools/zls#1494]
### Zig Version

0.11.0

### Zig Language Server Version

0.12.0-dev.33+fb5bfe2

### Steps to Reproduce

![image](https://github.com/zigtools/zls/assets/5464072/29393d73-43cf-43aa-afc6-4a5d870172ec)

### Expected Behavior

`x` should resolve to `T`/`u8`, as it does when you remove the `reader: anytype` parameter.

### Actual Behavior

instead `x` resolves to being a `type`. bug persists whether `anytype` param is on either side of `comptime T` param.

speaking with techatrix, this reproduces on zls master as well

**Comment by nektro** [comment]
code from the screenshot

```zig
test {
    const x = try readType(null, u8);
    _ = x;
}

pub fn readType(comptime T: type, reader: anytype) !T {
    _ = reader;
}
```

**Comment by Techatrix** [comment]
> code from the screenshot

The order `T` and `reader` has changed here. pretty sure this was unintentional, right?
