### ISSUE TITLE
zls/build.zig.zon:2:2: error: missing top-level 'paths' field .{

### ISSUE THREAD

**Issue by westernwontons** [zigtools/zls#1509]
### Zig Version

0.12.0-dev.877+2ca7cc46c

### Zig Language Server Version

c9d99fcacb8b9a83b630397ed719ee83cc725031

### Steps to Reproduce

Clone zls and run `zig build -Doptimize=ReleaseSafe`

### Expected Behavior

ZLS builds successfully

### Actual Behavior

Greeted by an error message saying:
```bash
zls/build.zig.zon:2:2: error: missing top-level 'paths' field
.{
```

**Comment by westernwontons** [comment]
Fixed it by adding:
```bash
.paths = .{""},
```

**Comment by SuperAuguste** [comment]
Yes
