### ISSUE TITLE
ZLS Build Failing on Zig master.

### ISSUE THREAD

**Issue by truemedian** [zigtools/zls#151]
Some commit to zig's master branch between `b0846b6ec` and `6bbb168f6` is causing zls's build to emit a TODO.

```
Semantic Analysis [797/1616] TODO buf_write_value_bytes maybe type
```

**Comment by data-man** [comment]
Not confirmed for Zig 0.6.0+243b5c7a8 (Linux).

**Comment by SuperAuguste** [comment]
I couldn't confirm this on 0.6.0+84d50c892 (Windows).

**Comment by truemedian** [comment]
I updated just now and it appears to work again, not exactly sure what happened.
