### ISSUE TITLE
Missing label detail for members with a default value

### ISSUE THREAD

**Issue by ryuukk** [zigtools/zls#1527]
It currently is broken:

![image](https://github.com/zigtools/zls/assets/44361234/2f56009e-a659-4893-ab53-579c2b7b5c89)

**Comment by Techatrix** [comment]
Could you explain your issue in more detail?

**Comment by Techatrix** [comment]
Labels details have been reworked in #1746 and #1763. @ryuukk do they now display as you would expect?

**Comment by Techatrix** [comment]
no response so I am going to close this issue. AFAICR this has been fixed by #1763.
