### ISSUE TITLE
Folding struct fail

### ISSUE THREAD

**Issue by iacore** [zigtools/zls#1528]
### Zig Version

0.11.0

### Zig Language Server Version

1a282b3

### Steps to Reproduce

Try to fold `SomeStruct` in vscode

```zig
pub const SomeStruct = struct {
    a: void, //
    b: void, //

    pub fn deinit() void {}

    // comment here
};
```

### Expected Behavior

The whole struct should collapse into one line.

### Actual Behavior

![image](https://github.com/zigtools/zls/assets/74560659/81d5b66d-b49c-485e-b083-64f54f4b1585)

**Comment by Techatrix** [comment]
this has been fixed in master by 27562655530923b178f37664c05ab15a11c26645
