### ISSUE TITLE
download packet timeout

### ISSUE THREAD

**Issue by zhang-chuanfeng** [zigtools/zls#1529]
## Remember to search before filing a new report
Fetch Packages [4/3] /root/code/zls/build.zig.zon:17:20: error: unable to connect to server: ConnectionTimedOut

.url = "https://gist.github.com/antlilja/8372900fcc09e38d7b0b6bbaddad3904/archive/6c3321e0969ff2463f8335da5601986cf2108690.tar.gz"

**Comment by zhang-chuanfeng** [comment]
wget can work

**Comment by zhang-chuanfeng** [comment]
➜  zls git:(master) ✗ zig env
{
 "zig_exe": "/snap/zig/9141/zig",
 "lib_dir": "/snap/zig/9141/lib",
 "std_dir": "/snap/zig/9141/lib/std",
 "global_cache_dir": "/root/.cache/zig",
 "version": "0.12.0-dev.926+3be8490d8",
 "target": "x86_64-linux.3.16...5.10.81-gnu.2.19"
}

**Comment by Techatrix** [comment]
This appears to be an issue with zig itself. https://github.com/ziglang/zig/pull/17473
