### ISSUE TITLE
Crashes on writing `callconv(.Stdcall)` in a function definition.

### ISSUE THREAD

**Issue by fivemoreminix** [zigtools/zls#153]
This happened while I was adding the WINAPI function
```rs
pub extern "kernel32" fn SetConsoleMode(hConsoleHandle: windows.HANDLE, dwMode: windows.DWORD) callconv(.Stdcall) windows.BOOL;
```
To my code, and I was just beginning to write .Stdcall, before I had written any function parameters or the return type.

ZLS was being used with VSCode, and the editor told me ZLS has crashed 3+ times within the same minute.

**Comment by alexnask** [comment]
Thanks for reporting this, I will take a look at it soon
