### ISSUE TITLE
 Your Zig version v0.11.0 does not meet the minimum build requirement of v0.12.0-dev.1125+63f9af87d

### ISSUE THREAD

**Issue by AngelZC790347** [zigtools/zls#1542]
## Remember to search before filing a new report
When i tried to build de zls it have this resport .
``` Your Zig version v0.11.0 does not meet the minimum build requirement of v0.12.0-dev.1125+63f9af87d.```
I thougth that is a dev version but i use 0.11.0.

**Comment by SuperAuguste** [comment]
You must be using the master version of Zig to compile the master version of ZLS :)

You can either install it from https://ziglang.org/download/ or some other tool like zigup, or build Zig yourself.
