### ISSUE TITLE
Unused variables need two saves to get formatted properly

### ISSUE THREAD

**Issue by TheFunctionalGuy** [zigtools/zls#1543]
### Zig Version

0.12.0-dev.1200+5f92b070b

### Zig Language Server Version

0.12.0-dev.185+645f728

### Steps to Reproduce

1. Implement this kind of code:
```rust
pub fn format(self: Self, comptime fmt: []const u8, options: std.fmt.FormatOptions, writer: anytype) !void {}
```
2. Press save so formatting kicks in

_Note:_ I would kindly provide more information when you need. Just tell me whether you need it.

### Expected Behavior

Getting this code after **ONE** save:
```rust
pub fn format(self: Self, comptime fmt: []const u8, options: std.fmt.FormatOptions, writer: anytype) !void {
    _ = writer;
    _ = options;
    _ = fmt;
    _ = self;
}
```

### Actual Behavior

Getting the following code after the **first** save:
```rust
pub fn format(self: Self, comptime fmt: []const u8, options: std.fmt.FormatOptions, writer: anytype) !void {
    _ = writer;
    _ = options;
    _ = fmt;
    _ = self;}
```
And after a **second** save:
```rust
pub fn format(self: Self, comptime fmt: []const u8, options: std.fmt.FormatOptions, writer: anytype) !void {
    _ = writer;
    _ = options;
    _ = fmt;
    _ = self;
}
```

**Comment by Koranir** [comment]
Relevant: #1490
