### ISSUE TITLE
ExecError -> RunError in zig master 6bf554f9a 

### ISSUE THREAD

**Issue by andreakarasho** [zigtools/zls#1545]
As you can see here:
`Compile.zig`
https://github.com/ziglang/zig/commit/fd2239bde9e2051a32fb25c50c732a40d4afccd0#diff-2629982d68fe3505606df31ea4696b5c7d674c251811cebc9cd3766aa1895d45

the field name has been changed

https://github.com/zigtools/zls/blob/ece79a6288425c08da0660a8d74fb23e24ce52ef/src/build_runner/master.zig#L485

**Comment by Techatrix** [comment]
fixed by https://github.com/zigtools/zls/pull/1544

**Comment by Techatrix** [comment]
not fixed by https://github.com/zigtools/zls/pull/1544
