### ISSUE TITLE
proposal: struct hovers should show entire struct, minus functions

### ISSUE THREAD

**Issue by slimsag** [zigtools/zls#1568]
Related to https://github.com/zigtools/zls/issues/1567 and maybe #1338

Today when hovering over a struct type you get a rather useless:

<img width="905" alt="image" src="https://github.com/zigtools/zls/assets/3173176/c456c361-ae81-4f82-9a88-5c6261ed1dd3">

It would be nice if after the documentation (if any), the actual code snippet for the struct with any `fn` redacted is shown. e.g. the full hover could be:

> const StaticLibraryOptions = struct
>
> Documentation text if any would go here.
>
> ```
> pub const StaticLibraryOptions = struct {
>     name: []const u8,
>     root_source_file: ?LazyPath = null,
>     target: CrossTarget,
>     optimize: std.builtin.OptimizeMode,
>     version: ?std.SemanticVersion = null,
>     max_rss: usize = 0,
>     link_libc: ?bool = null,
>     single_threaded: ?bool = null,
>     use_llvm: ?bool = null,
>     use_lld: ?bool = null,
>     zig_lib_dir: ?LazyPath = null,
>     main_mod_path: ?LazyPath = null,
> 
>     /// Deprecated; use `main_mod_path`.
>     main_pkg_path: ?LazyPath = null,
> };
> ```
> ([type](#))

**Comment by nullptrdevs** [comment]
Yes, I was very [fond](https://github.com/zigtools/zls/issues/1301) of this feature and would like to see it come back or at least as an option.

The original motivation as stated in that issue was that editors place doc comments below all that info, but we can include those at top.

Let me know, Team !

<details>
<summary>until then I'll stash this here</summary>

```diff
diff --git a/src/analysis.zig b/src/analysis.zig
index 7151384..1db465d 100644
--- a/src/analysis.zig
+++ b/src/analysis.zig
@@ -296,6 +296,29 @@ pub fn getVariableSignature(allocator: std.mem.Allocator, tree: Ast, var_decl: A
             offset += 1;
         }
 
+        if (container_decl.ast.members.len != 0) container_fields: {
+            var fields = try std.ArrayListUnmanaged(Ast.full.ContainerField).initCapacity(allocator, container_decl.ast.members.len);
+            for (container_decl.ast.members) |member| {
+                const field = Ast.fullContainerField(tree, member) orelse continue;
+                fields.appendAssumeCapacity(field);
+            }
+            if (fields.items.len == 0) break :container_fields;
+            var desc = std.ArrayListUnmanaged(u8){};
+            try desc.appendSlice(allocator, offsets.tokensToSlice(tree, start_token, token + offset)); // ie `const T = type`
+            try desc.appendSlice(allocator, " {\n    ");
+            // Decls aren't allowed between fields => get a slice of first_field.ast.main_token .. last_field.ast.xxx_token
+            const first_field = fields.items[0];
+            const last_field = fields.items[fields.items.len - 1];
+            const desc_end_token = last_field_last_token: {
+                if (last_field.ast.value_expr == 0 and last_field.ast.type_expr == 0 and last_field.ast.align_expr == 0) break :last_field_last_token last_field.ast.main_token;
+                const end_node = if (last_field.ast.value_expr != 0) last_field.ast.value_expr else last_field.ast.type_expr;
+                break :last_field_last_token ast.lastToken(tree, end_node);
+            };
+            try desc.appendSlice(allocator, offsets.tokensToSlice(tree, first_field.ast.main_token, desc_end_token));
+            try desc.appendSlice(allocator, "\n}");
+            return desc.toOwnedSlice(allocator);
+        }
+
         break :blk token + offset;
     };
     return offsets.tokensToSlice(tree, start_token, end_token);
```

</details>

**Comment by WillLillis** [comment]
> Yes, I was very [fond](https://github.com/zigtools/zls/issues/1301) of this feature and would like to see it come back or at least as an option.
> 
> The original motivation as stated in that issue was that editors place doc comments below all that info, but we can include those at top.
> 
> Let me know, Team !
> 
> until then I'll stash this here
> ```diff
> diff --git a/src/analysis.zig b/src/analysis.zig
> index 7151384..1db465d 100644
> --- a/src/analysis.zig
> +++ b/src/analysis.zig
> @@ -296,6 +296,29 @@ pub fn getVariableSignature(allocator: std.mem.Allocator, tree: Ast, var_decl: A
>              offset += 1;
>          }
>  
> +        if (container_decl.ast.members.len != 0) container_fields: {
> +            var fields = try std.ArrayListUnmanaged(Ast.full.ContainerField).initCapacity(allocator, container_decl.ast.members.len);
> +            for (container_decl.ast.members) |member| {
> +                const field = Ast.fullContainerField(tree, member) orelse continue;
> +                fields.appendAssumeCapacity(field);
> +            }
> +            if (fields.items.len == 0) break :container_fields;
> +            var desc = std.ArrayListUnmanaged(u8){};
> +            try desc.appendSlice(allocator, offsets.tokensToSlice(tree, start_token, token + offset)); // ie `const T = type`
> +            try desc.appendSlice(allocator, " {\n    ");
> +            // Decls aren't allowed between fields => get a slice of first_field.ast.main_token .. last_field.ast.xxx_token
> +            const first_field = fields.items[0];
> +            const last_field = fields.items[fields.items.len - 1];
> +            const desc_end_token = last_field_last_token: {
> +                if (last_field.ast.value_expr == 0 and last_field.ast.type_expr == 0 and last_field.ast.align_expr == 0) break :last_field_last_token last_field.ast.main_token;
> +                const end_node = if (last_field.ast.value_expr != 0) last_field.ast.value_expr else last_field.ast.type_expr;
> +                break :last_field_last_token ast.lastToken(tree, end_node);
> +            };
> +            try desc.appendSlice(allocator, offsets.tokensToSlice(tree, first_field.ast.main_token, desc_end_token));
> +            try desc.appendSlice(allocator, "\n}");
> +            return desc.toOwnedSlice(allocator);
> +        }
> +
>          break :blk token + offset;
>      };
>      return offsets.tokensToSlice(tree, start_token, end_token);
> ```

Just saw this today and thought it was really cool! Would it be possible for this to be added soon? I played with it a bit and noticed that in some cases the indention was inconsistent, e.g.

![image](https://github.com/zigtools/zls/assets/87077023/d4fdfda8-ab94-4e56-a42f-3f7ddb4076e4)

but could be simplified (unless I'm missing some edge cases, would be happy to look into this more) and made consistent with the following code:

```zig
if (container_decl.ast.members.len != 0) container_fields: {
    var fields = try std.ArrayListUnmanaged(Ast.full.ContainerField).initCapacity(allocator, container_decl.ast.members.len);
    for (container_decl.ast.members) |member| {
        const field = Ast.fullContainerField(tree, member) orelse continue;
        fields.appendAssumeCapacity(field);
    }
    if (fields.items.len == 0) break :container_fields;
    var desc = std.ArrayListUnmanaged(u8){};

    const last_field = fields.items[fields.items.len - 1];
    const desc_end_token = last_field_last_token: {
        if (last_field.ast.value_expr == 0 and last_field.ast.type_expr == 0 and last_field.ast.align_expr == 0) break :last_field_last_token last_field.ast.main_token;
        const end_node = if (last_field.ast.value_expr != 0) last_field.ast.value_expr else last_field.ast.type_expr;
        break :last_field_last_token ast.lastToken(tree, end_node);
    };
    try desc.appendSlice(allocator, offsets.tokensToSlice(tree, start_token, desc_end_token));
    try desc.appendSlice(allocator, "\n}");
    return desc.toOwnedSlice(allocator);
}
```
Screenshot after:

![image](https://github.com/zigtools/zls/assets/87077023/45f7985c-7909-44f2-9912-2488f1b55f71)

Something I did notice with both approaches is that any extra indentation in the source code also got added to the hover window's contents. I imagine this could be removed with some postprocessing (maybe utilizing some of [`zig fmt`'s functionality](https://github.com/ziglang/zig/blob/0884a434117dee3458eea8890b2e47e432844ac3/lib/std/zig/render.zig#L2276)?), but probably isn't too big of a deal. Would it be helpful if I opened a PR with these changes to get the ball rolling? :)

**Comment by llogick** [comment]
@WillLillis

> I played with it a bit and noticed that in some cases the indention was inconsistent, e.g.

I admit that I was aware of the indentation issue, but wasn't gonna bother with it until this was sorta/kinda approved.

The idea I had is to have the logic in a separate fn,
- iterate over container members, check if full field
- if `field.ast.type_expr` is a fullContainerDecl => recurse,
  otherwise add it to `desc`
- would need to keep/take an indent depth level

> but could be simplified (unless I'm missing some edge cases, ...

```zig
// just to illustrate the case, not guaranteed to be semantically correct
const S = struct {
	fn foo() void {
		// many lines here
    }

	fld: u8,
};
```


I'd be happy to see a PR.

Cheers

**Comment by WillLillis** [comment]
Was away from my computer for most of the weekend but I was able to work on this a bit. I'm going to spend some more time writing tests and cleaning things up but I should have a PR open soonish :)

```zig
/// just to illustrate the case, not guaranteed to be semantically correct
const S = struct {
	fn foo() void {
		// many lines here
    }

	fld: u8,
};
```

![image](https://github.com/zigtools/zls/assets/87077023/93dfb2b9-6d0b-4962-b98c-450b714c42c7)

```zig
/// Doc comment
const FooEnum = enum {
    foo,
    bar,
    baz,

    const Inner = struct {
        something: bool,
    };
};
```

![image](https://github.com/zigtools/zls/assets/87077023/f3cdddba-c38f-4be6-ae93-1574d80c0b46)
