### ISSUE TITLE
build from source error

### ISSUE THREAD

**Issue by ehrktia** [zigtools/zls#1582]
### Zig Version

0.12.0-dev.1466+dc63426b1

### Zig Language Server Version

7430bb66e67ef5041d2127f557a12305b69f8516

### Steps to Reproduce

**operating system:**

`Linux pop-os 6.5.6-76060506-generic #202310061235~1697396945~22.04~9283e32 SMP PREEMPT_DYNAMIC Sun O x86_64 x86_64 x86_64 GNU/Linux`

**What did i do**

build zig from source as mentioned in readme 
no errors build successful

follow instructions from readme
https://github.com/zigtools/zls#from-source

### Expected Behavior

build zls successfully

### Actual Behavior

```
<@zls>-<⎇ master>-> zig build -Doptimize=ReleaseSafe
zig build-exe zls ReleaseSafe native: error: the following command failed with 4 compilation errors:
/home/karthick/.local/zig/zig build-exe /home/karthick/github.com/zls/src/main.zig -OReleaseSafe --cache-dir /home/karthick/github.com/zls/zig-cache --global-cache-dir /home/karthick/.cache/zig --name zls --mod diffz::/home/karthick/.cache/zig/p/122089a8247a693cad53beb161bde6c30f71376cd4298798d45b32740c3581405864/DiffMatchPatch.zig --mod version_data::/home/karthick/github.com/zls/zig-cache/o/a8910b6ba7c3ddafb9023c52aa2f6e00/version_data_master_19666.zig --mod binned_allocator::/home/karthick/.cache/zig/p/1220363c7e27b2d3f39de6ff6e90f9537a0634199860fea237a55ddb1e1717f5d6a5/binned_allocator.zig --mod known-folders::/home/karthick/.cache/zig/p/1220bb12c9bfe291eed1afe6a2070c7c39918ab1979f24a281bba39dfb23f5bcd544/known-folders.zig --mod build_options::/home/karthick/github.com/zls/zig-cache/c/6c72e8fa098b187cf9cd3d4abe47e5aa/options.zig --deps build_options,known-folders,diffz,binned_allocator,version_data --listen=-
Build Summary: 3/6 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install zls transitive failure
   └─ zig build-exe zls ReleaseSafe native 4 errors
src/ZigCompileServer.zig:68:47: error: no field named 'little' in enum 'builtin.Endian'
        .extra_len = try reader.readInt(u32, .little),
                                             ~^~~~~~
/home/karthick/.local/zig/lib/std/builtin.zig:452:20: note: enum declared here
pub const Endian = enum {
                   ^~~~
referenced by:
    translate: src/translate_c.zig:240:52
    resolveCImport: src/DocumentStore.zig:1335:37
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
src/ZigCompileServer.zig:165:38: error: no field named 'little' in enum 'builtin.Endian'
const need_bswap = native_endian != .little;
                                    ~^~~~~~
/home/karthick/.local/zig/lib/std/builtin.zig:452:20: note: enum declared here
pub const Endian = enum {
                   ^~~~
src/ZigCompileServer.zig:147:45: error: no field named 'little' in enum 'builtin.Endian'
    return std.mem.readInt(u32, bytes_ptr, .little);
                                           ~^~~~~~
/home/karthick/.local/zig/lib/std/builtin.zig:452:20: note: enum declared here
pub const Endian = enum {
                   ^~~~
src/ZigCompileServer.zig:152:50: error: no field named 'little' in enum 'builtin.Endian'
    const int = std.mem.readInt(u32, bytes_ptr, .little);
                                                ~^~~~~~
/home/karthick/.local/zig/lib/std/builtin.zig:452:20: note: enum declared here
pub const Endian = enum {
                   ^~~~
```

**Comment by Techatrix** [comment]
The relevant breaking change that happened in Zig that causes this error: [link](https://github.com/ziglang/zig/commit/725f765c376dda291d3d5afe5446221a97c189f7)

---

I've just checked and I am able to build ZLS with Zig `0.12.0-dev.1468+e9a6197a8`.

Here is how I could explain why this has happened:
- the reported ZLS or Zig commit/version incorrect
- this [check](https://github.com/zigtools/zls/blob/7430bb66e67ef5041d2127f557a12305b69f8516/build.zig#L11-L17) has been removed and the Zig version is actually before `0.12.0-dev.1379+725f765c3`
- You are in fact using a Zig version that is at least `0.12.0-dev.1379+725f765c3` but your Zig standard library is before `0.12.0-dev.1379+725f765c3`.

I think that the last point is the most likely one. Could you post your output of `zig env`?
When I run the following command which explicitly tells Zig to use a old standard library directory, I get the same error message that you have reported. `zig env` should show you if Zig is using the wrong standard library directory.
`/nix/store/7p6ikfg5s7aklc06dhg0714jidn0ymxy-zig-0.12.0-dev.1383+7c5d01b95/bin/zig build --zig-lib-dir /nix/store/kd25pdda5cxr2w7avlar0x9ilrxgnfj2-zig-0.12.0-dev.1245+a07f288eb/lib`

Also, you do not need to build Zig from source to build ZLS from source. an upstream binary is also available [here](https://ziglang.org/download/)

**Comment by ehrktia** [comment]
thanks for swift reply , i had grabbed a copy of pre-built binary was curious to build and see if it works.
let me share the `zig env` as well
