### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by glepnir** [zigtools/zls#159]
Install zig from `brew install zig`. `zig version ` output is 0.6.0
![image](https://user-images.githubusercontent.com/41671631/93581703-1772bd80-f9d4-11ea-9eb7-ebd4d0d46136.png)

**Comment by data-man** [comment]
@glepnir 
README.md says:
> You will need a build of **Zig master** to build zls.

**Comment by glepnir** [comment]
sorry noob.

**Comment by alexnask** [comment]
I understand this is quite confusing, the repo will be stabilized upon zig's 0.7.0 release and a new fork will be used to track zig master :)

**Comment by data-man** [comment]
@alexnask 

https://github.com/zigtools/zls/issues/140#issuecomment-659302481 :smile:
