### ISSUE TITLE
Completing a builtin with a `(` after the identifier adds extra `@`

### ISSUE THREAD

**Issue by Vexu** [zigtools/zls#1592]
### Zig Version

0.12.0-dev.1369+a09ba455c

### Zig Language Server Version

0.12.0-dev.228+aa9fc0c

### Steps to Reproduce

```zig
@int<cursor>()
// Type F and complete @intFromBool
@intF<cursor>()
```

### Expected Behavior

```zig
@intFromBool()
```

### Actual Behavior

```zig
@@intFromBool()
```

**Comment by Techatrix** [comment]
caused by #1346
