### ISSUE TITLE
types of boolean literals are resolved as their literal value instead of `bool`

### ISSUE THREAD

**Issue by xdBronch** [zigtools/zls#1600]
### Zig Version

0.12.0-dev.1591+3fc6a2f11

### Zig Language Server Version

0.12.0-dev.228+aa9fc0c

### Steps to Reproduce

![image](https://github.com/zigtools/zls/assets/51252236/3ea5f1e3-82f6-4467-971b-9c519e37a724)

i believe this is somewhat recent, i dont remember it happening before

### Expected Behavior

both should be resolved as `bool` type

### Actual Behavior

resolved as `true` and `false`

**Comment by Techatrix** [comment]
#1589 attempted to fix this but the issue is slightly more annoying than anticipated.
