### ISSUE TITLE
zls doesn't pass errors from zig translate-c

### ISSUE THREAD

**Issue by ptrcnull** [zigtools/zls#1608]
### Zig Version

0.11.0

### Zig Language Server Version

0.11.0

### Steps to Reproduce

- create a zig file with `@cImport({ @cInclude("non-existent.h") });`
- open it in an editor supporting LSP with zls

### Expected Behavior

ideally, the `@cInclude` with a missing file is marked as an error; at least, the error from zig ( `/home/patrycja/.cache/zls/cimport.h:1:10: 'non-existent.h" file not found` ) printed in the zls logs

### Actual Behavior

the return type of `@cImport` is unknown. the zls log only says "error.Timeout"

**Comment by ptrcnull** [comment]
as a side note - normally, this isn't an issue, because zig would yell at the user at build that the header doesn't exist; however, in my case, zig ( i assume ) picks up the library via pkgconfig and sets the include path accordingly, but that isn't reflected in zls ( may that also be a separate issue? )

**Comment by Techatrix** [comment]
> zig ( i assume ) picks up the library via pkgconfig and sets the include path accordingly, but that isn't reflected in zls ( may that also be a separate issue? )

Are you saying that Zig was able to find your header file but ZLS wasn't? If that is that case, this should be investigated as a separate issue. Be sure to check against ZLS master and include information like your `build.zig` and entire ZLS log output.

**Comment by Techatrix** [comment]
This issue has been fixed in ZLS master. See https://github.com/zigtools/zls/pull/1463 and https://github.com/ziglang/zig/pull/17272.
This means that you would need to update ZLS and Zig.
