### ISSUE TITLE
completions for anonymous struct parameters only happen if the struct type and function are defined in a different file

### ISSUE THREAD

**Issue by xdBronch** [zigtools/zls#1617]
### Zig Version

0.12.0-dev.1680+be6f76655

### Zig Language Server Version

0.12.0-dev.248+62f17ab

### Steps to Reproduce

```zig
// main.zig
pub fn main() void {
    foo(.{<cursor>});
}

const Config = struct {
    conf: void,
};

fn foo(_: Config) void {}
```
request completions, none appear. move `Config` and `foo` into a separate file
```zig
// import.zig
pub const Config = struct {
    conf: void,
};

pub fn foo(_: Config) void {}
/////////////////////////////
// main.zig
const import = @import("import.zig");

pub fn main() void {
    import.foo(.{<cursor>});
}
```
request completions and they correctly appear

### Expected Behavior

completions should always be given

### Actual Behavior

inconsistent

**Comment by nullptrdevs** [comment]
Parser limitation - try it with #1536 or `1.` instead of just `.`.

It has to do with syntax errors and the type node being after the current node.

**Comment by xdBronch** [comment]
i have another issue to report where completions for configs like this are given instead of for the struct fields in cases where the function returns a type. is this related? i can open a new issue if not

**Comment by nullptrdevs** [comment]
It's the `std.heap.GeneralPurposeAllocator(.{}){.<cursor>}` issue isn't it.. :sweat_smile:
I keep forgetting about it so an issue as a reminder wouldn't be bad.

**Comment by xdBronch** [comment]
yeah thats it lol, will open an issue

**Comment by xdBronch** [comment]
#1618 i also noticed that `@import("std").heap.GeneralPurposeAllocator(.{}){}` doesnt give any completions so i had to split the import into a const, is that the same issue as this?

**Comment by nullptrdevs** [comment]
`collectFieldAccessContainerNodes` expects the first symbol to be something it can look up to determine if it's a `T` or `instance_of_T`
https://github.com/zigtools/zls/blob/71d2c3302acd4df716d39adb5d6797c2075bd946/src/features/completions.zig#L1375-L1382

A `if (field_access_slice[0] == '@') break :blk 1; // assume @import("..").some.Other{.}` could work.
