### ISSUE TITLE
Autofix on mutating constant

### ISSUE THREAD

**Issue by DivergentClouds** [zigtools/zls#1621]
Due to #1607 if you write something like `var foo: usize = 0` and then you run autofix (my autofix runs on save) it will turn into `const foo: usize = 0` and if you mutate it later by adding `foo += 1` for example, you will get an error for attempting to assign to a constant.

**Comment by leecannon** [comment]
I don't think auto `const` -> `var` fits zig.

**Comment by nektro** [comment]
this is zls not zig

but if that's still your opinion, then the var->const autofix shouldn't be in zls either

**Comment by DivergentClouds** [comment]
I think the zls autofix should change how the var to const works then to add a `_ = &foo` instead of making it const.

**Comment by Techatrix** [comment]
fixed by  #1652
