### ISSUE TITLE
ZLS timeout when using (huge?) cimport

### ISSUE THREAD

**Issue by alanoliveira** [zigtools/zls#1635]
### Zig Version

0.12.0-dev.1746+19af8aac8

### Zig Language Server Version

0.12.0-dev.261+f16bfd3

### OS
Windows 10

### Steps to Reproduce

1. Create a new project
2. Add the following import
```
const d3dx9 = @cImport({
    @cInclude("d3dx9.h");
});
```
3. type `d3dx9.`

### Expected Behavior

zls show the d3dx9 components.

### Actual Behavior

- zls process, that usually use less than 15 MB, in 3 seconds jumps to 100MB
- it keep processing using 100% of a cpu core
- after 10~ minutes it dies (or nvim or windows kills it)
  - nvim shows the message `Client 1 quit with exit code 3221225477 and signal 0`

### Additional Details
The `cimport.zig`  with d3dx9.h content generated by zig has more then 7 MB [cimport.zip](https://github.com/zigtools/zls/files/13485429/cimport.zip)
lsp log https://pastebin.com/Mv01eFDe

**Comment by xdBronch** [comment]
i had a similar problem and was told that its perfectly reasonable for zls to process files like this. its large but not absurdly large, theres a file in the zig compiler source thats 40% the size of this and zls has 0 problem with it

**Comment by Techatrix** [comment]
callsite references are going crazy
![Screenshot from 2023-12-01 19-53-50](https://github.com/zigtools/zls/assets/19954306/a2447f46-1d24-4d3d-a694-b387bd693da6)
