### ISSUE TITLE
Zig Language VSCode extension can't find zig or zls in path

### ISSUE THREAD

**Issue by Inalegwu** [zigtools/zls#1639]
### Zig Version

0.11.0

### Zig Language Server Version

0.12.0-dev.110+5973239

### Steps to Reproduce

Install Zig Language VSCode Extension
Reload VSCode Window
Try writing zig

### Expected Behavior

Autocomplete when typing
std.debug.print()

### Actual Behavior

No autocomplete output , but 2 consecutive error messages with "Can't find zig in path" and "Can't find zls in path" notifications
despite them both being set and Helix Editor works fine

**Comment by nullptrdevs** [comment]
Should be filed/transferred to https://github.com/ziglang/vscode-zig

**Comment by silverhairs** [comment]
Had a similar issue; fixed by reinstalling ZLS from the vscode command palette.
![Screenshot 2023-12-13 at 01 42 39](https://github.com/zigtools/zls/assets/43137330/0bd8873d-dce4-47cc-9752-56cd80174bef)

**Comment by jd-apprentice** [comment]
> Had a similar issue; fixed by reinstalling ZLS from the vscode command palette. ![Screenshot 2023-12-13 at 01 42 39](https://private-user-images.githubusercontent.com/43137330/290039680-0bd8873d-dce4-47cc-9752-56cd80174bef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODQ0MjAsIm5iZiI6MTcxMTk4NDEyMCwicGF0aCI6Ii80MzEzNzMzMC8yOTAwMzk2ODAtMGJkODg3M2QtZGNlNC00N2NjLTk3NTItNTZjZDgwMTc0YmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE1MDg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjBlZDU1OWFlMDgxMTRkM2Q4NWI5MWE3MmUwNmM2YzdlY2E1ZjgzMzA5OGFkZGMxN2QxYWZlN2Q3ZTI5NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sI4TeO-Ir3zKLsHQQNJDjDrqjZvAyl3JrmeJTMawquc)

This worked for me, thanks!
