### ISSUE TITLE
Include dirs for `@cInclude`

### ISSUE THREAD

**Issue by bluesillybeard** [zigtools/zls#1660]
I use the `@cImport` and `@cInclude` functions regularily.

For system libraries, ZLS works nicely. However, if the header is elsewhere (like in a local directory) they aren't found and ZLS reports an error.

I think it would be awesome if a solution for this is implemented, like a way for the user to provide a list of include directories.

**Comment by xdBronch** [comment]
if the headers are in an include path thats added to your exe in build.zig ZLS should pick them up, if not then its a bug not a missing feature

**Comment by bluesillybeard** [comment]
So it was a bug then. After building zls from source in order to update, the issue is fixed! :)
