### ISSUE TITLE
namespace with same name as primitive breaks hover events + completion

### ISSUE THREAD

**Issue by nektro** [zigtools/zls#1673]
### Zig Version

0.11.0

### Zig Language Server Version

0.12.0-dev.33+fb5bfe2

### Steps to Reproduce

```zig
const sdv = struct {
    const @"f32" = struct {
        const abc = 43;
    };
};

const x = sdv.@"f32".abc;
```

### Expected Behavior

the latter case in actual should work too

### Actual Behavior

this works great initially as shown:

![image](https://github.com/zigtools/zls/assets/5464072/3da1d244-e9d2-4a9c-b3eb-9fd5ee5e00e5)

however, upon saving `zig fmt` canonicalizes the code and zls is no longer able to resolve properly

![image](https://github.com/zigtools/zls/assets/5464072/84362dee-f9c1-4503-92d3-b3fff88278fd)

**Comment by Techatrix** [comment]
This has been fixed by #1574.
