### ISSUE TITLE
Intellisense for conditionally added modules 

### ISSUE THREAD

**Issue by akhildevelops** [zigtools/zls#1683]
zls doesn't help with intellisense, if a module is conditionally added
```zig
//build.zig

if (on_some_condition){
    // add foo module
    lib.addModule("foo",foo_module);
}

```

**Comment by nullptrdevs** [comment]
If it is a command line specified condition - https://github.com/zigtools/zls#per-build-configuration-options

**Comment by akhildevelops** [comment]
There's no commandline option to refer a module. Looking something like this below to be added into zls.json

|Option| Type| Default value|What it Does|
|-|-|-|-|
|module|?[]const u8|null|Helps zls to refer a module manually|

Ex: `{"module":"cudaz::/home/akhil/practice/cudaz/src/foo.zig"}` in zls.json will make sure zls point to foo.zig file for `@import("foo")`

**Comment by akhildevelops** [comment]
`zls.build.json` worked for me. Thanks for building wonderful language server for zig.
