### ISSUE TITLE
provide completions for creating `std_options`

### ISSUE THREAD

**Issue by xdBronch** [zigtools/zls#1688]
im not sure if this is easily done without cluttering general completions but it would be great if for example this
```zig
const std = @import("std");

pub const std_options = struct {
    pub const enable_se<cursor>
};

pub fn main() !void {}
```
gave a completion for `enable_segfault_handler` (maybe a type hint in the completion too? not sure how thatd work)
can zls detect if its in the root file? thats the only time std_options are valid

**Comment by xdBronch** [comment]
this kinda becomes moot once https://github.com/ziglang/zig/issues/14432 is implemented

**Comment by InKryption** [comment]
> this kinda becomes moot once https://github.com/ziglang/zig/issues/14432 is implemented

That isn't an accepted proposal, so wouldn't be too hasty to rely on it.

**Comment by xdBronch** [comment]
well it's certainly marked as accepted
I'm guessing you're referring to andrews comment about what vexu so I get what you mean. I'd still like this feature, just wanted to point out that it will likely not be needed eventually

**Comment by nektro** [comment]
it's accepted but there's no current accepted way to implement it. there's some showstopping issues with making it a struct instance that make it unlikely to make it in

**Comment by xdBronch** [comment]
its merged now so not really any point to this
