### ISSUE TITLE
zig build fails

### ISSUE THREAD

**Issue by JeromeK13** [zigtools/zls#169]
```
.\src\analysis.zig:918:33: error: enum 'std.zig.tokenizer.Id' has no field named 'Keyword_opaque'
       return self.isContainer(.Keyword_opaque);
```

**Comment by JeromeK13** [comment]
i try to commit a PR to fix that

**Comment by ifreund** [comment]
@JeromeK13 This is likely due to your zig version being too old, the opaque keyword was added fairly recently.

**Comment by JeromeK13** [comment]
ah alright, then I will update my version 👍 Thanks
