### ISSUE TITLE
add config file directory logic

### ISSUE THREAD

**Issue by r4pr0n** [zigtools/zls#17]
I think zls should look for directories like `$XDG_CONFIG_HOME` on posix systems, `%appdata%` on Windows and so on...
Having zls.conf in `/usr/bin` because `zls` is there is really not optimal; e.g. it needs root privileges to change the config on linux systems.

**Comment by SuperAuguste** [comment]
Hi r4pr0n! We were actually planning on implementing this in the near future along with workspace-level configs. We'll solve this issue soon!

**Comment by r4pr0n** [comment]
We at @ziglibs are currently developing [known-folders](https://github.com/ziglibs/known-folders), so that could be used here when it is finished.

**Comment by alexnask** [comment]
Cheers, we will use this for sure :)
