### ISSUE TITLE
Auto-completion and type function and variable not working with a pointer slice indexing

### ISSUE THREAD

**Issue by StringNick** [zigtools/zls#1701]
### Zig Version

0.12.0-dev.2059+42389cb9c

### Zig Language Server Version

0.12.0-dev.352+d29a62e

### Client / Code Editor / Extensions

vscode

### Steps to Reproduce and Observed Behavior

```zig
const Type = struct {
    const Self = @This();

    pub fn init() Self {
        return .{};
    }

    pub fn foo(self: Self) void {
        _ = self; // autofix
        return;
    }
};

pub fn main() void {
    const val = [_]Type{
        Type.init(),
        Type.init(),
    };

    // completion working
    val[0].foo();

    const someVal = val[0..];
    // working
    someVal[0].foo();

    const ptrToSlice = &val;

    // not-working
    ptrToSlice[0].foo();
}
```
Autocompletion, highlighting variable and functions of type working with array, with slice, but with ptr on slice/array its stop working, code is building and working.
For reproducing just hover foo() in three places, or type ptrToSlice[0]. and watch behavior.

### Expected Behavior

Show inline suggestions for type, if its ptr on a slice/array (same behavior as on slice/array)

**Comment by FnControlOption** [comment]
Does the `ptrToSlice` variable show its type when you hover over it?

**Comment by StringNick** [comment]
yes show type as on screen below:
<img width="387" alt="image" src="https://github.com/zigtools/zls/assets/13052752/8e664e36-89fa-4e72-86e1-ac142b1685f0">
hover working:
<img width="387" alt="image" src="https://github.com/zigtools/zls/assets/13052752/2c53c2a7-a4f4-4832-b02b-1981c667deee">
hover not working:
<img width="391" alt="image" src="https://github.com/zigtools/zls/assets/13052752/9397ec06-4ebd-4b65-a988-42f7971e8fec">
