### ISSUE TITLE
cInclude no longer showing added libraries.

### ISSUE THREAD

**Issue by overlandandseas** [zigtools/zls#1704]
### Zig Version

0.12.0-dev.2139+e025ad7b4

### Zig Language Server Version

0.12.0-dev.156+e4593da

### Client / Code Editor / Extensions

helix 23.05 (7f5940be)

### Steps to Reproduce and Observed Behavior

Using raylib, add raylib as a submodule in the root folder of you project.
Adding raylib using the provided build.zig file.
```zig
// build.zig
const raylib_sdk = @import("raylib/src/build.zig");
...
const raylib = raylib_sdk.addRaylib(b, target, optimize, .{});
exe.addIncludePath(.{ .path = "raylib/src" });
exe.linkLibrary(raylib);

b.installArtifact(exe);
```

Attempting to import raylib.h using cInclude
```zig
// src/main.zig
const rl = @cImport({
    @cInclude("raylib."); // <-- "raylib.h" does not get suggested here when typing
});

...

rl.InitWindow( // <- rl.InitWindow does not get suggested here when typing.
```
This was working previously.

![Screenshot 2024-01-12 at 13 30 48](https://github.com/zigtools/zls/assets/660813/dc3786fa-9a69-4a00-9e95-9b192cd6cea8)
When hitting Tab after typing some letters, I noticed the folder that it appears to be searching in is not related to the project.

### Expected Behavior

"raylib.h" should be suggested in the cInclude argument.

`rl.InitWindow` should be a suggestion, goto definition should visit the relevent raylib function. 

### Relevant log output

```shell
OS: macOS 13.6 22G120 arm64 (m1 pro)
```

**Comment by nullptrdevs** [comment]
Could you try that with a more recent version of ZLS? Current one is `0.12.0-dev.356+f726e9e`.

**Comment by hazelnutcloud** [comment]
can confirm facing this issue with the most recent version of ZLS. seems like ZLS only provides completions for header files in /usr/include. If I cp a header file into that directory, it'll also provide completion for it. I don't see a way to configure this behavior.

**Comment by Techatrix** [comment]
no response -> no issue
