### ISSUE TITLE
not compatible with zig 0.11.0

### ISSUE THREAD

**Issue by subh-cs** [zigtools/zls#1739]
### Zig Version

0.11.0

### Zig Language Server Version

N/A

### Steps to Reproduce and Observed Behavior

I'm using ubuntu 22.04 and I downloaded zig from snapstore which installed 0.11.0 LTS version. 
And now I need to install ZLS but when I follow installation guide, it requires latest version. 
```
Your Zig version v0.11.0 does not meet the minimum build requirement of v0.12.0-dev.2138+828d23956
```

### Expected Behavior

1. There should be an installation guide on how to download a specific version of ZLS based on ZIg version.
2. maybe just install ZLS which will take a look at system for existing ZIG version, if ZIG is not installed, it will ask first to install it and then install the specific ZLS accordingly, in this case everything is in abstraction and UX will be awesome.

**Comment by nektro** [comment]
there are in the releases https://github.com/zigtools/zls/releases/tag/0.11.0
