### ISSUE TITLE
Inlay hints are crashing zls non deterministacally

### ISSUE THREAD

**Issue by Deecellar** [zigtools/zls#1789]
### Zig Version

0.12.0-dev.2811+3cafb9655

### Zig Language Server Version

0.12.0-dev.411+1bfb8a0

### Client / Code Editor / Extensions

Visual Studio Code-1.83.1 with the official zig extension

### Steps to Reproduce and Observed Behavior

Access Preferences
Search for Inlay Hints of any kind
Enable them.
Open any Zig file.

Crashes on windows and linux sometimes

### Expected Behavior

To not crash

**Comment by nullptrdevs** [comment]
Get the newest zls, those got ironed out in 54eaba2a7267166c832fd45f82a9aab9ba48642a

**Comment by Techatrix** [comment]
No response. This should have been fixed in 47ddbc3f099147ed489161e9df91595133dd8790 or 54eaba2a7267166c832fd45f82a9aab9ba48642a.
