### ISSUE TITLE
Config autofix doesn't get applied

### ISSUE THREAD

**Issue by jcs090218** [zigtools/zls#1798]
### Zig Version

0.12.0-dev

### Zig Language Server Version

0.11.0

### Client / Code Editor / Extensions

Emacs

### Steps to Reproduce and Observed Behavior

Hi, I am trying to implemented Emacs client for zls in https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-zig.el. I noticed some configurations aren't being respected by the language server, e.g., `zig.zls.enableAutofix`. I cannot reproduce this bug in VSCode; therefore, I was wondering what version is the VSCode using? Is it not `0.11.0`? If this bug has been fixed in the master branch, can someone released a new version (maybe `0.11.1`)? 🤔 

### Expected Behavior

Expect the variable `lsp-zig-zls-enable-autofix` being respected.

**Comment by Techatrix** [comment]
The [vscode-zig](https://github.com/ziglang/vscode-zig) extensions uses different names to refer to the ZLS config options. It adds a `zig.` prefix and converts the name to camelCase. You can find the relevant code [here](https://github.com/ziglang/vscode-zig/blob/b4801265aaf6d2485e613d20300f8ab8e5c38c97/src/zls.ts#L40-L47). This means that ZLS expects a config options like `zls.enable_autofix` while vscode-zig uses `zig.zls.enableAutofix`.

FYI: if you haven't already, ZLS's [log output](https://github.com/zigtools/zls/wiki/Guide:-How-to-view-ZLS-log-output) may help with figuring out whats going wrong.

> I was wondering what version is the VSCode using? Is it not `0.11.0`?

The vscode-zig extensions can install tagged releases or the latest master of Zig and ZLS. Do note that the config options it displays for ZLS target the master branch even if you use an older ZLS release. This means that options like `enable_build_on_save` or `completions_with_replace` would get ignored/rejected by ZLS when using an older release like 0.11.0 where these options are not available.

Also, your ZLS version should always match your Zig version. So if you use Zig master then you should also use ZLS master. If you use Zig 0.11.0 then ZLS 0.11.0. Mismatching the versions could lead to unexpected behavior like ZLS failing to resolve imported packages/modules.

**Comment by jcs090218** [comment]
Here is what I've tried. I have changed to use `0.11.0` on both `zls` and `zig`. And changed config option to `zls.enable_autofix`. But unfortunately, it's still not working. 🤔

**Comment by jcs090218** [comment]
> but even if I delete the entire content of the file it did not change anything. 

You don't need to delete the file. You just need to `eval` it.

> How am I supposed to debug the zig-mode package?

Do you mean the `lsp-mode`? `zig-mode` doesn't implement the LSP features. 🤔

**Comment by Techatrix** [comment]
> Do you mean the `lsp-mode`? `zig-mode` doesn't implement the LSP features. 🤔

Yes, sorry for the mixup. I meant `lsp-mode`.

---
I think I've managed to get it working. I tested this with ZLS master and ZLS 0.11.0.

<details>
  <summary>lsp-zig.el</summary>
  
```lisp
(lsp-register-custom-settings
 '(("zls.enable_snippets" lsp-zig-zls-enable-snippets)
   ("zls.enable_argument_placeholders" lsp-zig-zls-enable-argument-placeholders)
   ("zls.enable_build_on_save" lsp-zig-zls-enable-build-on-save)
   ("zls.build_on_save_step" lsp-zig-zls-build-on-save-step)
   ("zls.enable_autofix" lsp-zig-zls-enable-autofix)
   ("zls.semantic_tokens" lsp-zig-zls-semantic-tokens)
   ("zls.enable_inlay_hints" lsp-zig-zls-enable-inlay-hints)
   ("zls.inlay_hints_show_variable_type_hints" lsp-zig-zls-inlay-hints-show-variable-type-hints)
   ; inlay_hints_show_struct_literal_field_type is missing
   ("zls.inlay_hints_show_parameter_name" lsp-zig-zls-inlay-hints-show-parameter-name)
   ("zls.inlay_hints_show_builtin" lsp-zig-zls-inlay-hints-show-builtin)
   ("zls.inlay_hints_exclude_single_argument" lsp-zig-zls-inlay-hints-exclude-single-argument)
   ("zls.inlay_hints_hide_redundant_param_names" lsp-zig-zls-inlay-hints-hide-redundant-param-names)
   ("zls.inlay_hints_hide_redundant_param_names_last_token" lsp-zig-zls-inlay-hints-hide-redundant-param-names-last-token)
   ("zls.warn_style" lsp-zig-zls-warn-style)
   ("zls.highlight_global_var_declarations" lsp-zig-zls-highlight-global-var-declarations)
   ("zls.dangerous_comptime_experiments_do_not_enable" lsp-zig-zls-dangerous-comptime-experiments-do-not-enable)
   ("zls.skip_std_references" lsp-zig-zls-skip-std-references)
   ("zls.prefer_ast_check_as_child_process" lsp-zig-zls-prefer-ast-check-as-child-process)
   ("zls.record_session" lsp-zig-zls-record-session)
   ("zls.record_session_path" lsp-zig-zls-record-session-path)
   ("zls.replay_session_path" lsp-zig-zls-replay-session-path)
   ("zls.builtin_path" lsp-zig-zls-builtin-path)
   ("zls.zig_lib_path" lsp-zig-zls-zig-lib-path)
   ; zig_exe_path is missing
   ("zls.build_runner_path" lsp-zig-zls-build-runner-path)
   ("zls.global_cache_path" lsp-zig-zls-global-cache-path)
   ("zls.build_runner_global_cache_path" lsp-zig-zls-build-runner-global-cache-path)
   ("zls.completion_label_details" lsp-zig-zls-completions-with-replace)
   ; has been removed in master ("zls.completionLabelDetails" lsp-zig-zls-completion-label-details)
   ))
```
</details>

My config contains the following lines
```
(setq lsp-log-io t)
(setq lsp-zig-zls-enable-snippets t)
(setq lsp-zig-zls-semantic-tokens "partial")
(setq lsp-zig-zls-executable "/run/media/techatrix/UserFiles/zls/out/bin/zls")
```

I used `:lsp-workspace-show-log` to view ZLS's log output where you can see ZLS sending a workspace configuration request  and receiving the result. Some of them are from my own config and others are the default value from `lsp-zig.el`.

<details>
  <summary>relavent logs</summary>
  
```
[Trace - 01:45:15 ] Received request 'workspace/configuration - (i_haz_configuration).
Params: {
  "items": [
    {
      "section": "zls.enable_snippets"
    },
    {
      "section": "zls.enable_argument_placeholders"
    },
    {
      "section": "zls.enable_ast_check_diagnostics"
    },
    {
      "section": "zls.enable_autofix"
    },
    {
      "section": "zls.enable_import_embedfile_argument_completions"
    },
    {
      "section": "zls.semantic_tokens"
    },
    {
      "section": "zls.enable_inlay_hints"
    },
    {
      "section": "zls.inlay_hints_show_builtin"
    },
    {
      "section": "zls.inlay_hints_exclude_single_argument"
    },
    {
      "section": "zls.inlay_hints_hide_redundant_param_names"
    },
    {
      "section": "zls.inlay_hints_hide_redundant_param_names_last_token"
    },
    {
      "section": "zls.operator_completions"
    },
    {
      "section": "zls.warn_style"
    },
    {
      "section": "zls.highlight_global_var_declarations"
    },
    {
      "section": "zls.dangerous_comptime_experiments_do_not_enable"
    },
    {
      "section": "zls.include_at_in_builtins"
    },
    {
      "section": "zls.skip_std_references"
    },
    {
      "section": "zls.max_detail_length"
    },
    {
      "section": "zls.prefer_ast_check_as_child_process"
    },
    {
      "section": "zls.record_session"
    },
    {
      "section": "zls.record_session_path"
    },
    {
      "section": "zls.replay_session_path"
    },
    {
      "section": "zls.builtin_path"
    },
    {
      "section": "zls.zig_lib_path"
    },
    {
      "section": "zls.zig_exe_path"
    },
    {
      "section": "zls.build_runner_path"
    },
    {
      "section": "zls.global_cache_path"
    },
    {
      "section": "zls.build_runner_global_cache_path"
    }
  ]
}


[Trace - 01:45:15 ] Sending response 'workspace/configuration - (i_haz_configuration)'. Processing request took 8ms
Params: {
  "jsonrpc": "2.0",
  "id": "i_haz_configuration",
  "result": [
    true,
    true,
    null,
    null,
    null,
    "partial",
    true,
    true,
    true,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    true,
    null,
    "",
    "",
    "",
    "",
    null,
    "",
    "",
    ""
  ]
}
```
</details>

One thing I couldn't figure out is how to set a config option to `false`.

**Comment by jcs090218** [comment]
I don't think it works. 🤔 At least `(setq lsp-zig-zls-enable-autofix nil)` doesn't work.

> One thing I couldn't figure out is how to set a config option to false.

This is how you set something to false in elisp, `(setq VAR-NAME nil)`.

**Comment by Techatrix** [comment]
using `(setq VAR-NAME nil)` is exactly what I tried. The problem is that ZLS receives `null` instead of `false` as the new config value from Emacs.

**Comment by jcs090218** [comment]
The solution is to set the third argument `boolean?`.

```diff
- ("zls.enable_autofix" lsp-zig-zls-enable-autofix)
+ ("zls.enable_autofix" lsp-zig-zls-enable-autofix t)
```

Thank you very much! I have made the changes in https://github.com/emacs-lsp/lsp-mode/pull/4350.

**Comment by jcs090218** [comment]
Thanks! Fixed in https://github.com/emacs-lsp/lsp-mode/pull/4351.
