### ISSUE TITLE
Strict version checking is flawed as is.

### ISSUE THREAD

**Issue by zkburke** [zigtools/zls#1811]
The strict version checking just introduced in https://github.com/zigtools/zls/commit/f25fafe991b76735748a7ac37e95e6d660c5faa8 determines that the zls version isn't tagged if the pre or build part of the semver is null. This is seems reasonable on the surface but the version set in the build options is set to this constant: 

```zig
const zls_version = std.SemanticVersion{ .major = 0, .minor = 12, .patch = 0 };
```  
As such, when opening a zig file I'm spammed with multiple warnings emitted by this code snippet in Server.zig in ```updateConfiguration()```:

```zig
const zig_version_is_tagged = zig_version.pre == null and zig_version.build == null;
const zls_version_is_tagged = build_options.version.pre == null and build_options.version.build == null;

const zig_version_simple = std.SemanticVersion{ .major = zig_version.major, .minor = zig_version.minor, .patch = 0 };
const zls_version_simple = std.SemanticVersion{ .major = build_options.version.major, .minor = build_options.version.minor, .patch = 0 };

if (zig_version_is_tagged != zls_version_is_tagged) {
    if (zig_version_is_tagged) {
        server.showMessage(
            .Warning,
            "Zig {} should be used with ZLS {} but ZLS {} is being used.",
            .{ zig_version, zig_version_simple, build_options.version },
        );
    } else if (zls_version_is_tagged) {
        server.showMessage(
            .Warning,
            "ZLS {} should be used with Zig {} but found Zig {}. ",
            .{ build_options.version, zls_version_simple, zig_version },
        );
    } else unreachable;
    break :version_check;
}
``` 
This might seem like something I could just fix myself but it would either require neutering this commit (which on all other fronts is an improvement) or proposing to add a build part to the zls semver, and I don't know what is wanted by the developers of zls so I'm just chipping in here with the problem (adding a build number seems reasonable to me as that's what zig's using). Another thing that could be done is storing the full semantic version of zig used to build zls and doing some comparisons with that in the above snippet.

Oh and if it isn't clear I'm using the nightly version of zig and a fresh local build of zls, but this problem would occur with any version of zig or zls because of the aforementioned constant zls version.

**Comment by Techatrix** [comment]
ZLS uses the same logic as Zig for resolving the version using git. [code here](https://github.com/zigtools/zls/blob/0a891774b077c028b6bc867b629c4f54ad6d9a82/build.zig#L265). The line that returns the version with pre and build part is [here](https://github.com/zigtools/zls/blob/0a891774b077c028b6bc867b629c4f54ad6d9a82/build.zig#L293).
What is your output of `zig version` and `zls --version`? It is possible to compile ZLS master and have it resolve to `0.12.0` when `git` wasn't available. failed to be executed or not all commits were fetched.

**Comment by zkburke** [comment]
```
zig-out/bin/zls --version => 0.12.0
zig version => 0.12.0-dev.3126+136d7c213
```

I built zls using ```zig build -DReleaseSafe```

**Comment by Techatrix** [comment]
What do you get when run: `git -C . describe --match "*.*.*" --tags` inside the ZLS folder?

**Comment by zkburke** [comment]
```git -C . describe --match "*.*.*" --tags``` gives me ```fatal: No names found, cannot describe anything.```
That's very strange. This is all being done in a clone of my up to date fork of zls. I might need to get a fresh clone, but I have no idea why it would give me that output.

**Comment by Techatrix** [comment]
What about `git -C . describe --tags`?

**Comment by zkburke** [comment]
I get the exact same output. I'm happy to close this issue assuming this is my local environment at fault, as I think this might be at risk of wasting your time.

**Comment by zkburke** [comment]
I've just tried this on a fresh clone of my fork, and on a fresh clone of zigtools/zls, and it seems to be an issue with my fork and I'm not sure why it's happening (on this repo I get ```0.11.0-477-g0a89177``` from ```git -C describe --tags```).

**Comment by Techatrix** [comment]
> I think this might be at risk of wasting your time.

Definitely not, I did actually think of this being a possibility but forgot about resolving this. I can add a check for this situation so that no warnings get shown.

> I've just tried this on a fresh clone of my fork, and on a fresh clone of zigtools/zls, and it seems to be an issue with my fork and I'm not sure why it's happening (on this repo I get `0.11.0-477-g0a89177` from `git -C describe --tags`).

This should hopefully mean that not incorrect warning gets shown.

**Comment by zkburke** [comment]
I might suggest a different approach for version checking but I think my case of building from my own fork (which seems to have broken tags (why github? why?)) is a little esoteric so I think I'll just clone from this repo and build from that for now.
