### ISSUE TITLE
"executable bit" is missing in binary release

### ISSUE THREAD

**Issue by jcs090218** [zigtools/zls#1818]
### Zig Version

0.11.0

### Zig Language Server Version

0.11.0

### Client / Code Editor / Extensions

Emacs

### Steps to Reproduce and Observed Behavior

1. Use Emacs with `lsp-mode`
2. Auto-install the zig executable (downalod, untar, then extract) with `lsp-mode`
3. Permission denied `bin/zls`

### Expected Behavior

`bin/zls` is executable ready.

### Relevant log output

No answer.

### Additional Information

I only tried the `zls-aarch64-macos.tar.gz`. Not sure if all the binary releases have the same issue. :thinking:

**Comment by Techatrix** [comment]
All of the GitHub releases for ZLS 0.11.0 and 0.9.0 that I checked do not have the executable file permission bits set. I do not think that this is enough to justify modifying or updating these releases retroactively. The auto-install steps should set the file permissions to `755` `rwxr-xr-x` after extracting the tarball to avoid this issue.

**Comment by jcs090218** [comment]
Would this be changed in the future? Having the executable file permissions bit sets would be much easier for users. 🤔

**Comment by Techatrix** [comment]
I will make sure that the upcoming ZLS 0.12.0 release won't repeat this mistake if that is what you were asking.
