### ISSUE TITLE
build.zig error on constant declaration

### ISSUE THREAD

**Issue by maximelapointe** [zigtools/zls#1832]
### Zig Version

0.11.0

### Zig Language Server Version

fd3b5afe51ee57dbfba2db317e48a13abf741039

### Client / Code Editor / Extensions

vscode latest. Windows. ziglang extension.

### Steps to Reproduce and Observed Behavior

in Readme.md, it is mentionned to use these steps to build zls from source:
git clone https://github.com/zigtools/zls
cd zls
zig build -Doptimize=ReleaseSafe

during zig build step, you will receive:
error: expected ';' after declaration
    const version_string, const precise_version_string = getVersion(b);
    
Line 28 is the code line in question and can be found in build.zig: 
const version_string, const precise_version_string = getVersion(b);

### Expected Behavior

Using recommended zig build command on build.zig found in master branch should build without an error message.

**Comment by maximelapointe** [comment]
I apologize if I am unable to investigate the error past this point, as I'm actually trying to learn Zig and barely started 1h ago.

**Comment by nullptrdevs** [comment]
https://github.com/zigtools/zls?tab=readme-ov-file#from-source

> Building zls is very easy. **You will need [a build of Zig master](https://ziglang.org/download/) to build zls.**

Follow that link and download zig-0.12.0-dev.3333+ce4245f87 for your cpu and os.

**Comment by maximelapointe** [comment]
@nullptrdevs I missed that part, apparently.

I went to check and it seems all package managers are still on 0.11, which I was currently using.
I tried with the most recent 0.12 and it worked.

Thank you, Issue closed.
