### ISSUE TITLE
Fork and rehost coc-zls under zigtools org

### ISSUE THREAD

**Issue by Pyrolistical** [zigtools/zls#1838]
The instructions for Coc https://github.com/zigtools/zls/wiki/Installation#with-extension say to use `:CocInstall coc-zls`

Coc uses npm under the hood, so it finds https://www.npmjs.com/package/coc-zls, which is owned by https://github.com/xiyaowong

No offense to @xiyaowong, but if that account ever gets compromised, all users of coc-zls are compromised. If we need to trust zls anyways, then zigtools should rehost coc-zls.

**Comment by Techatrix** [comment]
coc-zls has been removed from the [Installation Guide](https://github.com/zigtools/zls/wiki/Installation#coc) and is no longer recommended. See discussion: https://github.com/zigtools/zls/issues/1972#issuecomment-2259110145
