### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by truemedian** [zigtools/zls#184]
Running `zig build test` no longer completes successfully (most likely due to not being kept up-to-date).

This throws off the CI from giving accurate information.

**Comment by alexnask** [comment]
Yes, this is on top of my todo, sorry about it (I think all that needs to change is the semanticTokens request url)
Btw I see you are working on the workflows, the tests do not work on windows (even when they did work), I will fix that too

**Comment by truemedian** [comment]
307ac34d4a40ee841168fc0420972022950dbb98 seems to have fixed this, thanks!
