### ISSUE TITLE
Proposal: Only show missing fields in autocompletion on struct initialization

### ISSUE THREAD

**Issue by IntegratedQuantum** [zigtools/zls#1849]
So right now I'm in the process of learning Vulkan and it has a ton of large configuration structs.
Now I would like to know what fields are missing so far and it would be nice if autocomplete would only show missing members.
Since it isn't allowed to initialize a field twice it doesn't even make sense to show already present fields.
## Current:
![Screenshot at 2024-04-08 21-10-34](https://github.com/zigtools/zls/assets/43880493/f57774c1-d017-45ed-a664-a66a97a582d3)
## Proposed:
![Screenshot at 2024-04-08 21-10-35](https://github.com/zigtools/zls/assets/43880493/b4605eee-8896-4898-8299-4c1e5d8c6d34)

**Comment by Techatrix** [comment]
The completion tests for struct initialization have some examples of this [here](https://github.com/zigtools/zls/blob/4e01c08f558ea07462aaa7b71d2a24f86f47a855/tests/lsp_features/completion.zig#L1634).

**Comment by llogick** [comment]
Initial support in https://github.com/zigtools/zls/tree/nullptrdevs/c012,

> Excludes fields/switch cases that precede the current source_index, ie
> ```zig
> S{
>    .a = 1,
>    .b = 2,
>    . // ^--- excluded from completions list
>    .fields_here = 3,
>    .are_shown = 4,
> };
> ```
