### ISSUE TITLE
ZLS not found in path by VS Code extension when in fact it is in $PATH

### ISSUE THREAD

**Issue by tristanisham** [zigtools/zls#1858]
### Zig Version

0.12.0-dev.3639+9cfac4718

### Zig Language Server Version

0.12.0-dev.504+4e01c08

### Client / Code Editor / Extensions

VS Code with the ZLS Extension

### Steps to Reproduce and Observed Behavior

Start VS Code in a Zig Project. The extension won't load ZLS even if it's set in the extension.

### Expected Behavior

The extension to connect to ZLS

**Comment by llogick** [comment]
Hi,

Please file zig vscode extension issues here https://github.com/ziglang/vscode-zig

Cheers
