### ISSUE TITLE
integer overflow not highlighted as an error

### ISSUE THREAD

**Issue by ngc6302h** [zigtools/zls#1862]
## integer overflow not highlighted as an error

The following code should have a hover error over the assignment to 500, as 500 would overflow the 8 bit integer. zls, however, doesn't say anything about this.
```
const std = @import("std");

pub fn main() u8 {
    const k : u8 = 500;
    return k;
}
```

**Comment by Techatrix** [comment]
This issue is a very specific example of #2017. There is no need to track this separately so I will be closing this.
