### ISSUE TITLE
Raylib autocomplete doesn't work

### ISSUE THREAD

**Issue by lmarzocchetti** [zigtools/zls#1866]
### Zig Version

0.12.0

### Zig Language Server Version

0.12.0-dev.517+fcb9eec

### Client / Code Editor / Extensions

Visual Studio Code

### Description
I'm using raylib (the C library without wrappers), the executable compiles perfectly, but zls give me ' "raylib.h" file not found '.
It's a regression, because 1 month ago with the same project but with different versions of zig/zls worked fine.

### Step to Reproduce
I used this github repository: https://github.com/SimonLSchlee/zigraylib 
Simply from build.zig.zon remove the raylib entry and run:
```
zig fetch --save=raylib "https://github.com/raysan5/raylib/archive/29ce13b.tar.gz"
```
after:
```
zig build run
```
### Observed behaviour
Open this project in vscode (or other editor with zls(?)) and you will see that the autocomplete doesn't work, and if you go to the @cImport declaration, you can notice the error ' "raylib.h" file not found '.

### Expected Behavior

Working autocomplete with zls and c libraries

### Relevant log output

warning: (translate_c): failed to delete file '/Users/rhohen/Library/Caches/zls/cimport.h': error.FileNotFound
[Trace - 5:09:37 PM] Received response 'textDocument/inlayHint - (329)' in 1074ms.
warning: (translate_c): failed to delete file '/Users/rhohen/Library/Caches/zls/cimport.h': error.FileNotFound

**Comment by lmarzocchetti** [comment]
I'm experiencing the same kind of bug in the last master release (in the 0.13.0 release all works fine)

**Comment by lmarzocchetti** [comment]
> I'm experiencing the same kind of bug in the last master release (in the 0.13.0 release all works fine)

It is not a bug in the master release, i compiled from source and all works. The problem is in the section of "Installation Guide". That the Nighly build it is not the last master release compiled but the 0.13.0 build. Which broke the autocompletions for the latest Zig master release

**Comment by Krymancer** [comment]
Do you was able to make this work? I'm currently having the same issue

**Comment by lmarzocchetti** [comment]
@Krymancer I have submitted a pull request, after the merge the autocompletion is restored, so take a look!
