### ISSUE TITLE
error: container 'std.heap' has no member called 'GeneralPurposeAllocator'

### ISSUE THREAD

**Issue by joshvoll** [zigtools/zls#187]
OS : macOS Catalina version 10.15.7
zig Version: 0.6.0
Installation from : brew install zig --HEAD

Problem
-> zig build

Error:
./src/main.zig:1518:25: error: container 'std.heap' has no member called 'GeneralPurposeAllocator'
var gpa_state = std.heap.GeneralPurposeAllocator(.{}){};
                        ^
./src/main.zig:1521:18: note: referenced here
    allocator = &gpa_state.allocator;
                 ^
zls...The following command exited with error code 1:

**Comment by alexnask** [comment]
Hi, zls is currently meant to be built with a master build of zig (you can find binaries [here](https://ziglang.org/download/).  
I will stabilize the master branch for zig 0.7.0 when it comes out (Saturday) and split off to a new branch for builds with master zig.
