### ISSUE TITLE
Fails to build on 0.13.0-dev.46+3648d7df1

### ISSUE THREAD

**Issue by aryzing** [zigtools/zls#1875]
### Zig Version

0.13.0-dev.46+3648d7df1

### Zig Language Server Version

e96503d9c11c061573fa68cc8aafa575138418a0

### Steps to Reproduce and Observed Behavior

Running `zig build -Doptimize=ReleaseSafe` produces several similar errors to

```
    /lib/zig/std/Build.zig:1065:27: note: expected 2 arguments, found 3
    const uninstall_tls = @fieldParentPtr(TopLevelStep, "step", uninstall_step);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected Behavior

Successful compilation

**Comment by Techatrix** [comment]
The [line in Build.zig](https://github.com/ziglang/zig/blob/3648d7df19642b6902b3f75538a826a322211673/lib/std/Build.zig#L1066) you referenced does not match the standard library at the time of `0.13.0-dev.46+3648d7df1`.

Please run `zig env` and verify that the `lib_dir` field points to the correct standard library directory.

**Comment by aryzing** [comment]
My bad, was pointing to incorrect lib version.
