### ISSUE TITLE
Release missing tar.gz

### ISSUE THREAD

**Issue by jcs090218** [zigtools/zls#1879]
### Zig Version

0.12.0

### Zig Language Server Version

0.12.0

### Client / Code Editor / Extensions

Emacs

### Steps to Reproduce and Observed Behavior

The original extension was `tar.gz` but now is `tar.xz`. Is there a reason why the extension has changed? 🤔 

More info see https://github.com/emacs-lsp/lsp-mode/issues/4445.

### Expected Behavior

n/a

**Comment by maxdeviant** [comment]
It would be very helpful to have the `.tar.gz` artifacts restored, as those are the ones that we use for Zed.

**Comment by maxdeviant** [comment]
> It would be very helpful to have the `.tar.gz` artifacts restored, as those are the ones that we use for Zed.

I should also note that we're not really enthused by the thought of having to support `.xz` files in Zed, in light of the recent `xz` backdoor.

**Comment by JonGretar** [comment]
Any news on the gzip files returning?

**Comment by Techatrix** [comment]
I'm sorry for leaving this issue answered so long but at least I have some good news.

ZLS has a new [Install Page](https://zigtools.org/zls/install/). For every `tar.xz` file, a `.tar.gz` file is available as well.
For more information, please refer to the new ZLS [release-worker](https://github.com/zigtools/release-worker).
Please let me know if this resolves your issue.

**Comment by maxdeviant** [comment]
> I'm sorry for leaving this issue answered so long but at least I have some good news.
> 
> ZLS has a new [Install Page](https://zigtools.org/zls/install/). For every `tar.xz` file, a `.tar.gz` file is available as well. For more information, please refer to the new ZLS [release-worker](https://github.com/zigtools/release-worker). Please let me know if this resolves your issue.

Thank you for the update!

I'll take a look at getting the Zig extension updated to use the new install page.

**Comment by versecafe** [comment]
@maxdeviant I can take care of it and make a PR
