### ISSUE TITLE
semicolon autofix sometimes results in invalid code

### ISSUE THREAD

**Issue by travisstaloch** [zigtools/zls#1883]
### Zig Version

0.13.0-dev.46+3648d7df1

### Zig Language Server Version

0.13.0-dev.6+75bd32d

### Client / Code Editor / Extensions

sublime text stable build 4169

### Steps to Reproduce and Observed Behavior

related to #1475 and #1476

### repro 1 
```zig
comptime {
  const x = hello,
}
```
save results in
```zig
comptime {
  const x = hello,;
}
```
### repro 2
```zig
comptime {
  const x = hello 0
}
```
save results in
```zig
comptime {
  const x = hello 0;;
}
```

### Expected Behavior

Saving should produce valid code.

**Comment by travisstaloch** [comment]
And with a block
### repro 3
```zig
comptime {
  { hello 0 }
}
```
save results in
```zig
comptime {
  { hello 0; };
}
```

**Comment by travisstaloch** [comment]
With a switch statement
```zig
comptime {
 switch(1) { 1 => {hello} }
}
```
save results in
```zig
comptime {
 switch(1) { 1 => {hello}; }
}
```

**Comment by travisstaloch** [comment]
In my experience during the past month or so these extra semicolons have been rare.  But since this feature seems to have problems, I would like to see it either turned off by default or removed until fuzzing has been implemented and more bugs like these have been found.

**Comment by Cloudef** [comment]
I think config options for the autofix fixes should be implemented.

**Comment by travisstaloch** [comment]
I also posted here https://www.reddit.com/r/pop_os/comments/1ci8fo4/pop_shop_update_changed_my_login_screen_to_a/
