### ISSUE TITLE
Structs not folding in VS Code

### ISSUE THREAD

**Issue by aryzing** [zigtools/zls#1895]
Code folding isn't working with structs in VS Code. E.g., in the following example, would expect to see the `return struct {` keyword as a sticky line in the editor,

[simplescreenrecorder-2024-05-13_12.29.53.webm](https://github.com/zigtools/zls/assets/4924405/a706a8cc-7bd3-43d3-889b-a3d6ee5b8289)

**Comment by Techatrix** [comment]
You will need to set `editor.stickyScroll.defaultModel` to `foldingProviderModel` which will match the folding ranges returned by ZLS.

**Comment by aryzing** [comment]
Amazing, thanks!
