### ISSUE TITLE
Annotations are incorrect 

### ISSUE THREAD

**Issue by akhildevelops** [zigtools/zls#1897]
### Zig Version

0.12.0

### Zig Language Server Version

0.12.0

### Client / Code Editor / Extensions

VsCode

### Steps to Reproduce and Observed Behavior

![image](https://github.com/zigtools/zls/assets/6951100/258ff5ca-5c42-4b48-9bf9-14dd87e48bd9)

I've declared an arraylist containing slice of u8 slices.
`var splits = std.ArrayList([][]const u8).init(allocator);`

While iterating I get wrong annotation but the hover gives correct type info, as seen in the above image

### Expected Behavior

Both should be consistent

**Comment by Techatrix** [comment]
The following code snippet resolves `item` as `[][]const u8`. Could you post the entire code snippet?
```zig
const std = @import("std");
test {
    const splits = std.ArrayList([][]const u8).init(undefined);
    for (splits.items) |item| {
        _ = item;
    }
}
```
I suspect this to be related to #1392.

**Comment by akhildevelops** [comment]
For me i's still incorrect.

![image](https://github.com/zigtools/zls/assets/6951100/26febf2f-9f86-42f2-a1f5-4942a73ed6b7)

Zig - 0.12.0
ZLS- 0.12.0
Zig VsCode Extension- 0.5.7
VSCode - 1.89.1

**Comment by Techatrix** [comment]
> For me i's still incorrect.

I can't reproduce this with Zig 0.12.0 and ZLS 0.12.0.

You could you post [ZLS's log output](https://github.com/zigtools/zls/wiki/Guide:-How-to-view-ZLS-log-output)? (VSCode: Bottom Panel -> Output -> Zig Language Server)

**Comment by akhildevelops** [comment]
[kazam_qfoenyyr.movie.webm](https://github.com/zigtools/zls/assets/6951100/ce69e5fe-3668-4253-bd8d-5745314e8c31)

I got the issue, type annotations are wrong when there's for loop iteration before it. You can see in the video.

**Comment by Techatrix** [comment]
This is the same underlying issue as #1841
