### ISSUE TITLE
Auto completion of c functions does not work with the latest zls.

### ISSUE THREAD

**Issue by drshapeless** [zigtools/zls#1900]
### Zig Version

0.13.0-dev.217+ad7217229

### Zig Language Server Version

0.12.0-dev.365+a8a83b6

### Client / Code Editor / Extensions

emacs

### Steps to Reproduce and Observed Behavior

In main.zig

    const C = @cImport({
        @cInclude("c_print.h");
    });
    
    pub fn main() !void {
        C.c_print();
    }

In c\_print.c

    #include "c_print.h"
    
    #include <stdio.h>
    
    void c_print() {
        printf("hello from c\n");
    }

In c\_print.h

    #ifndef C_PRINT_H
    #define C_PRINT_H
    
    void c_print();
    
    #endif /* C_PRINT_H */

The build.zig is correctly configured so the include path, c\_source\_path, and libC are linked.

When I run `zig build run`, the program is correctly compiled and print what I expected. Yet, no auto-completion from zls.

However, when I downgraded to zig version 0.12.0 and zls version 0.12.0. Things are working well.

### Expected Behavior

Auto completion for c functions

**Comment by xdBronch** [comment]
completions like this not working is usually a sign of a zig/zls version mismatch which i think is quite likely since the zls version you gave is 4 months old. [check your lsp logs](https://github.com/zigtools/zls/wiki/Guide:-How-to-view-ZLS-log-output) for any errors from ZLS

**Comment by drshapeless** [comment]
> completions like this not working is usually a sign of a zig/zls version mismatch which i think is quite likely since the zls version you gave is 4 months old. [check your lsp logs](https://github.com/zigtools/zls/wiki/Guide:-How-to-view-ZLS-log-output) for any errors from ZLS

My bad. I made a silly mistake that I forget to move my compiled zls binary to my installed path. Thank you for your time.
