### ISSUE TITLE
Remove `main` snippet

### ISSUE THREAD

**Issue by sno2** [zigtools/zls#1909]
I have a lot of code where I need to write `main_token`. I have repeatedly typed `main` and then pressed tab expecting auto-complete for `main_token` only for it to spit out `pub fn main() !void {}`.

When would you even manually write a main function? `zig init` handles this for you and anyone who is going to run into a situation where they need to write out their own main function would likely know how to do it. Furthermore, it is sort of odd to autocomplete to `!void` when the user could want any of the following options: `void`, `!void`, `u8`, `!u8`.

Thanks

**Comment by Techatrix** [comment]
Does #1910 resolve your issue?

**Comment by sno2** [comment]
> Does #1910 resolve your issue?

Yep that would work. Thanks
