### ISSUE TITLE
Errors reported in multiline strings

### ISSUE THREAD

**Issue by RUSshy** [zigtools/zls#191]
```zig
var mystring = 
\\#version 0
;
```

it'll complain with:

``expected ';', found invalid bytes``

**Comment by alexnask** [comment]
Hm, I cannot reproduce this, can you upload a small test file where this happens? Thanks

**Comment by RUSshy** [comment]
![image](https://user-images.githubusercontent.com/18348637/99077040-6c8a1480-25bc-11eb-9564-18c768ee50e5.png)

[test.zip](https://github.com/zigtools/zls/files/5536978/test.zip)

**Comment by alexnask** [comment]
Looks like an issue with CRLF in multiline string literals in the stdlib parser, I will fix it upstream.  
Thanks for reporting
