### ISSUE TITLE
Hover fails on `@""` identifiers

### ISSUE THREAD

**Issue by Radvendii** [zigtools/zls#1929]
Not sure if this is a bug or improvement, but I went with improvement because nothing returns an **incorrect** result.

Using hover on `@""` identifiers doesn't work. It would be nice if it did.

**Comment by Techatrix** [comment]
Identifiers are not allowed to be empty. Zig and ZLS will report `error: identifier cannot be empty`.

**Comment by Radvendii** [comment]
No I mean like `@"foo-bar"`
