### ISSUE TITLE
System-wide config locations

### ISSUE THREAD

**Issue by daurnimator** [zigtools/zls#193]
> You can configure zls by providing a zls.json file.
> zls will look for a zls.json configuration file in multiple locations with the following priority:
>
>  - In the local configuration folder of your OS (as provided by known-folders)
>  - In the same directory as the executable

  - known-folders only (currently) provides user-specific locations
  - the executable is likely to be at e.g. `/usr/bin/zls`, config files should not be in `/usr/bin`, but instead at e.g. `/etc/zls.json`

**Comment by alexnask** [comment]
Implemented in df22d2490bcfe81bc026b878a1a942370803e213
