### ISSUE TITLE
Auto completion for c function definitions with no param names should provide some kind of placeholders

### ISSUE THREAD

**Issue by glyh** [zigtools/zls#1932]
Say, for example, I have this

![image](https://github.com/zigtools/zls/assets/12870742/da95a0db-c3dc-4a7f-88da-5873ee8a52b4)

For now the auto completion just gives a definition where each param has no name. But I think it would be nice if we have something like `arg1`, `arg2`, etc.

**Comment by Techatrix** [comment]
I don't see a reason for giving parameters artificial names like  `arg1` or `arg2` instead of just omitting them. #1933 will remove the `: `.
