### ISSUE TITLE
Regression due to #1671 C imports no longer found on Windows

### ISSUE THREAD

**Issue by btipling** [zigtools/zls#1940]
### Zig Version

0.14.0-dev.154+768b17755

### Zig Language Server Version

4408eb218461625fc9ce594dfa4578c53c9d33ca

### Client / Code Editor / Extensions

Visual Studio Code 1.91.0 (user setup)

### Steps to Reproduce and Observed Behavior

on Windows version Windows 11 Pro 23H2 22631.3810
in zls repo:
```
git checkout 4408eb218461625fc9ce594dfa4578c53c9d33ca 
rm -r .zig-cache
zig build -Doptimize=ReleaseSafe
```
In separate directory:
```
git clone https://github.com/btipling/foundations
cd foundations
zig build 
```
in foundations, everything builds fine
open src\foundations\c.zig with vs code
See zls unable to complete any c
![image](https://github.com/zigtools/zls/assets/249641/23ccb62b-8caa-49c1-93ab-69e0b5f0efc4)

close vs code

```
git checkout a263b8dc66bb134aea962b816a93af284b5154d2 
rm -r .zig-cache
zig build -Doptimize=ReleaseSafe
```
open src\foundations\c.zig with vs code 
see everything is imported fine
![image](https://github.com/zigtools/zls/assets/249641/948a8775-1923-48df-985c-83724f644743)

### Expected Behavior

I expected C imports to be known to ZLS

### Relevant log output

```shell
info : ( main ): Starting ZLS 0.14.0-dev.23+4408eb2 @ 'C:\Users\swart\projects\zls\zig-out\bin\zls.exe'
info : (server): Client is 'Visual Studio Code-1.91.0'
info : (server): Set config option 'enable_autofix' to 'true'
info : (server): Set config option 'builtin_path' to 'C:\Users\swart\AppData\Local\Temp\zls\builtin.zig'
info : (server): Set config option 'zig_lib_path' to 'C:\Users\swart\zig-stuff\zig\0.14.0-dev.154+768b17755\files\lib'
info : (server): Set config option 'zig_exe_path' to 'C:\Users\swart\zig-stuff\zig.exe'
info : (server): Set config option 'build_runner_path' to 'C:\Users\swart\AppData\Local\Temp\zls\build_runner\dc1a8653090eccd89b5ff10b26826142\build_runner.zig'
info : (server): Set config option 'global_cache_path' to 'C:\Users\swart\AppData\Local\Temp\zls'
info : (server): Set config option 'enable_autofix' to 'false'
info : (server): Set config option 'semantic_tokens' to 'partial'
info : (server): Set config option 'inlay_hints_show_variable_type_hints' to 'false'
info : (server): Set config option 'inlay_hints_show_parameter_name' to 'false'
info : (server): Set config option 'zig_exe_path' to 'C:\Users\swart\zig-stuff\zig.EXE'
```

**Comment by Techatrix** [comment]
Does #1942 resolve your issue? I haven't tested it on the project you have linked but it did fix cimport for me on an small example project I created.

**Comment by btipling** [comment]
@Techatrix yes that resolves the issue, thank you!
