### ISSUE TITLE
Autosuggestion feature for try expressions

### ISSUE THREAD

**Issue by akhildevelops** [zigtools/zls#1947]
ZLS beautifully shows available methods / fields for a struct value but doesn't show for values accessed after try expression.

- file object shows all available methods / fields 
![image](https://github.com/zigtools/zls/assets/6951100/70426d86-a357-46cf-8b25-4de68bbc3430)

- file object doesn't show anything that's available after try expression
![image](https://github.com/zigtools/zls/assets/6951100/79f07426-a2f4-4330-a5db-f073025a7299)

**Comment by llogick** [comment]
You make a compelling argument #1948

**Comment by Techatrix** [comment]
fixed by #1948
