### ISSUE TITLE
<0x7f> added when removing symbol name using CTRL + BACKSPACE in Sublime Text

### ISSUE THREAD

**Issue by RUSshy** [zigtools/zls#195]
Hi,

When using zls with LSP plugin in sublime text, all works fine except this litlte annoying thing

When i type a symbol name, and then press CTRL + BACKSPACE, it removes it then adds ``<0x7f>`` 

Here a gif:  https://i.imgur.com/9jIEqaT.gifv

`` 27:7   	zls         	error     	expected 'Identifier', found invalid bytes``

When trying to copy paste the that msg on github, it adds a whitespace instead

**Comment by alexnask** [comment]
Thanks for the report, will check it out later today.  
It may be a sublime text client bug, I will investigate.

**Comment by RUSshy** [comment]
It seems random, i reinstalled all (sublime + LSP + zls) and i don't have the problem anymore, i might have had an old version of LSP plugin

I'll report back if i ever encounter that bug

**Comment by RUSshy** [comment]
I found the cause: https://forum.sublimetext.com/t/ctrl-backspace-inserts-invisible-0x7f-del-character/13050

I had the Purchase Popup in the background, closing it fixes the issue lol, maybe time for me to finally buy it xD
