### ISSUE TITLE
Suggest deinit method if present for the object

### ISSUE THREAD

**Issue by akhildevelops** [zigtools/zls#1956]
It would be helpful to suggest `defer deinit method` or write by default after initialisation of objects if present, Later developer can delete or keep it if needed.

**Comment by InKryption** [comment]
`defer thing.deinit();` is merely a convention, and doesn't make sense to suggest in exactly that way for all types, even those with a deinit method. For some contexts `errdefer` would be the correct approach, or there may be multiple ways of deinitializing something based on how it was created, or how parts of its resources are being used (imagine `deinitShallow`).

At best, this would remind the developer to do something which is usually obvious/the developer was going to do anyway/would have been caught by GPA.
At worst, this would give the programmer (especially a new one) the false impression of correct code, in a situation where the suggestion is incorrect.

Not to mention the various alternative but equally valid conventions like `open`/`close`, `start`/`finish`, `create`/`destroy`, which this would fail to address.

**Comment by akhildevelops** [comment]
Your argument seem to be fair. Closing down the request.
