### ISSUE TITLE
autofix `_ = non_const_var` to `_ = &non_const_var`

### ISSUE THREAD

**Issue by silbinarywolf** [zigtools/zls#1959]
Update autofixing to use `&` for `var` that are not constant so that there is not a compile error about changing the variable to `const`.
```
var non_const_var = 0;
_ = &non_const_var
```

Raised previously here on Zig issues: https://github.com/ziglang/zig/issues/20584
Comment on why I want it written here: https://github.com/ziglang/zig/issues/20584#issuecomment-2224297888

**Comment by WillLillis** [comment]
This proposal was already rejected, see #1949.
