### ISSUE TITLE
No syntax coloring in preview popup

### ISSUE THREAD

**Issue by RUSshy** [zigtools/zls#196]
I first thought it was an issue with the LSP plugin from sublime text, so i reported an issue there but they told me it is server's responsability to define that, so here i am opening an issue here instead 

For details and context: https://github.com/sublimelsp/LSP/issues/1472

**Comment by rchl** [comment]
Actually, I've just realized something that might mean it's a bug in ST. Let's discuss back there.

**Comment by RUSshy** [comment]
Thanks to rchl, it now works, you only have to add:

```json
	"mdpopups.sublime_user_lang_map": {
		"zig": [ ["zig"], ["Zig Language/Syntaxes/Zig"] ]
	},
``` 

In your settings
