### ISSUE TITLE
Build failure linux

### ISSUE THREAD

**Issue by aryzing** [zigtools/zls#1962]
### Zig Version

0.14.0-dev.363+c3faae6bf

### Zig Language Server Version

41dae221fab979b3764e9191d8126e09625b0bb2

### Client / Code Editor / Extensions

n/a

### Steps to Reproduce and Observed Behavior

`zig build -Doptimize=ReleaseSafe`

### Expected Behavior

The build to succeed

### Relevant log output

```shell
/home/user/.local/lib/zig/std/os/linux.zig:719:9: error: @bitCast size mismatch: destination type 'usize' has 32 bits but source type 'os.linux.fanotify.MarkMask' has 64 bits
        @bitCast(mask),
        ^~~~~~~~~~~~~~
/home/user/.local/lib/zig/std/os/linux.zig:4211:33: note: struct declared here
    pub const MarkMask = packed struct(u64) {
                         ~~~~~~~^~~~~~
referenced by:
    fanotify_markZ: /home/user/.local/lib/zig/std/posix.zig:4555:36
    fanotify_mark: /home/user/.local/lib/zig/std/posix.zig:4542:30
    6 reference(s) hidden; use '-freference-trace=8' to see all references
```
```

**Comment by Techatrix** [comment]
Are you running on a 32-bit machine or did you accidentally use x86-linux?
See https://github.com/ziglang/zig/pull/20675

**Comment by aryzing** [comment]
The error is thrown on a 64bit Ubuntu 24.04 LTS

**Comment by Techatrix** [comment]
What is your output of `zig env`?

**Comment by aryzing** [comment]
You're right, the system had the wrong version of zig. Thanks!
