### ISSUE TITLE
always sort identifiers before keywords in completions

### ISSUE THREAD

**Issue by nektro** [zigtools/zls#1965]
(i couldve swore i saw an issue for this before but cant find it; maybe i hallucinated, sorry if there is one)

i cannot count the amount of times this has made me type the wrong thing

<img width="395" alt="image" src="https://github.com/user-attachments/assets/7b20e412-f332-4cb8-9072-71e0178f8e0c">

**Comment by Techatrix** [comment]
I believe your a looking for #1792.

This should have improved after efccfb7a3c993cba5918a5ce0cd75b83bff7883d:
![completion_order](https://github.com/user-attachments/assets/0db13a4f-fc87-4b2a-acef-9a843b144943)

**Comment by Techatrix** [comment]
fixed by #1955
