### ISSUE TITLE
Functions where the first parameter is of type `anytype` are treated as methods.

### ISSUE THREAD

**Issue by arrufat** [zigtools/zls#1978]
### Zig Version

0.14.0-dev.620+eab934814

### Zig Language Server Version

45eb38e2365c3f9fe7cee5a37a0f8d5c8645f888

### Client / Code Editor / Extensions

kakoune + kakoune-lsp

### Steps to Reproduce and Observed Behavior

I have set up [kakoune-lsp](https://github.com/kakoune-lsp/kakoune-lsp) to highlight functions and methods differently.
In particular, a method uses an italicized font.

Check this image:
![image](https://github.com/user-attachments/assets/686f8fca-a52f-497c-af30-5b3b9a1cd9ab)

You can see how the following functions are, correctly, not in italics:
- `@import`
- `pow`
- `main`
- `start`
- `print`

You can also see how the `read` method/member function from `Timer` is correctly italicized.
However, `lerp` from `std.math` is a normal function, whose signature is: `fn lerp(a: anytype, b: anytype, t: anytype) @TypeOf(a, b, t)`

Below the main function, I could recreate the issue by defining two functions. As you can see, the one that has `anytype` as the first parameter gets italicized.

### Expected Behavior

Functions who don't explicitly depend on self should not be treated as methods.

**Comment by Techatrix** [comment]
I don't know what exactly is meant by "Functions who don't explicitly depend on self" but I guess you just expect `shouldNotBeItalic` and `lerp` to not be highlighted as methods i.e. *italic*. #1979 should fix that

**Comment by arrufat** [comment]
Yes, that was poorly worded, I meant "the first parameter of type `@This()`".

I just tried #1979 and it works great, thank you!
