### ISSUE TITLE
No published artifacts for ZLS 0.14.0

### ISSUE THREAD

**Issue by Lynnesbian** [zigtools/zls#1988]
I have a small auto-updater that I've written for Zig and ZLS. It checks the relevant JSON files for the latest available version and downloads it for the host platform.

I've noticed that while Zig is able to be updated to the as yet unreleased 0.14 branch (specified as `master` in [this JSON file](https://ziglang.org/download/index.json)), there is no 0.14 branch available for ZLS. The JSON I've been checking is [this one](https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/index.json), which is linked to by the [ZLS wiki page on installation](https://github.com/zigtools/zls/wiki/Installation#latest-nightly). However, according to that file, the latest available version (specified by the `latest` field) is 0.13.0, and there are no 0.14-branch releases available under the `versions` field. Additionally, the direct link to the latest nightly for x86-64 Linux leads to [this file](https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/master/x86_64-linux/zls), which is a build of ZLS 0.13.0. Finally, the [GitHub releases page](https://github.com/zigtools/zls/releases) has no 0.14-branch releases.

**Comment by steeve** [comment]
It also seems the CI workflow is running properly: https://github.com/zigtools/zls/actions/runs/10424399882/job/28873117389

**Comment by nektro** [comment]
github releases has no 0.14 version because zig 0.14 is not released yet

**Comment by steeve** [comment]
@nektro i think OP is reffering to the nightlies, I know I am at least

**Comment by nektro** [comment]
I was responding to:

> Finally, the [GitHub releases page](https://github.com/zigtools/zls/releases) has no 0.14-branch releases.

**Comment by Techatrix** [comment]
You will find download links to nightly builds of ZLS in the [Install Page](https://zigtools.org/zls/install/). As for you auto-updater, you may find use in the new [release-worker](https://github.com/zigtools/release-worker) to query compatible ZLS versions. Please let me know if it covers your use case.

> Finally, the [GitHub releases page](https://github.com/zigtools/zls/releases) has no 0.14-branch releases.

GitHub releases only have tagged releases. No nightly builds. ZLS 0.14.0 will only be tagged when Zig 0.14.0 has been tagged.

**Comment by Lynnesbian** [comment]
Ah, alright. So if I have Zig version `x`, I just need to check `https://releases.zigtools.org/v1/zls/select-version?zig_version=x&compatibility=only-runtime`. Thanks!

**Comment by steeve** [comment]
> You will find download links to nightly builds of ZLS in the [Install Page](https://zigtools.org/zls/install/). As for you auto-updater, you may find use in the new [release-worker](https://github.com/zigtools/release-worker) to query compatible ZLS versions. Please let me know if it covers your use case.

this is amazing, great job!
