### ISSUE TITLE
No completion when dereferencing pointer from optional

### ISSUE THREAD

**Issue by RUSshy** [zigtools/zls#199]
With this code, ZLS is confused, and doesn't provide completion for the ``ptr.*.?.data`` despite it being valid code

```zig
const std = @import("std");

const Value = struct {
    data: i32 = 5
};
pub fn main() !void {

    var value: ?Value = null;
    value = Value{};
    var ptr = &value;

    std.debug.warn("{}\n", .{ptr.*.?.}); <----- no completion, it should offer 'data'
}
```

I am clueless about language parsers or LSP, but i guess something needs to handle optionals here: 

https://github.com/zigtools/zls/blob/bdcd2a1e85599882bc5522acd823f3976d725eab/src/analysis.zig#L422-L447

**Comment by alexnask** [comment]
Fixed in  5a88f2698018ac9970ac293968106f84a8462739
Thanks for reporting.
