### ISSUE TITLE
prebuilt osx binary on releases page does not work

### ISSUE THREAD

**Issue by dnwe** [zigtools/zls#200]
The prebuilt osx binary of zls available from the [0.1.0 release](https://github.com/zigtools/zls/releases/tag/0.1.0) doesn't run. I'm presuming that this is related to https://github.com/ziglang/zig/issues/3295

```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B29
```

```
$ zls
dyld: Symbol not found: __tlv_bootstrap
  Referenced from: /usr/local/bin/zls
  Expected in: /usr/local/bin/zls
 in /usr/local/bin/zls
```

Compiling from source on my own machine works fine

**Comment by clankill3r** [comment]
Same for me OSX 10.14.6

**Comment by alexnask** [comment]
Sorry about this, I did not test the MacOS executable properly in the last release.  
It will not happen again.

**Comment by nsadeh** [comment]
Hey @alexnask I am also running into this issue, is the only solution to build from source or is there a release planned with macOS support?

**Comment by tskj** [comment]
I've recently started experiencing the same issue. It worked a while ago, but now it doesn't work at all on Mac (11.3.1). Haven't tried building from source.

**Comment by tauraamui** [comment]
I had the same issue, I tried building from source but it seems like the latest lib def has changed/removed things.

**Comment by nektro** [comment]
ZLS is updated with Zig master. the proper use case is to build from source. future zig releases will have respective zls releases

**Comment by tauraamui** [comment]
Ok, well whatever version is released currently under brew (lemme check) 0.8.1, (I haven't time to check but I'd imagine that's already fairly out of date), but trying to build the latest master of `zls` with that results in the following:

<img width="679" alt="Screenshot 2021-12-03 at 10 51 22" src="https://user-images.githubusercontent.com/3159648/144590608-96838317-03b5-45cc-a784-eb6b31800baf.png">

**Comment by tauraamui** [comment]
I have to say it's not a great first impression, whilst I understand that yes things are in progress and subject to change, and the actual Zig README does warn against using the language for anything serious/for production. However I saw someone on Reddit before that claiming that Zig can be used today, whereas Jai cannot, although in my opinion I prefer the design ideas and choices of the Jai's apparent current implementation as I understand it, compared to Zigs, and, I'll let you know once I've joined the beta (started again November this year), but I very much doubt there'll be as much flux based disruption.

**Comment by nektro** [comment]
`brew install zig --HEAD`
