### ISSUE TITLE
`typeDefinition` goes to variables type annotation when provided instead of the types definition

### ISSUE THREAD

**Issue by xdBronch** [zigtools/zls#2020]
### Zig Version

0.14.0-dev.1407+0b9fccf50

### ZLS Version

0.14.0-dev.145+ace6f6d

### Steps to Reproduce and Observed Behavior

```zig
const S = struct {};
const A: S = S{};
const B = S{};
```
goto type definition on `A` takes you to its own type annotation while doing so on `B` takes you to the actual definition of `S`

### Expected Behavior

both should go to the definition of `S`

**Comment by srijan-paul** [comment]
PR #2046 should fix this :)
