### ISSUE TITLE
Add a nix binary cache to for ZLS

### ISSUE THREAD

**Issue by ethanholz** [zigtools/zls#2034]
Is there any way that we could potentially get a binary cache for the Nix build of ZLS? This would make installation much faster for those using Nix. From a CI perspective, this would require the setup of an action to install Nix, build ZLS, and then cache the derivations into something like cachix.

**Comment by Techatrix** [comment]
AFAIKT Cachix is unlikely to happen. ZLS provides prebuilt binaries (See https://github.com/zigtools/release-worker/) that need to be accessibly to non Nix users as well. Something similar to https://github.com/mitchellh/zig-overlay can be done to provide these binaries to Nix users.

On the topic of installation time for Nix, the [checkPhase](https://github.com/zigtools/zls/blob/4790cb1ab425ba97e82a22e909b4d42b37a5cb95/flake.nix#L32) could be skipped to save some time running the tests.

**Comment by ethanholz** [comment]
Doing something like https://github.com/mitchellh/zig-overlay was what I was going to attempt if an official binary cache is not an option. Thanks for the response and I will dig into using the prebuilt binaries!

**Comment by mocompute** [comment]
@ethanholz If you do such a thing, please share. I also had to disable checkPhase recently because of some error that kept occurring. And there's always a FileNotFound during build, but I haven't investigated.
