### ISSUE TITLE
zig build config fails

### ISSUE THREAD

**Issue by clankill3r** [zigtools/zls#204]
When I use the command `zig build config` I get the following output:

> Welcome to the ZLS configuration wizard! (insert mage emoji here)
> Looking for 'zig' in PATH...
> reached unreachable code
> C:\Program Files\zig\lib\zig\std\debug.zig:223:14: 0x7ff6cf621078 in std.debug.assert (build.obj)
>     if (!ok) unreachable; // assertion failure
>              ^
> C:\Program Files\zig\lib\zig\std\fs.zig:1969:11: 0x7ff6cf66075f in std.fs.openFileAbsolute (build.obj)
>     assert(path.isAbsolute(absolute_path));
>           ^
> C:\Users\clank\Desktop\zls\build.zig:38:49: 0x7ff6cf65aaa6 in .@build.config (build.obj)
>             const file = std.fs.openFileAbsolute(full_path, .{}) catch continue;
>                                                 ^
> C:\Program Files\zig\lib\zig\std\build.zig:2731:24: 0x7ff6cf64b4b1 in std.build.Step::std.build.Step.make (build.obj)
>         try self.makeFn(self);
>                        ^
> C:\Program Files\zig\lib\zig\std\build.zig:438:19: 0x7ff6cf64a227 in std.build.Builder::std.build.Builder.makeOneStep (build.obj)
>         try s.make();
>                   ^
> C:\Program Files\zig\lib\zig\std\build.zig:393:33: 0x7ff6cf63f55d in std.build.Builder::std.build.Builder.make (build.obj)
>             try self.makeOneStep(s);
>                                 ^
> C:\Program Files\zig\lib\zig\std\special\build_runner.zig:143:17: 0x7ff6cf624dd0 in main (build.obj)
>     builder.make(targets.items) catch |err| {
>                 ^
> C:\Program Files\zig\lib\zig\std\start.zig:174:65: 0x7ff6cf62212e in std.start.WinStartup (build.obj)
>     std.os.windows.kernel32.ExitProcess(initEventLoopAndCallMain());
>                                                                 ^
> Unable to dump stack trace: FileNotFound
> error: the following build command failed with exit code 2147483651:
> C:\Users\clank\Desktop\zls\zig-cache\o\7a9fa06ce8002e208424e22045e74bf8\build.exe C:\Program Files\zig\zig.exe C:\Users\clank\Desktop\zls C:\Users\clank\Desktop\zls\zig-cache C:\Users\clank\AppData\Local\zig config
> 

I first tried this with zig version 0.7.0+6294c1136, and since that did not work I updated to 0.7.1+b09045164, both give the same error.

**Comment by clankill3r** [comment]
This happens both when I use `git clone` or download the 0.1.0 release.

**Comment by clankill3r** [comment]
I thought it might had to do that my zig was located in Program Files, but this is not the case.

**Comment by g-w1** [comment]
Can you do this `echo %Path%` to see the path. I suspect something in your path is not an absolute path?

**Comment by g-w1** [comment]
Does adding this help? I think it will fix the issue?
```diff
diff --git a/build.zig b/build.zig
index 271a544..608d1af 100644
--- a/build.zig
+++ b/build.zig
@@ -34,6 +34,7 @@ pub fn config(step: *std.build.Step) anyerror!void {
             });
             defer allocator.free(full_path);

+            if (!std.fs.path.isAbsolute(full_path)) continue;
             // Skip folders named zig
             const file = std.fs.openFileAbsolute(full_path, .{}) catch continue;
             const stat = file.stat() catch continue;
```

**Comment by clankill3r** [comment]
The output of `echo %Path%`  is:

> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Doeke\Git\cmd;"C:\Users\clank\AppData\Local\Android\Sdk\tools;C:\Users\clank\AppData\Local\Android\Sdk\platform-tools";C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;C:\Program Files\dotnet\;C:\Program Files (x86)\ZeroTier\One\;C:\Program Files\Inkscape\bin;C:\Users\clank\Desktop\zig;C:\Program Files\nodejs\;C:\Users\clank\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\clank\AppData\Local\Programs\Python\Python37\;C:\Users\clank\AppData\Local\Microsoft\WindowsApps;C:\doeke\apps\VSCode\bin;C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\Users\clank\AppData\Roaming\npm

I will check your last post now.

**Comment by clankill3r** [comment]
Yes that works! Thank you so much!

**Comment by g-w1** [comment]
#206 closes this.
