### ISSUE TITLE
Wrong output characters due to color

### ISSUE THREAD

**Issue by clankill3r** [zigtools/zls#207]
Personally I don't care about this, but I report this in case someone does care.

If I use command prompt (cmd) I get the following output:

![zig_output_chars](https://user-images.githubusercontent.com/738650/102710120-6b7d8e80-42b0-11eb-9095-ad4a54c9bd30.png)

I then downloaded Cmder to compare:

![Cmder](https://user-images.githubusercontent.com/738650/102710133-8e0fa780-42b0-11eb-8468-b4cffd33a3c3.png)

So yeah, it's the color.

**Comment by InterplanetaryEngineer** [comment]
Looks like this would be fixed by using the lates version of zinput

**Comment by alexnask** [comment]
Fixed in df22d2490bcfe81bc026b878a1a942370803e213
