### ISSUE TITLE
Labeled switch lsp error when the code compiles (is valid)

### ISSUE THREAD

**Issue by andradei** [zigtools/zls#2075]
### Zig Version

0.14.0-dev.2162+3054486d1

### ZLS Version

0.13.0

### Client / Code Editor / Extensions

NVIM v0.10.2 with zls installed via mason

### Steps to Reproduce and Observed Behavior

Write the code below, taken from [ziglings exercise 108](https://codeberg.org/ziglings/exercises/src/branch/main/exercises/108_labeled_switch.zig#L63).

zls complains about labeled switch syntax:
![image](https://github.com/user-attachments/assets/32a8d002-3d3e-40c9-9f89-5d0609529aef)

### Expected Behavior

No errors since the code compiles and tests pass.

**Comment by leecannon** [comment]
Zig master needs zls master. Labelled switch has been introduced during the 0.14 dev cycle, so zls 0.13 has no support for it.
