### ISSUE TITLE
autofix removes extra line sometimes on pointless discard

### ISSUE THREAD

**Issue by travisstaloch** [zigtools/zls#2076]
### Zig Version

0.14.0-dev.2126+e27b4647d

### ZLS Version

0.14.0-dev.190+2451194

### Client / Code Editor / Extensions

sublime text stable build 4180

### Steps to Reproduce and Observed Behavior

here is the sequence of actions
```zig
fn debug(comptime fmt: []const u8, args: anytype) void {
    // std.debug.print(fmt ++ "\n", args);
}
```
ok - save file becomes
```zig
fn debug(comptime fmt: []const u8, args: anytype) void {
    _ = args; // autofix
    _ = fmt; // autofix
    // std.debug.print(fmt ++ "\n", args);
}
```
ok - uncomment
```zig
fn debug(comptime fmt: []const u8, args: anytype) void {
    _ = args; // autofix
    _ = fmt; // autofix
    std.debug.print(fmt ++ "\n", args);
}
```
oops - save becomes
```zig
fn debug(comptime fmt: []const u8, args: anytype) void {
    _ = args; // autofix
    _ = fmt; // autofix ++ "\n", args);
}
```

here the final line has been removed incorrectly. the removed length seems to be equal to the length of the last line

~/.config/zls.json

```json
{
    "enable_snippets": true,
    "enable_autofix": true,
    "enable_inlay_hints": false,
    "inlay_hints_show_parameter_name": false,
    "semantic_tokens": "full",
    "enable_build_on_save": true,
    "build_on_save_step": "check"
}
```

i notice that adding a newline after the last autofixed line produces a good result
```zig
fn debug(comptime fmt: []const u8, args: anytype) void {
    _ = args; // autofix
    _ = fmt; // autofix
    
    std.debug.print(fmt ++ "\n", args);
}
```
save
```zig
fn debug(comptime fmt: []const u8, args: anytype) void {
    std.debug.print(fmt ++ "\n", args);
}
```

### Expected Behavior

the pointless discards should be remove and result in
```zig
fn debug(comptime fmt: []const u8, args: anytype) void {
    std.debug.print(fmt ++ "\n", args);
}
```

**Comment by travisstaloch** [comment]
This doesn't seem to reproduce with vscode or with adding this test to `tests/lsp_features/code_actions.zig`
```zig
test "remove discard with trailing text" {
    try testAutofix(
        \\fn debug(comptime fmt: []const u8, args: anytype) void {
        \\    _ = args; // autofix
        \\    _ = fmt; // autofix
        \\    @import("std").debug.print(fmt ++ "\n", args);
        \\}
        \\
    ,
        \\fn debug(comptime fmt: []const u8, args: anytype) void {
        \\    @import("std").debug.print(fmt ++ "\n", args);
        \\}
        \\
    );
}
```
That makes me think this might be a sublime text bug.

**Comment by Techatrix** [comment]
I can confirm that this is a bug with [Sublime Text LSP](https://github.com/sublimelsp/LSP/). 

We start with the following source file:
```zig
const std = @import("std");

fn debug(comptime fmt: []const u8, args: anytype) void {
    _ = args; // autofix
    _ = fmt; // autofix
    std.debug.print(fmt ++ "\n", args);
}
```

Sublime Text applies the first code action:
```json
{
    "range": {
        "start": {
            "line": 2,
            "character": 56
        },
        "end": {
            "line": 3,
            "character": 24
        }
    },
    "newText": ""
}
```
This result in the following file:

```zig
const std = @import("std");

fn debug(comptime fmt: []const u8, args: anytype) void {
    _ = fmt; // autofix
    std.debug.print(fmt ++ "\n", args);
}
```

It then applies the second code action:
```
{
    "range": {
        "start": {
            "line": 3,
            "character": 24
        },
        "end": {
            "line": 4,
            "character": 23
        }
    },
    "newText": ""
}
```
Note that the "character" value of "start" is being "clamped" to the end of line.

This result in the corrupted source file:
```zig
const std = @import("std");

fn debug(comptime fmt: []const u8, args: anytype) void {
    _ = fmt; // autofix ++ "\n", args);
}
```

Sublime Text LSP needs to apply the code actions simultaniously. This behaviour can be easily noticed when using `Ctrl+Z` to undo the edit. The two code actions get undone individually.

Removing `source.fixAll` from `lsp_code_actions_on_save` to instead rely on `enable_autofix` can workaround the issue. I believe that this issue wasn't previously present until #2051 indirectly fixed `lsp_code_actions_on_save`.

**Comment by travisstaloch** [comment]
Thanks for the detailed feedback :+1:  I think I you're saying that fixing the first code action results in a second one with invalid ranges?  I can also see the actions getting undone individually w/ ctrl+z.

I think you're right.  I haven't noticed this issue until i pulled and rebuilt yesterday.

**Comment by Techatrix** [comment]
> I think I you're saying that fixing the first code action results in a second one with invalid ranges?

Yes. the code actions are meant to be applied to the "initial" document. Applying one of them modifies the document and invalidates the other code action's "range".

**Comment by travisstaloch** [comment]
And thanks for the sublime lsp link :pray:.  I just noticed that its a specific issue.

**Comment by travisstaloch** [comment]
Closing since this appears to be a sublime lsp bug.

**Comment by rchl** [comment]
I'm looking at the ST bug right now but I can't reproduce this anymore. It seems like zls now provides just a single code action. For this document:

```zig
const std = @import("std");

fn debug(comptime fmt: []const u8, args: anytype) void {
    _ = fmt; // autofix
    _ = args; // autofix
    std.debug.print(fmt ++ "\n", args);
}
```

I'm getting one code action with those changes:

```json
[
  {
    "edit": {
      "changes": {
        "file:///usr/local/workspace/zigtest/test.zig": [
          {
            "newText": "",
            "range": {
              "end": {
                "character": 24,
                "line": 4
              },
              "start": {
                "character": 23,
                "line": 3
              }
            }
          },
          {
            "newText": "",
            "range": {
              "end": {
                "character": 23,
                "line": 3
              },
              "start": {
                "character": 56,
                "line": 2
              }
            }
          }
        ]
      }
    },
    "kind": "source.fixAll",
    "title": "apply fixall"
  }
]
```

Has the behavior changed since this was reported?

**Comment by rchl** [comment]
I did find https://github.com/zigtools/zls/issues/2099 now so yes, this has changed in zls.
