### ISSUE TITLE
Two times a zls.exe and zls.json

### ISSUE THREAD

**Issue by clankill3r** [zigtools/zls#208]
Although the info given with `zig build config` states:

> You can find the ZLS executable in the "zig-cache/bin" by default.

For me there is both a `zig.exe` in `zls` and `zls/zig-cache/bin/zig.exe`.
They both differ in size and date. I think it would be more clear if only one existed cause this could be confusing, and people will eventually make mistakes targetting the wrong one.

**Comment by g-w1** [comment]
Could you give instructions on how to reproduce this? I do not see zig.exe in zig-cache/bin/?

**Comment by clankill3r** [comment]
@g-w1 I tried, I can't...

But I do only have zig.exe in zig-cache/bin/ so I wonder why you don't see it there.

**Comment by alexnask** [comment]
This should only be an issue if you cross compile zls for a windows and linux target.  
Please reopen if this is not the case, thanks.
