### ISSUE TITLE
Config option 'zig_exe_path': expected file path but

### ISSUE THREAD

**Issue by DendyGrobovshik** [zigtools/zls#2088]
### Zig Version

0.14.0-dev.2253+3a6a8b8aa

### ZLS Version

0.13.0

### Client / Code Editor / Extensions

vscode with Zig Language plugin

### Steps to Reproduce and Observed Behavior

Provide zig path to folder with zig compiler also named zig, like `/home/user/bin/zig/zig` in vscode 'Zig: Path'.
Then you'll get vscode warning `config option 'zig_exe_path': expected file path but`. 

🛠️ **Easiest way to fix it** is to rename folder with compiler.

### Expected Behavior

No warning if folder is named this way.

**Comment by Techatrix** [comment]
- Could you provide the [log output of ZLS](https://github.com/zigtools/zls/wiki/Guide:-How-to-view-ZLS-log-output)? 
- Did you add Zig or ZLS to your PATH?
- Did you perhaps add `/home/user/bin/` to your PATH?

This is most likely unrelated to your issue but your Zig and ZLS versions are not compatible. Please visit the [ZLS Installation Guide](https://zigtools.org/zls/install/) to install the appropriate ZLS version.

**Comment by Techatrix** [comment]
No response. Feel free to open a new issue with the requested information.
