### ISSUE TITLE
A way to disable/enable formatting for specific files, functions or just code blocks.

### ISSUE THREAD

**Issue by unorsk** [zigtools/zls#2091]
Having a common way to format code is really useful and nice!

But sometimes aligning code vertically makes it look more readable and clean. Like when I declare an array of structs. I am sure there are some other examples, but this is what made me wonder if I could keep some parts of my code retain the original formatting :)

The most obvious and straightforward way to do this technically might be just by adding some hints like: 
```
// zls formatter disable
// zls formatter enable
```

**Comment by Techatrix** [comment]
https://github.com/ziglang/zig/wiki/FAQ#how-do-i-make-zig-fmt-skip-a-range-of-source-lines

**Comment by unorsk** [comment]
omg. thanks!
