### ISSUE TITLE
Can't hide type hints

### ISSUE THREAD

**Issue by mf-in-mun** [zigtools/zls#2109]
### Zig Version

0.14.0-dev.2443+3f7b3daaa

### ZLS Version

0.14.0-dev, code downloaded and build on Dec. 13.

### Client / Code Editor / Extensions

VScode Version: 1.96.0 (system setup) 

### Steps to Reproduce and Observed Behavior

Just open a .ZIG-file in VScode.

![Screenshot 2024-12-13 102629](https://github.com/user-attachments/assets/f4a42233-0c57-4ee3-ad9b-c18f1ec59fcd)

You see the type hints which i can't hide.

### Expected Behavior

Sometimes these hints are really helpful, especially for beginners like me.

I tried to set and unset this parameter _"Inlay Hints Show Variable Type Hints"_ in the options:

![image](https://github.com/user-attachments/assets/2755e573-7c94-404b-bcf5-52a8a01465f3)

I'm expecting to activate respectively deactivate that parameter _"Inlay Hints Show Variable Type Hints"_ and switch on or off those hints.

### Relevant log output

```shell
---
```

**Comment by Vexu** [comment]
This is a bug in the vscode extension fixed in https://github.com/ziglang/vscode-zig/pull/257 but not yet released.
