### ISSUE TITLE
A normal comment after a doc comment breaks syntax highlighting

### ISSUE THREAD

**Issue by BinaryWarlock** [zigtools/zls#211]
```zig
/// foo
// bar
pub fn foo() void {
}
```

with ZLS for VSCode gives:
![image](https://user-images.githubusercontent.com/75403657/103447242-5e13bd00-4c3d-11eb-8d0b-1ac410e698a6.png)

**Comment by g-w1** [comment]
Does this also happen without zls?

**Comment by BinaryWarlock** [comment]
Yes, I used the Zig extension (vscode-zig) before switching to ZLS. I just disabled that and reloaded just to be sure it wasn't conflicting, and it still happens, it just highlights differently:

![image](https://user-images.githubusercontent.com/75403657/103495073-4cbde280-4dee-11eb-917b-c6bae08e9a64.png)

**Comment by alexnask** [comment]
There are a few bugs in the semantic highlighting, I keep a list, I will hopefully go through it soon :)
Thanks for reporting.

**Comment by alexnask** [comment]
This was fixed in the latest semantic highlighting upgrades.  
Thanks again for the report.
