### ISSUE TITLE
Bundle zls inside zig to make installation easier

### ISSUE THREAD

**Issue by vegerot** [zigtools/zls#2116]
- **Problem**: Currently, installing zls is [unintuitive](https://zigtools.org/zls/install/)
- **Reason**: This is because of the difficulty in matching the zls and zig versions
- **Solution**: Include zls inside zig, as `zig lsp`.

I noticed that zls isn't an official Zig project, which would mean we'd need to make this project official before bundling them together :)

**Comment by Techatrix** [comment]
Adopting ZLS into the Zig project would have far reaching consequences which have not been examined in this issue. The given reasoning is not enough. I also highly doubt that the Zig team has any interest in this and so do I.

If you don't want to go thorugh the ZLS install page, I would suggest a version management tool like [ZVM](https://github.com/tristanisham/zvm).

**Comment by mlugg** [comment]
I'd also like to note (to OP; Techatrix already knows this) that an LSP implementation is considered out of scope for a Zig Software Foundation project: we aren't in the business of tying the compiler into specific protocols like this where it can be avoided. See https://github.com/ziglang/zig/issues/615 for more context.
