### ISSUE TITLE
zls puts fastfetch's output at the beginning of a neovim buffer when opened and/or saved

### ISSUE THREAD

**Issue by YuvrajSinghGitbub** [zigtools/zls#2122]
### Zig Version

0.13.0

### ZLS Version

0.13.0

### Client / Code Editor / Extensions

NVIM v0.10.3 (astronvim) with zls installed with `mason`

### Steps to Reproduce and Observed Behavior

1. install `zls` from `mason`
2. open a zig file and write code
3. save the file

example output:
           .-------------------------:
          .+=========================.
         :++===++==================-       :++-
        :*++====+++++=============-        .==:
       -*+++=====+***++==========:
      =*++++========------------:
     =*+++++=====-                     ...
   .+*+++++=-===:                    .=+++=:
  :++++=====-==:                     -*****+
 :++========-=.                      .=+**+.
.+==========-.                          .
 :+++++++====-                                .--==-.
  :++==========.                             :+++++++:
   .-===========.                            =*****+*+
    .-===========:                           .+*****+:
      -=======++++:::::::::::::::::::::::::-:  .---:
       :======++++====+++******************=.
        :=====+++==========++++++++++++++*-
         .====++==============++++++++++*-
          .===+==================+++++++:
           .-=======================+++:
             ..........................[1G[21A[58Cyuvi@giogio
[58C-----------
[58COS: CachyOS Linux x86_64
[58CHost: HP Pavilion Gaming Laptop 15-ec0xxx
[58CKernel: Linux 6.12.6-2-cachyos
[58CUptime: 3 hours, 9 mins
[58CPackages: 1136 (pacman), 11 (flatpak)
[58CShell: fish 3.7.1
[58CDisplay (NCP0040): 1920x1080 @ 60 Hz in 15" [Built-in]
[58CWM: Hyprland (Wayland)
[58CTheme: Adwaita-dark [GTK2/3]
[58CIcons: Adwaita [GTK2/3]
[58CFont: Cantarell (11pt) [GTK2/3]
[58CCursor: Bibata-Modern-Classic (24px)
[58CTerminal: nvim
const std = @import("std");

### Expected Behavior

the expected behavior when opening a zig file in a nvim buffer is that it should have the either no code or if the file is generated by `zig init` to have the default code

**Comment by Techatrix** [comment]
I highly doubt that ZLS is running fastfetch and putting its output into your buffer. I would suggest to look into your neovim or terminal configuration.
