### ISSUE TITLE
Renamed identifier is not wrapped with `@""` when required

### ISSUE THREAD

**Issue by Vexu** [zigtools/zls#2124]
### Zig Version

0.14.0-dev.2548+0f17cbfc6

### ZLS Version

0.14.0-dev.325+8406f8c7

### Client / Code Editor / Extensions

VsCode 1.96.0

### Steps to Reproduce and Observed Behavior

```zig
// file.zig
const a_valid_name = 1;
```
Rename `a_valid_name` to `an invalid name`.
```zig
const an invalid name = 1;
```

This is especially annoying when using identifiers that shadow keywords or primitive values.
Workaround is to manually wrap the identifier with `@""` when renaming. 

### Expected Behavior

```zig
const @"an invalid name" = 1;
```

**Comment by nilskch** [comment]
I would like to take a stab at this.
