### ISSUE TITLE
Semantic Highlight: use standard semantic tokens/modifiers as much as possible

### ISSUE THREAD

**Issue by GrayJack** [zigtools/zls#220]
I want to propose some changes to the semantic highlight to use as much as possible the [standard semantic tokens/modifiers](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide), for better support in themes that only set up the standard ones.

## Change 1

For symbol declarations the modifier should be `declaration` instead of `definition`.

The standard semantic modifiers supported have both `declaration` and `definition` modifiers, with some difference:

declaration: For declarations of symbols.
definition: For definitions of symbols, e.g. in header files.

### Prior work
All other semantic highlighters I know also uses `declaration` for symbol declaration (rust-analyzer, pylance, Language Support for Java and TypeScript)

## Change 2

Change the `namespace` modifier to be a token. This change would improve the quality of zig code highlighted by themes that only define colors for the standard tokens/modifiers.

## Change 3

Change the name of `tagField` to `enumMember`. This change would improve the quality of zig code highlighted by themes that only define colors for the standard tokens/modifiers.

**Comment by alexnask** [comment]
I agree with Changes 1 and 3.  
I feel like `namespace` should stay a modifier, people should be able to play around with `type` and get highlighting for namespaces as well unless they specifically change thme imo.
