### ISSUE TITLE
Build fail: unable to find 'src/zinput/src/main.zig' (commit 6a66a7eb43)

### ISSUE THREAD

**Issue by Rogue-Ishtar** [zigtools/zls#223]
```[~/git/zls] zig build -Drelease-safe
./build.zig:5:16: error: unable to find 'src/zinput/src/main.zig'
const zinput = @import("src/zinput/src/main.zig");
               ^
./build.zig:52:28: note: referenced here
        zig_exe_path = try zinput.askString(builder.allocator, "What is the path to the 'zig' executable you would like to use?", 512);
                           ^
```

**Comment by Rogue-Ishtar** [comment]
I noticed [this comment](https://github.com/zigtools/zls/issues/222#issuecomment-761768601) on another build failure reported earlier today. At the risk of sounding clueless, what is a "master" version of zig? Anything pulled from master? The build failure I'm reporting happened with a pre-built 0.8.0 that I grabbed from the Zig website.

**Comment by SuperAuguste** [comment]
Hey @Rogue-Ishtar! I believe that the issue you're encountering is unrelated to Zig or ZLS, but rather a GitHub submodules issue. Try running `git submodule update --init --recursive` and rerunning `zig build`.

**Comment by Rogue-Ishtar** [comment]
I ran the submodule update as per your instructions. Now I no longer get the compilation error, but the build gets stuck with no message other than:
```[~/git/zls] zig build
Code generation... 
```
The zig process is taking up 2.5GB of physical memory (which is 90% on the machine I'm running it on). and churning at 20-40% CPU utilization. I'm guessing the zig compiler or zls needs more memory to proceed. I'm puzzled that it needs so much though.
