### ISSUE TITLE
Syntax highlighting not working in VS Code

### ISSUE THREAD

**Issue by cdwilson** [zigtools/zls#224]
I built `zls` from master (6a66a7eb433507e283f970551690dfdefdabed30) per instructions [here](https://github.com/zigtools/zls/wiki/Downloading-and-Building-ZLS) and I'm not seeing any syntax highlighting in VS Code.  First time user, just wondering if there's something else that needs to be configured to get this to work?

![image](https://user-images.githubusercontent.com/14631/105570890-d7647400-5d00-11eb-993c-a3612c44675d.png)

**Comment by g-w1** [comment]
Also install the zig extension.

**Comment by cdwilson** [comment]
Thanks, that worked (I didn't realize that zls didn't provide syntax highlighting by itself).
