### ISSUE TITLE
Prebuilt binaries

### ISSUE THREAD

**Issue by faraazahmad** [zigtools/zls#229]
I was trying to install zls, but I found that there aren't any prebuilt binaries for it (yet?). Is there a plan to provide prebuilt binary releases? because sometimes people just want to download and use it out of the box

**Comment by haze** [comment]
In what scenario are you using `zls` without `zig`?

**Comment by faraazahmad** [comment]
People just want to download and use. For example, rust-analyzer. I can just download and use it. I don't want to deal with building it and then configuring. In the end, it only helps zig and zls adoption

**Comment by InterplanetaryEngineer** [comment]
To enable this, the config wizard would need to be extracted form the build system and possibly made a subcommand of the executable.

**Comment by faraazahmad** [comment]
Sounds like a plan

**Comment by alexnask** [comment]
I will set up artifact uploads from CI
