### ISSUE TITLE
Package code completion seems to have died

### ISSUE THREAD

**Issue by prime31** [zigtools/zls#230]
Tested on macOS x64 and ARM.

I updated to zls master + zig master yesterday and it seems all code completion for any symbols in a package no longer works. I tried doing `zig run build_runner.zig --pkg-begin @build@ build.zig --pkg-end` that seems to print out a list of all the packages many times over. Any ideas which commit broke package support so I can roll back a bit? Thanks!

**Comment by alexnask** [comment]
Hi, I can't seem to reproduce this with zig master (zig version = `0.8.0-dev.1120+300ebbd56`).  
Maybe this is triggered by something in the build files, can you point me to one that breaks?  
(I tried it with the zls and gyro build files)

**Comment by prime31** [comment]
Sure thing. This repo exhibits the behavior: https://github.com/prime31/zig-upaya

The screenshots below (Code and Vim) shows completions received when typing "ig" which should have 100 or so Dear ImGui methods and types.

<img width="203" alt="Screen Shot 2021-02-05 at 9 00 36 AM" src="https://user-images.githubusercontent.com/60377/107064672-a2d8c980-6790-11eb-999c-68230c32e4b6.png">


<img width="200" alt="Screen Shot 2021-02-05 at 8 58 16 AM" src="https://user-images.githubusercontent.com/60377/107064537-77ee7580-6790-11eb-9ed7-e29b3f2e292d.png">

**Comment by prime31** [comment]
Update: seems macOS x64 is working but macOS arm is not. very odd...

**Comment by prime31** [comment]
Thanks to "definitely haze" this is now working. The issue was that some of my `build.zig` files which are used only for adding packages and c/c++ files had no `build() void` method. This seemed to cause ZLS to die quietly. Adding empty `build` methods seems to have fixed it on ARM.

Note that I still have no idea why it worked on x64 but failed on M1....
