### ISSUE TITLE
Need consistent stable or beta releases

### ISSUE THREAD

**Issue by fivemoreminix** [zigtools/zls#231]
I'm working on a feature for the VS Code extension that downloads and installs the latest version of ZLS. Problem is, if I wanted to use a release, I'd have to use a very specific version. A solution to this problem is tagging all stable releases "stable". And any beta releases "beta".

The releases should include source code snapshots (which I believe GitHub does automatically) as well as the most major precompiled binaries.

**Comment by fivemoreminix** [comment]
Edit: I'll consider myself crazy because I never saw the release IS tagged stable. But I still want to see releases being more frequent as this appears to be the only channel for stable releases.

**Comment by alexnask** [comment]
Sorry about, this, I was on a hiatus for a while.  
I will try to make releases more frequent, probably close to 1-2 releases per zig release cycle.
