### ISSUE TITLE
Prebuilt binary fails to start on Ubuntu 20.04.2 LTS 

### ISSUE THREAD

**Issue by corvideon** [zigtools/zls#234]
Hi folks

When I unzip and run the latest release, running `./zls` just results in the error below:

```
Content-Length: 106

{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":1,"message":"[err-default] AccessDenied"}} 
```

I thought it might be a path error, but I cannot find any workaround.
Any ideas?

Thanks

Seamus

**Comment by SuperAuguste** [comment]
Hey @corvideon, thanks for opening an issue! You're not supposed to run the zls binary directly; instead, give its path to an LSP client in your editor of choice. You can get that all set up quickly by heading over to https://github.com/zigtools/zls#vscode and scrolling down until you find your editor of choice.
