### ISSUE TITLE
Private declarations should show up in completions when not from imported types

### ISSUE THREAD

**Issue by Vexu** [zigtools/zls#24]
```zig
// b.zig
pub const foo = 1;
const bar = 2;
```
```zig
// a.zig
const b = @import("b.zig");
test "" {
    b. // only 'foo' should show up
}
```

**Comment by SuperAuguste** [comment]
I actually had this exact same thought 1 hour ago and fixed this in one of the recent commits, which should be pushed!

**Comment by Vexu** [comment]
Ah, I didn't notice. This is coming together so quickly. Works correctly after updating to master.

**Comment by Vexu** [comment]
Now the issue is that private declarations in the same file are not completed.
```zig
const foo  = struct {
    var a = 1;
    pub var b = 2;
};
test "" {
    foo. // only b shows up
}
```
Also `visib_token` can only ever be `pub` so we can just check `visib_token != null`.

**Comment by SuperAuguste** [comment]
Isn't this the correct behavior?

**Comment by Vexu** [comment]
> Isn't this the correct behavior?

No, `pub` is only needed when accessing declarations in different files.

**Comment by SuperAuguste** [comment]
This should now be fixed thanks to @alexnask's PR! Can you tell us if this is the intended behavior you expect? Thanks! 🎉

**Comment by Vexu** [comment]
Works as expected now.
