### ISSUE TITLE
container 'std.zig.ast.Node' has no member called 'Use'

### ISSUE THREAD

**Issue by thomastay** [zigtools/zls#242]
When running zig build -Drelease-safe, I get this error. I think it might be related to #238?

Here is my trace:
```
~\A\R\zls>zig build -Drelease-safe
.\src\analysis.zig:2039:28: error: container 'std.zig.ast.Node' has no member called 'Use'
    uses: []const *ast.Node.Use,
                           ^
.\src\analysis.zig:1986:5: note: while checking this field
    scopes: []Scope,
    ^
.\src\document_store.zig:26:5: note: while checking this field
    document_scope: analysis.DocumentScope,
    ^
C:\Users\**\AppData\Roaming\ziglang\lib\zig\std\hash_map.zig:293:13: note: while checking this field
            value: V,
            ^
C:\Users\**\AppData\Roaming\ziglang\lib\zig\std\hash_map.zig:357:40: note: referenced here
            pub fn next(it: *Iterator) ?*Entry {
                                       ^
.\src\document_store.zig:614:26: note: referenced here
    while (entry_iterator.next()) |entry| {
                         ^
.\src\analysis.zig:1540:34: error: container 'std.zig.ast.FnProto' has no member called 'ParamDecl'
    param_decl: *ast.Node.FnProto.ParamDecl,
                                 ^
~\A\R\zls[1]>zig version
0.8.0-dev.1427+0447a2c04
```

OS: Windows 10

**Comment by Luukdegram** [comment]
You'll need a master version of Zig that is atleast 1 commit older than https://github.com/ziglang/zig/pull/7920 to compile the current zls master. I hope to finish #238 soon that will make it work with latest Zig again.

**Comment by IvanTurgenev** [comment]
> You'll need a master version of Zig that is atleast 1 commit older than [ziglang/zig#7920](https://github.com/ziglang/zig/pull/7920) to compile the current zls master. I hope to finish #238 soon that will make it work with latest Zig again.

766b315b3888f0f9ac1ece69131cdf23f98b2c14

**Comment by snamber** [comment]
At hash `d9e46dceeca3f66b87e6b2e36415417495d2d2a0` the zig build works, and that version of zig can compile zls as well

**Comment by IvanTurgenev** [comment]
> @IvanTurgenev At hash `d9e46dceeca3f66b87e6b2e36415417495d2d2a0` the zig build works, and that version of zig can then compile zls as well

If using vscode change vscode semantic setting from configured by theme to true

**Comment by thomastay** [comment]
Thanks @Luukdegram for the fix!
