### ISSUE TITLE
zls + vim-lsp

### ISSUE THREAD

**Issue by mind-rot** [zigtools/zls#246]
Don't know if you support zls + vim-lsp, but i'm getting strange behavior.

When selecting autocompleted suggestion, say `mylib.selectedSuggestion`, after hitting any character, say `(` or `<tab>` or any other, the result will be change to `mylib.v:null`

Don't have this problem with gopls + vim-lsp.

**Comment by prabirshrestha** [comment]
Try updating to latest vim-lsp https://github.com/prabirshrestha/vim-lsp/pull/1093

**Comment by mind-rot** [comment]
@prabirshrestha updated. now getting empty string instead of `v:null` :(

**Comment by prabirshrestha** [comment]
Please try again. New PR got merged. https://github.com/prabirshrestha/vim-lsp/pull/1095

**Comment by mind-rot** [comment]
@prabirshrestha don't know what is the expected behavior, but it's bit different from `gopls`.
Now if i select from completion list, next keystroke will be ignore, where with `gopls` i continue typing as usual.

**Comment by prabirshrestha** [comment]
Can you comment on vim-lsp PR with repro step.

**Comment by rhysd** [comment]
@mind-rot Can you confirm your vim-lsp local repository contains changes from https://github.com/prabirshrestha/vim-lsp/pull/1095? If not, please fetch the plugin and try again. I think input would no longer be ignored.

**Comment by rhysd** [comment]
This should be fixed by https://github.com/prabirshrestha/vim-lsp/pull/1109.

**Comment by mind-rot** [comment]
@rhysd just checked, works as charm. Tanks a lot!!

btw, nice dog.
