### ISSUE TITLE
Functions defined directly as a field access of an import currently complete as variables

### ISSUE THREAD

**Issue by alexnask** [zigtools/zls#25]
Quick example:  
```zig
const std = @import("std");

pub fn main() void {
    std.ArrayLi // <- ArrayList completion is a variable, not a function
}

```

**Comment by Sergeeeek** [comment]
Hi, I'd like to work on this if no one is doing that yet :)

**Comment by SuperAuguste** [comment]
You can totally work on this one @Sergeeeek!

**Comment by Sergeeeek** [comment]
I think the real problem here is that imports should be resolved recursively.

That's how the `ArrayList` definition looks like in std.zig:

```zig
pub const ArrayList = @import("array_list.zig").ArrayList;
```

I guess analysis will need to support traversing multiple trees (a tree per file) and resolving types in that.

Still investigating what's the best way to do that. Maybe some data structure which could contain multiple trees and *somehow* have references between them.

Also might be related to this #26

**Comment by alexnask** [comment]
@Sergeeeek Imports are resolved recursively (e.g. try `sts.json.<whatever>`)  
The AnalysisContext contains the innermost import's tree and resolves import paths + builds the new tree in `onImport`.  

I don't think we need to store all the trees while traversing the imports (this is how I started coding it but I realized that we only need the latest tree since we will always complete from symbols in the innermost import).

**Comment by Sergeeeek** [comment]
Got it, feel free to reassign. I still want to try to figure it out though :)

**Comment by alexnask** [comment]
It's okay, I can work on another feature or general cleanup if you want to keep on working on this :D  
I will just give you my intuition on where things may be going wrong :)    
I was initially expecting this to work out of the box, since `resolveTypeOfNode` checks `InfixOp.Period` nodes, resolves the left part then asks for the child with the name from the rhs.  
I would probably start there and insert some warns to see what is going on (in case you don't know, all the warns are shown in the output log of the vscode extension, not 100% sure about other editors).  
This is also the case in #26 as you pointed out.  

Let me know if you have questions about the codebase.

**Comment by Sergeeeek** [comment]
Thank you, I'll try that

**Comment by alexnask** [comment]
I think something like this should fix this issue:  
When generating completions with `enable_snippets = true` if we are generating a VarDecl, resolve the type of the init expression.  
If it is a function type, generate a function completion instead, keeping the doc and label from the vardecl but generating the insert text with `analysis.getFunctionSnippet`

**Comment by Sergeeeek** [comment]
Yep, doing something like that.
There is one thing though, `resolveTypeOfNode` doesn't stop on function declarations, it tries to get the return type. I've added a function `resolveOriginalDeclaration` for now, which is similar to `resolveTypeOfNode`, but stops at function declarations.

Shoud I  change the behavior of `resolveTypeOfNode`? Maybe it should try to resolve the return type only when node *is* a function call, not when it's a function decl?

Here's the intermediate result for now:
![image](https://user-images.githubusercontent.com/3381399/82136222-f0cd2c00-9813-11ea-8d26-d2ac1762835c.png)

**Comment by Sergeeeek** [comment]
Is it possible that a pointer to a value in `HashMap` will become invalid/point to a different value when the `HashMap` changes? I fighting with a bug right now where `Handle` changes unexpectedly and that seems like the only explanation

**Comment by alexnask** [comment]
> Shoud I change the behavior of resolveTypeOfNode? Maybe it should try to resolve the return type only when node is a function call, not when it's a function decl?  

That sounds like a good change to me.  

> Is it possible that a pointer to a value in HashMap will become invalid/point to a different value when the HashMap changes? I fighting with a bug right now where Handle changes unexpectedly and that seems like the only explanation  

I don't think this is the case, will doublecheck soon.  
What can happen however is that the analysis context hits an import while analyzing and switches trees.  
That will cause all nodes from the tree and slices into the source to be invalidated.  
I tried implementing a quick fix yesterday and I hit this, we want to keep the base tree when generating the completions, however resolving the type of VarDecls will sometimes hit an import and invalidate this.  
This porbably requires some API changes to AnalysisContext to somehow notify it to keep the original tree around and not free it.

**Comment by Sergeeeek** [comment]
> What can happen however is that the analysis context hits an import while analyzing and switches trees.

For now I just create a new analysis context when analyzing each declaration. But sometimes, the `Handle` would change, and the initial context (where each declaration is iterated) would become different, it happened randomly.

I checked by comparing the context document uri on each iteration to the initial value. Pointer to the `Handle` was the same, but uri would randomly change and it would start looking at a different document.

Fixed this for now by calling `getHandle` each time with the initial document uri.

Function declaration aliases work now, across multiple files with imports:
![image](https://user-images.githubusercontent.com/3381399/82138315-38f64980-9828-11ea-964c-ec6118109597.png)

But now it doesn't complete anything else besides functions :rofl: I guess now that it uses `resolveTypeOfNode` for variable declarations, it will actually resolve to an actual type instead of VarDecl, which is not supported in `nodeToCompletion`

**Comment by alexnask** [comment]
Right, now that I think about it, the completion functions assume no documents are inserted into the document store while they are executing, since that could in fact invalidate the hande pointer.

**Comment by Sergeeeek** [comment]
I think changing document_store.handles to StringHashMap(*Handle) instead of StringHashMap(Handle) would fix this.

Also in my branch I end up jumping to different documents and therefore pasting them multiple times. What do you think about putting the *Tree right on the Handle to avoid that?

**Comment by alexnask** [comment]
@Sergeeeek  
We toyed with keeping the entire tree around early on, however it has a couple of drawbacks:  
- Quite memory intensive compared to the text  
- You also need to keep a copy of the source text used to parse the tree around  
Point number two is no longer an issue since we always get the tree from the latest text now.  

Keeping references to handles in the store would indeed fix this, I am quite reluctant to intentionally introduce fragmentation but making sure the references are stable is probably worth it.  

@Sergeeeek At the moment I would recommend you use the current sub optimal ways of dealing with this to try to restore the rest of the completions, stay within the scope of the issue and open a PR, I will discuss some of these changes with @SuperAuguste and introduce them as accepted.
