### ISSUE TITLE
Completion of builtin results in two `@` symbols

### ISSUE THREAD

**Issue by leecannon** [zigtools/zls#258]
After the recent (8d34232c7ad57e81f91038aacf5fe547c7bbfbe6) change typing an `@` then selecting a builtin completion results in two `@` symbols.

For example upon typing `const std = @` then selecting `@import` results in  `const std = @@import(comptime path: []u8)`

**Comment by alexnask** [comment]
Sorry about that, fixed in the latest commit.

**Comment by InterplanetaryEngineer** [comment]
On Sublime Text 3, the latest commit regresses to missing the @ sign on autocompletion. Why should it not be part of the completion? Isn't this an issue with your editor?

**Comment by alexnask** [comment]
Im not sure if the bug is on the client or server side.  
I would assume VSCode would follow the specs more closely than others (maybe this is a wrong assumption)  

Every client I've tried completes correctly only when I skip the `@` character.  
Maybe a configuration option makes sense here

**Comment by InterplanetaryEngineer** [comment]
Good idea, should I work on a PR?

**Comment by alexnask** [comment]
Sure, that would be good :)  
I will work on semantic highlighting bugs and any crashes I discover myself.
