### ISSUE TITLE
Why UTF-16 support?

### ISSUE THREAD

**Issue by InterplanetaryEngineer** [zigtools/zls#263]
I started working on #181 and saw that `offsets.documentPosition` and a few other places expect an `Encoding` parameter. This seems strange since Zig [only supports UTF-8](https://ziglang.org/documentation/master/#toc-Source-Encoding) encoding.

**Comment by alexnask** [comment]
LSP defines all offsets in the protocol as UTF16 codepoint offsets.  
Some servers do just send UTF-8 byte offsets instead, but that will result in errors, especially with the semantic highlighting in compliant clients.  

Instead, I also impelmented clangd's offsetEncoding LSP extension which was made specifically for clients and sevrers to negotiate and use UTF-8 byte offsets instead if they support them.
