### ISSUE TITLE
zig_exe_path is set incorrectly when using the snap version of Zig

### ISSUE THREAD

**Issue by fabioarnold** [zigtools/zls#265]
`zig build config` finds `/snap/bin/zig` from my `PATH` variable. This is a symlink: `/snap/bin/zig -> /usr/bin/snap`. This symlink is resolved using `std.os.realpath` in https://github.com/zigtools/zls/blob/3a8d4c7bfb5daeaec5ff55fa8cf39e7fe0f82f9d/build.zig#L47
Which results in zig_exe_path being set to `/usr/bin/snap`.

What is the reason for resolving a potential symlink? What other use case would it break to remove this resolution?

**Comment by g-w1** [comment]
A lot of users use symlinks to manage zig versions with eg: https://github.com/marler8997/zigup

**Comment by fabioarnold** [comment]
Does the the symlink need to be resolved in that case or would ZLS still work with the symlink set as `zig_exe_path`?
