### ISSUE TITLE
Enum and error completions broken

### ISSUE THREAD

**Issue by InterplanetaryEngineer** [zigtools/zls#266]
`makeScopeInternal` leaves `error_completions` empty and populates `enum_completions` with all kinds of globals.

**Comment by alexnask** [comment]
The error completions should be fix now (I will work on deduplications now)  
The enum_completions code seems right to me, Ill crack open some of my test files for zls to confirm.

**Comment by alexnask** [comment]
Should be fixed in 962327425d04d9cb9bdba242602b89d409c1271c
