### ISSUE TITLE
Detect self-parameters and skip the first argument in snippet completions

### ISSUE THREAD

**Issue by alexnask** [zigtools/zls#27]
For functions that have a first argument of `T`, `*T` or `*const T` where `T` is the type of the expression we are field accessing.

**Comment by pixelherodev** [comment]
Shouldn't this be done based on the call site, and not the function type?

**Comment by alexnask** [comment]
This should be based on a combination of both, the current implementation will skip the first agument when the container the first argument is of the same type as the container the function is defined in (or a pointer to it).  

Ideally we should only check this when we complete the function in a field access expression and the left hand side expression is not the type itself but an instance of the type.

**Comment by pixelherodev** [comment]
```
Ideally we should only check this when we complete the function in a field access expression and the left hand side expression is not the type itself but an instance of the type.
```
Yeah, that's what I was saying. (checking that it's an instance)

**Comment by alexnask** [comment]
This is an issue in pretty much all contexts atm, we complete the same for intances of a type as well as the type itself, I will address this soon ™️
