### ISSUE TITLE
Hover and go to definiton don't work at the beginning of the word with coc.nvim

### ISSUE THREAD

**Issue by AtomToast** [zigtools/zls#273]
I am using coc.nvim as an lsp client.
For a good while I was very confused why zls worked so inconsistently. Though now I noticed the pattern that if the cursor is positioned on the first character in a word it doesn't work.

This is something that happens very frequently as I like to move around with w and b. With other language servers like ccls for c or pyright for python I have no such issues with an otherwise identical setup.
Also I don't know if this behaves any different with nvim-lsp as I haven't set that up yet but I am plannig to.

**Comment by alexnask** [comment]
Thanks for reporting, I will be fixing this later today :)

**Comment by alexnask** [comment]
Fixed in 8cf6029f1acac5b49297188be5c0f390f6ae193d
