### ISSUE TITLE
zls.json in gitpod

### ISSUE THREAD

**Issue by markfirmware** [zigtools/zls#278]
The problem at hand is that I have zig-cache/bin/zls.json containing just {}, which I think is an empty json struct. The readme indicates that empty is ok if zig is in the PATH. Is that true? When I open a .zig file, the zls seems to start but indicates that it cannot find the zig exe nor the standard library.

Background:

I am working on getting zls to work in https://gitpod.io

My work is at branch gitpod at  https://github.com/markfirmware/zls/tree/gitpod

The url to start a gitpod workspace on that branch is https://gitpod.io/#https://github.com/markfirmware/zls/tree/gitpod

That branch has .gitpod.yml and .vscode/settings to install zig, install the vscode extension, and build zls itself. It calls tools/update-tools.sh to build zig master.

Usually I install both zig and zls using update-tools.sh inside say, https://github.com/markfirmware/zig-vector-table but it has not been working lately. That is why I decided to apply gitpod to the zls repo itself.

Regards,
Mark

**Comment by alexnask** [comment]
Hi, a zls.json file with `{}` should indeed work in that situation.  

Here is an exmaple session in vscode with with the zls debug log open:
![image](https://user-images.githubusercontent.com/265903/113275771-d09d4300-92e7-11eb-9d1f-c655396307e9.png)

Do you have access to the debug logs?  
It would be very helpful.

**Comment by markfirmware** [comment]
This morning I am getting a build error:

    zig version 0.8.0-dev.1676+070a28e49
    building zls
    ./src/semantic_tokens.zig:1111:31: error: expected optional type, found 'u32'
                if (array_type.ast.sentinel) |sentinel|
                                  ^
    ./src/semantic_tokens.zig:1111:13: note: referenced here
                if (array_type.ast.sentinel) |sentinel|
                ^
    zls...The following command exited with error code 1:
    /workspace/zls/tools/zig/zig build-exe /workspace/zls/src/main.zig --pkg-begin build_options /workspace/zls/zig-cache/zls_build_options.zig --pkg-end --cache-dir /workspace/zls/zig-cache --global-cache-dir /home/gitpod/.cache/zig --name zls --pkg-begin known-folders /workspace/zls/src/known-folders/known-folders.zig --pkg-end --enable-cache 
    error: the following build command failed with exit code 1:
    /workspace/zls/zig-cache/o/6792cb46346c325277e9c45c3ac09b83/build /workspace/zls/tools/zig/zig /workspace/zls /workspace/zls/zig-cache /home/gitpod/.cache/zig

**Comment by alexnask** [comment]
Ah, havent pulled from zig master yet, fixing this in a bit

**Comment by alexnask** [comment]
@markfirmware Should work now

**Comment by markfirmware** [comment]
[Info  - 11:25:19 AM] [info-main] No config file zls.json found.
[Info  - 11:25:19 AM] [info-main] ClientCapabilities{ .supports_snippets = true, .supports_semantic_tokens = true, .hover_supports_md = true, .completion_doc_supports_md = true }
[debug-main] Took 0ms to process method initialize
[debug-main] Took 0ms to process method initialized
[debug-doc_store] Opened document: file:///workspace/zls/src/analysis.zig
[debug-doc_store] Cannot resolve std library import, path is null.
[debug-doc_store] Cannot resolve std library import, path is null.
[debug-doc_store] Opened document: file:///workspace/zls/src/document_store.zig
[debug-doc_store] Cannot resolve std library import, path is null.
[debug-doc_store] Cannot resolve std library import, path is null.
[debug-doc_store] Cannot resolve std library import, path is null.
[debug-doc_store] Cannot resolve std library import, path is null.
[debug-doc_store] Cannot resolve std library import, path is null.
[debug-doc_store] Opened document: file:///workspace/zls/src/types.zig
[debug-doc_store] Cannot resolve std library import, path is null.
[debug-doc_store] Opened document: file:///workspace/zls/src/offsets.zig
[debug-doc_store] Cannot resolve std library import, path is null.
[debug-doc_store] Cannot resolve std library import, path is null.
[debug-doc_store] Cannot resolve std library import, path is null.
[debug-doc_store] Cannot resolve std library import, path is null.

**Comment by alexnask** [comment]
I see, we removed the executable directory zls.json option in favor of the local and global configuration directories (`~/.config`, `/etc/`) in one of the latest commits.  
The READMEs have not been updated accordingly, I apologize for that and will fix it shortly.  

I think the best option is to also support a `--config-path` option when launching zls to make it more flexible to use for this kind of application.

**Comment by alexnask** [comment]
That said, it looks like the zig executable path should have been located anyway if it was in PATH

**Comment by alexnask** [comment]
Can you try setting path using `gp env PATH=<...>`? (see https://www.gitpod.io/docs/environment-variables/, maybe PATH does not persist when vscode is called)

**Comment by markfirmware** [comment]
Imwill try that.

As it stands it seems I need zls.json in both ~/.config and in zig-cache/bin

**Comment by markfirmware** [comment]
gp env stores them in user settings which might be a work-around at best.

What line of code can I add to have zls echo the PATH to the log?

**Comment by markfirmware** [comment]
I definitely need  zls.json in both ~/.config and in zig-cache/bin

FYI gitpod persists /workspace (which in this case has the zls git clone) but does not yet persist $HOME - I update ~/.config when the workspace starts - https://github.com/markfirmware/zls/blob/3aa3b7c85698dd9d1a911198c45e2c91f8d86069/.gitpod.yml#L7-L12

**Comment by alexnask** [comment]
> I definitely need zls.json in both ~/.config and in zig-cache/bin  

I really don't see how this could be the case, on my own setup I only have a single zls.json file in `/etc/` and the code does not even try to get the executable directory anymore (https://github.com/zigtools/zls/blob/master/src/main.zig#L1723-L1739)  

As for the PATH debug print, you can add it in setup.zig:219, add `std.debug.print("PATH: {s}\n", .{env_path});`

**Comment by markfirmware** [comment]
> > I definitely need zls.json in both ~/.config and in zig-cache/bin
> 
> I really don't see how this could be the case, on my own setup I only have a single zls.json file in `/etc/` and the code does not even try to get the executable directory anymore (https://github.com/zigtools/zls/blob/master/src/main.zig#L1723-L1739)
> 

I will defer this anomaly for the time being. I will check the PATH next. If the PATH is not right, I will defer that and just put the zig path in the json to get a working reference case.

**Comment by markfirmware** [comment]
1. Copying zls.json to zig-cache/bin is not necessary.

2. The PATH does not contain zig. I will ask gitpod support for help on that.

3. I am having some bash quoting problems in producing my zls.json that has zig_exe_path. Once I can confirm that that works, I will be able to close this issue.

**Comment by alexnask** [comment]
Cheers.  
Let me know if I can help in any way on the zls side with any other issues, this looks like a cool project :)

**Comment by markfirmware** [comment]
> Cheers.
> Let me know if I can help in any way on the zls side with any other issues, this looks like a cool project :)

Thank you, and thank you for your help. I now have https://github.com/markfirmware/zig-gitpod-template that I will post in discord.
