### ISSUE TITLE
Unable to compile ZLS from source

### ISSUE THREAD

**Issue by Lauel09** [zigtools/zls#282]
Hi !
I tried to build ZLS from source, but it stops compiling due to some semantic errors.
I have linked the output.
Ubuntu 20.04.2 LTS ,64 bit
Linux Kernel - 5.8
[Bash Output](https://pastebin.pl/view/70f43b6f)

**Comment by GavinRay97** [comment]
Heya -- this is the same issue as this:
https://github.com/zigtools/zls/issues/279

It only builds if you've compiled the latest Zig master as of 24 hours ago apparently.
I would suggest doing a checkout on commit `df22d2490bcfe81bc026b878a1a942370803e213` (the one directly before it) and building from there maybe.

![image](https://user-images.githubusercontent.com/26604994/113424907-eae62800-939e-11eb-938a-d895d8cd3ad2.png)

**Comment by alexnask** [comment]
Hi, as pointed out zls currently can only be built using zig's master branch.  
Sorry for the inconvenience, I will make the CI upload build artifacts soon so you can grab zls without needing an up to date zig master build.

**Comment by Lauel09** [comment]
Thanks for the reply.My bad ,I  should have read `README.md` first.
