### ISSUE TITLE
update readme - I see, we removed the executable directory zls.json option in favor of exclusively the local and global configuration directories (`~/.config`, `/etc/`) in one of the latest commits.

### ISSUE THREAD

**Issue by markfirmware** [zigtools/zls#287]
I see, we removed the executable directory zls.json option in favor of exclusively the local and global configuration directories (`~/.config`, `/etc/`) in one of the latest commits.  
The READMEs have not been updated accordingly, I apologize for that and will fix it shortly.  

I think the best option is to also support a `--config-path` option when launching zls to make it more flexible to use for this kind of application.

_Originally posted by @alexnask in https://github.com/zigtools/zls/issues/278#issuecomment-811847043_

**Comment by markfirmware** [comment]
Also I think the readme is still out of date regarding the zls.json located next to the exe.

**Comment by markfirmware** [comment]
Oh I see you have another issue. Ok, thanks.

**Comment by alexnask** [comment]
@markfirmware 
Yes, this is fixed in the signature help PR (not the most elegant, but I was originally planning just to push the changes and they took a bit longer than expected).  
Sorry for the inconvenience.
