### ISSUE TITLE
Don't send snippets if the client doesn't ask for them

### ISSUE THREAD

**Issue by tadeokondrak** [zigtools/zls#29]
The editor I use doesn't really have great support for snippets, but other language servers don't send them since snippetSupport isn't set here: https://microsoft.github.io/language-server-protocol/specification#textDocument_completion.

This isn't really a high priority thing, but just once you get support for client capabilities, it would be nice :)

edit: wasn't aware there was already a config file!

**Comment by alexnask** [comment]
Closed in 52fe21b8bd2ea1482c7e79d2071bc7fefcca2cf3
