### ISSUE TITLE
Missing symbols in the MacOS build?

### ISSUE THREAD

**Issue by InterplanetaryEngineer** [zigtools/zls#291]
Mentioned in https://github.com/sublimelsp/LSP/issues/1634#issuecomment-813037711.

I do not have a Mac to try and reproduce this tho...

**Comment by ron-wolf** [comment]
I am able to reproduce. I get the same exact message, in fact:

<pre>
zig: dyld: Symbol not found: __tlv_bootstrap
zig:   Referenced from: /Users/Ron/.local/bin/zls
zig:   Expected in: /Users/Ron/.local/bin/zls
zig:  in /Users/Ron/.local/bin/zls
</pre>

**Comment by agbell** [comment]
I get this as well
```
[Info  - 11:12:40 AM] Connection to server got closed. Server will restart.
dyld: Symbol not found: __tlv_bootstrap
  Referenced from: /Users/adam/sandbox/zls/zls
  Expected in: /Users/adam/sandbox/zls/zls
 in /Users/adam/sandbox/zls/zls
[Info  - 11:12:40 AM] Connection to server got closed. Server will restart.
dyld: Symbol not found: __tlv_bootstrap
  Referenced from: /Users/adam/sandbox/zls/zls
  Expected in: /Users/adam/sandbox/zls/zls
 in /Users/adam/sandbox/zls/zls
[Error - 11:12:40 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by NduatiK** [comment]
Same issue. 

Building from source works well and because zig is so fast at compiling, its doable.

**Comment by alxiong** [comment]
same issue. (btw, I'm on a M1 chip)

Also tried building from source, got this: 
```
$ zig build -Drelease-safe
 build -Drelease-safe
./build.zig:12:26: error: no member named 'addOptions' in struct 'std.build.Builder'
    const exe_options = b.addOptions();
                         ^
/opt/homebrew/Cellar/zig/0.8.1/lib/zig/std/special/build_runner.zig:170:24: note: referenced here
        .ErrorUnion => try root.build(builder),
                       ^

$ zig version
0.8.1
```

**Comment by nektro** [comment]
did you build from source? what zig version are you on?

**Comment by andyfleming** [comment]
Building from `zls@master` with zig `0.9.0-dev.1352+6d6cf5984` appears to have worked. :+1:
