### ISSUE TITLE
crash when return type of a function pointer is missing

### ISSUE THREAD

**Issue by Hadron67** [zigtools/zls#298]
zls from `902c91e`. This causes the crash:
```zig
const h: fn();
```
Also affects variable and struct member. Noticed this in the log:
```
Segmentation fault at address 0x0
```

**Comment by InterplanetaryEngineer** [comment]
Cannot reproduce

**Comment by Hadron67** [comment]
Perhaps I'm missing something. Steps to reproduce:
* create file `test.zig`;
* input `const h: f();`
Note that it works fine and just shows syntax error if that semicolon is missing.

I'm using `zig-linux-x86_64-0.8.0-dev.1721+c9ffb6f73` on Ubuntu 20.04.

**Comment by alexnask** [comment]
Thanks for reporting, I have managed to reproduce this, on it :)

**Comment by alexnask** [comment]
Closed in 4b0d86f0bcac2efaae70a7788b0688e53392faf0
