### ISSUE TITLE
Don't send error field at all when there isn't an error

### ISSUE THREAD

**Issue by tadeokondrak** [zigtools/zls#30]
The LSP spec says that the error field shouldn't exist at all if there isn't an error (yeah, this is annoying). It seems the lsp_types rust crate marks it as an invalid message if it is set (to null in this case).

I've worked around it by just commenting out the line, since zls doesn't actually send any errors yet.

https://github.com/zigtools/zls/blob/8468207da31716d824397dbb292ce2da43ca670b/src/types.zig#L82

**Comment by SuperAuguste** [comment]
Good call! We'll also likely never send errors using JSON as we already have all the errors necessary encoded as strings! Thanks for your help @tadeokondrak!
