### ISSUE TITLE
Markdown highlighting of pointers unclear. Becomes bold

### ISSUE THREAD

**Issue by Himujjal** [zigtools/zls#302]
Editor: **neovim 0.5**
Plugins: **nvim-lspconfig**, **nvim-compe**

When on hover, pointers `*hello_ptr` renders as the start of a bold. And the pointer is simply not shown.

Maybe consider using `\\*`. If you are parsing from the source code, maybe replace `*` with `\*`.

**Comment by InterplanetaryEngineer** [comment]
Is the * part of the declaration or in a doc comment?

**Comment by Himujjal** [comment]
> Is the * part of the declaration or in a doc comment?

part of the declaration.

**Comment by InterplanetaryEngineer** [comment]
Can you show a screenshot of this? Zls normally wraps the declaration in \``` pairs, between which the rest of the Markdown syntax should be disabled. Could this be an error in the client side implementation? Could you share s screenshot?

**Comment by Himujjal** [comment]
Sorry for the delay. Here is the picture.

![image](https://user-images.githubusercontent.com/18563948/114164982-92d49600-9949-11eb-8387-7f6d70b1607d.png)

You can see that the method is declared as `fn valDeclaration(self: *Self) Stmt {`. The content after `*` becomes kind of bold on hover.

**Comment by InterplanetaryEngineer** [comment]
Does this occur in other editors too? I certainly haven't noticed it in Sublime Text. Should we add a config option to escape Markdown in declarations?

**Comment by Himujjal** [comment]
Its a neovim thing at the moment. Sure, you can do that. Just another observation from C:

![image](https://user-images.githubusercontent.com/18563948/114232844-22a23080-999a-11eb-989e-30f48f84a0cf.png)

**Comment by InterplanetaryEngineer** [comment]
Haven't really tried clangd yet, it seems kinda slow...

**Comment by Himujjal** [comment]
How is the hover text rendered in clangd in your editor (is what I meant to ask)? Can you post an image?

**Comment by WillLillis** [comment]
It looks like this can be closed, I can't reproduce this in NVIM v0.11.0-dev-1167+gf1748b78e3:

![image](https://github.com/user-attachments/assets/adf5ea4a-06d2-484f-8f17-9114a22df251)

FWIW regarding the difference with clangd, it looks like the difference is that zls renders this code in a single triple backtick block, whereas clangd uses single backticks in some places.

I didn't check too thoroughly, but it looks like proper support for markdown code blocks may have been added in [this PR](https://github.com/neovim/neovim/pull/25127), which came *way* after neovim 0.5.

**Comment by Techatrix** [comment]
Thank you for looking into this @WillLillis.
Out of curiosity. I installed ZLS 0.9.0 and neovim 0.5.0 with the `nvim-lspconfig` and `zig.vim` plugins from around the same time in April 2021 and was not able to reproduce the issue.
