### ISSUE TITLE
Top-level Doc Comments Are Not Supported

### ISSUE THREAD

**Issue by Leguu** [zigtools/zls#304]
In `Something.zig`:
```zig
//! top level comment

/// inner comment
a: i32
```

In `main.zig`:
```zig
const Something = @import("Something.zig");
pub fn main() void {
  const some = Something { .a = 2 }; // Something has no documentation
  some.a; // Has top level documentation and inner documentation 
}
```

Oddly enough, the hover info over `some.a` includes the top level comment and the inner comment. The expected output should be "inner comment" for `a` and "top level comment" for `Something`.

![Image](https://cdn.discordapp.com/attachments/768384829477355521/829786162800885800/20210408_14h33m27s_grim.png)

**Comment by InterplanetaryEngineer** [comment]
Will have a PR done tomorrow
