### ISSUE TITLE
zig exe path - for what is it needed?

### ISSUE THREAD

**Issue by markfirmware** [zigtools/zls#307]
Just for my understanding, is it just to get lib/std sources, or is it needed for more than that?

**Comment by alexnask** [comment]
The zig executable is used for three purposes:  
- Calling `zig env` to get the standard library path  
- Calling `zig fmt` to provide a formatter call for zls
- Using `zig run` with the custom build_runner to extract packages from build.zig file

Let me know if that clears it up :)
