### ISSUE TITLE
Are there going to be any changes from stage2?

### ISSUE THREAD

**Issue by markfirmware** [zigtools/zls#309]
Do you expect zls to keep its architecture for stage2? I have the impression that stage2 might be a compile server that receives code updates and returns new binary objects. In that case maybe what zls does might be built in to stage2.

**Comment by alexnask** [comment]
I'm currently working on a partial rewrite of zls that will follow the stage2 model closely (probably without the IR, but the samantic analysis will be very similar), along with a port of tree-sitter for an incremental, error resilient parsing.  
The goal is to figure out what extras we will need for the stage2 semantic server and if it will work well in practise (which it should).  

When a semantic server is released in stage2, zls will become a bridge between LSP and whatever protocol the compiler uses.  
I hope this answers your questions :)

**Comment by markfirmware** [comment]
Thanks for these and the other answers.
