### ISSUE TITLE
Centralize / deduplicate installation/configuration documentation

### ISSUE THREAD

**Issue by tau-dev** [zigtools/zls#315]
Installation instructions for various editors are currently reproduced in slightly different forms in the README.md, the config wizard, the GitHub wiki, and [the editor plugin](https://github.com/zigtools/zls-vscode). Failure to keep these in sync has been a cause of confusion for new users, as in #312, #295 and #222.
I propose we remove the editor specific installation instructions from the README (which is currently quite intimidating), keep short instructions in the config wizard, and further details in the wiki.

**Comment by SuperAuguste** [comment]
This is definitely something that needs to improve, especially as many people installing zls are new to programming in Zig or in general.

Removing installation instructions from the README and substituting them for a big button that takes you to an installation website of sorts where you just click on what you want could be a really useful addition. The config wizard is sadly seldom used and can be confusing for new users so this might the best option. :)

I'm down to work on improving the onboarding experience while #724 awaits landing.
