### ISSUE TITLE
[Feature Request] Type inference in editor

### ISSUE THREAD

**Issue by InfRandomness** [zigtools/zls#318]
Hi,
I think it would be a great idea to add a feature where zls / ZLS for VSCode could show the type inferred to certain variables like how rust-analyzer does it : 
![image](https://user-images.githubusercontent.com/43730933/117192124-a7d60500-ade1-11eb-9899-f090d9f3b42f.png)
(Notice the "i32")

**Comment by leecannon** [comment]
Implemented in #559

**Comment by Techatrix** [comment]
I think we should keep this issue open, because #559 only implements inlay hints for function call parameter names and not for these kinds of type hints.

**Comment by leecannon** [comment]
Sorry about that, your right I was getting ahead of myself :)
