### ISSUE TITLE
Align on field causes large number of errors

### ISSUE THREAD

**Issue by leecannon** [zigtools/zls#321]
The below code in a file results in ZLS emitting a large number of errors whenever you modify the file.

It seems to be caused by align specifically.

```zig
const S = struct {
    num: usize align(16),
};
```
Errors:
`[err-semantic_tokens] Moved backwards from Tag.integer_literal at position 164 to Tag.identifier at 152.`
`[err-semantic_tokens] Moved backwards from Tag.integer_literal at position 40 to Tag.identifier at 28.`
`[err-semantic_tokens] Moved backwards from Tag.integer_literal at position 50 to Tag.identifier at 38.`

**Comment by alexnask** [comment]
Closed in 5631b8d202637e7376c8b253e3369dc41f684ee4
