### ISSUE TITLE
Semantic token error makes VSCode unusable

### ISSUE THREAD

**Issue by Jarred-Sumner** [zigtools/zls#332]
The alert seems to pop up in an infinite loop, causing CPU usage to spike and the editor to eventually hang

Video:

https://user-images.githubusercontent.com/709451/119237485-e95cf480-baf1-11eb-9791-e79a474ce687.mov

For now, I've disabled it manually by commenting out the log:
```zig
        if (next_start < self.previous_position) {
            // log.err(
            //     "Moved backwards from {} at position {} to {} at {}.",
            //     .{ tags[self.previous_token orelse 0], self.previous_position, tags[token], next_start },
            // );
            return;
        }
```

**Comment by bradms** [comment]
This bug also happens when using the `continue` keyword for me.
