### ISSUE TITLE
zls config not recognized

### ISSUE THREAD

**Issue by adnan449** [zigtools/zls#337]
I'm trying to set up zls for VS Code. I have zls installed in my path:
```
$ which zls
/home/***/zls/zls
```

The extension was not able to detect it, I manually added the path to zls but then it warns that 

>[warn-main] Zig standard library path not specified in zls.json and could not be resolved from the zig executable

I referred back to the README and it suggests to use `zls config`. However it's not working:

```
***@pop-os:~/zigbed$ zls config
Unrecognized argument config***@pop-os:~/zigbed$
```

(Also note the lack of a newline character in the message there).

I cannot print the version either as it spits out the same error. 

My zls folder:

```$ tree ~/zls
/home/***/zls
├── build_runner.zig
├── LICENSE.md
├── README.md
├── zls
└── zls.json
```
```
$ cat ~/zls/zls.json 
{
    "enable_snippets": false,
    "warn_style": false,
    "enable_semantic_tokens": false,
    "operator_completions": true
}
```

**Comment by 222464** [comment]
I have the same issue!

**Comment by Luukdegram** [comment]
`zls config` only works on the later version of `zls`. If you downloaded the binary from the tagged release, it is too old to support this. You can obtain the latest version of zls by either building it from source manually, or downloading a binary from the CI artifacts right here: https://github.com/zigtools/zls/actions -> Open latest run -> Click "builds" at the bottom of the page.

**Comment by adnan449** [comment]
Okay, I'm closing this under the assumption that future tag releases will fix this issue.
