### ISSUE TITLE
Can't compile ZLS

### ISSUE THREAD

**Issue by Quentincestino** [zigtools/zls#356]
Hello,
When I try to compile ZLS, it fails on:
``` ./build.zig:18:59: error: no member named 'path' in '[]const u8'
    exe.addPackage(.{ .name = "known-folders", .path = .{ .path = "src/known-folders/known-folders.zig" } });
                                                          ^
/usr/lib/zig/std/special/build_runner.zig:158:24: note: referenced here
        .ErrorUnion => try root.build(builder), ```


Can someone help me to fix it ?

**Comment by leecannon** [comment]
This is due to ZLS tracking zig master (although has not been able to build against master for a few days pending https://github.com/zigtools/zls/pull/355)

If you want to stay on zig 0.8.0 see https://github.com/zigtools/zls/issues/347#issuecomment-872106344

**Comment by JornVeken** [comment]
I figured out a fix for this,
Replace `.path = .{ .path = "src/known-folders/known-folders.zig" } ` with `.path = "src/known-folders/known-folders.zig"` in the build.zig file. You will get another (identical) error from another line in build.zig. Which you can fix the exact same way.
