### ISSUE TITLE
Large delay( or crash on safety enabled builds ) in sublime text 

### ISSUE THREAD

**Issue by JonSnowbd** [zigtools/zls#368]
https://user-images.githubusercontent.com/4250341/127779023-7ea827f2-0427-4e4a-b709-86971c73ca53.mp4

Sublime text 4, windows 10, latest main branch ZLS and Zig, ZLS config was ran to set it for Sublime

Has this delay which is per import file, per session, on anything that isn't from the standard lib. 

When ZLS was built in debug or anything with safety, it was instead a zig crash with an error code `zig exited with status code 2147483651`

Works fast and snappy on VSC

edit: Looking closer, its actually per import file, per tab. closing a tab and reopening the file causes the delay per import again.

**Comment by SuperAuguste** [comment]
Wow we're late to the party on this one 😅

Is this still happening @JonSnowbd?

**Comment by JonSnowbd** [comment]
That was basically the day I tried ST4 and it didn't go well so I've not used it since, but works fine now testing on a fresh ST4 install, thanks for the follow-up.
