### ISSUE TITLE
zls doesn't start. I don't know if this is an issue.

### ISSUE THREAD

**Issue by guijun** [zigtools/zls#374]
:CocConfig
{
   "languageserver": {
       "zig" : {
           "enable":true,
           "command": "/Users/kin/zig/zls/zig-out/bin/zls",
           "filetypes": ["zig"]
       }
   }
}
restart nvim
e hello.zig

no syntex highlight, no auto competion.
no process found in "ps axf"

**Comment by Avokadoen** [comment]
Had the same issue with unknown version after updating Zig. Tried building latest version and everything seems to work for me

**Comment by paulstelian97** [comment]
Does #200 apply?

**Comment by nektro** [comment]
what editor/os/arch is this happening on?

**Comment by SuperAuguste** [comment]
Stale, please reopen if this persists / with more details :)
