### ISSUE TITLE
crashes in Emacs

### ISSUE THREAD

**Issue by q60** [zigtools/zls#384]
it seems to crash just randomly in Emacs

![image](https://user-images.githubusercontent.com/61933599/131253704-3a444022-766b-47d5-8f86-3c0cdf27147d.png)

**Comment by q60** [comment]
there's another type of crash when emacs suggests to restart LS

**Comment by q60** [comment]
> there's another type of crash when emacs suggests to restart LS

![image](https://user-images.githubusercontent.com/61933599/131307221-7db2fada-487b-4828-bdd7-f7b1081ff675.png)

can be reproduced going straight down in the file hitting end of the buffer

stderr: https://gist.github.com/q60/f5e1a80e7d2e0c2640a1c5b61eca127d

**Comment by q60** [comment]
> > there's another type of crash when emacs suggests to restart LS
> 
> ![image](https://user-images.githubusercontent.com/61933599/131307221-7db2fada-487b-4828-bdd7-f7b1081ff675.png)
> 
> can be reproduced going straight down in a file hitting end of the buffer
> 
> stderr: https://gist.github.com/q60/f5e1a80e7d2e0c2640a1c5b61eca127d

such crashes also happen in background if i wait just several minutes

**Comment by wilsonk** [comment]
I don't get the random crashes with Emacs/Spacemacs-27.2, but I do get the crash when I use the down key and hit the end of a buffer (and then I usually have to hit the down key several times to get the server to crash). 

It seems to be only on certain zig files though. Here is my zls::stderr output...hopefully it helps:

```
/home/wilsonk/Downloads/zls/src/types.zig:138:37: 0x34db4e in types.TextDocument.borrowNullTerminatedSlice (zls)
        const popped_char = self.mem[end_idx];
                                    ^
/home/wilsonk/Downloads/zls/src/analysis.zig:1532:59: 0x2c5ffe in analysis.documentPositionContext (zls)
        var held_line = document.borrowNullTerminatedSlice(
                                                          ^
/home/wilsonk/Downloads/zls/src/main.zig:1551:65: 0x2b3d10 in hoverHandler (zls)
        const pos_context = try analysis.documentPositionContext(arena, handle.document, doc_position);
                                                                ^
/home/wilsonk/Downloads/zls/src/main.zig:1719:53: 0x293c10 in processJsonRpc (zls)
                    done = extractErr(method_info[2](arena, id, request_obj, config));
                                                    ^
/home/wilsonk/Downloads/zls/src/main.zig:1962:27: 0x286224 in main (zls)
        try processJsonRpc(&arena, &json_parser, buf, config);
                          ^
/home/wilsonk/Downloads/zig/build/lib/zig/std/start.zig:510:37: 0x27ccda in std.start.callMain (zls)
            const result = root.main() catch |err| {
                                    ^
/home/wilsonk/Downloads/zig/build/lib/zig/std/start.zig:452:12: 0x260cbe in std.start.callMainWithArgs (zls)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/home/wilsonk/Downloads/zig/build/lib/zig/std/start.zig:366:17: 0x25fce6 in std.start.posixCallMainAndExit (zls)
    std.os.exit(@call(.{ .modifier = .always_inline }, callMainWithArgs, .{ argc, argv, envp }));
                ^
/home/wilsonk/Downloads/zig/build/lib/zig/std/start.zig:279:5: 0x25faf2 in std.start._start (zls)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});


```

**Comment by jtepe** [comment]
That second crash also happens for me.

If it helps, I can reproduce it reliably with the default `main.zig` from `zig init-exe`.

Running on Linux.

My `zls` config is
```json
{
  "zig_exe_path": "<REDACTED>",
  "enable_snippets": true,
  "warn_style": true,
  "enable_semantic_tokens": true,
  "operator_completions": true,
  "include_at_in_builtins": false,
  "max_detail_length": 1048576
}
```

**Comment by q60** [comment]
> This seems to have been fixed for me (hitting the bottom of a file and zls crashing in emacs-27.2) as of Oct 26, 2021 after commit [80f0983](https://github.com/zigtools/zls/commit/80f09831bc4be779af8a1bf8fadda1357faa302e). Just so people know. Not sure about the other error that @q60 discussed above.

yeah it's fixed
