### ISSUE TITLE
Issues compiling with zig@`05cf44933d753f7a5a53ab289ea60fd43761de57`

### ISSUE THREAD

**Issue by InfRandomness** [zigtools/zls#386]
A new [commit has just been pushed](https://github.com/ziglang/zig/commit/05cf44933d753f7a5a53ab289ea60fd43761de57),
This commit removes the `true, false, undefined, null` keywords.

This causes compilation errors when building zls @ https://github.com/zigtools/zls/blob/master/src/semantic_tokens.zig#L104-L130, https://github.com/zigtools/zls/blob/master/src/analysis.zig#L668-L690,
https://github.com/zigtools/zls/blob/master/src/analysis.zig#L1659-L1802,
https://github.com/zigtools/zls/blob/master/src/analysis.zig#L3228-L3231, 
https://github.com/zigtools/zls/blob/master/src/semantic_tokens.zig#L773-L777 and some other places. It seems as if Zls tries to switch onto now inexistant enum members for the most part.

**Comment by SuperAuguste** [comment]
Should be fixed by Lee Cannon's #385!
