### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by haffla** [zigtools/zls#391]
Hi,

I am trying to build zls following the [instructions](https://github.com/zigtools/zls#from-source) in the README.

My zig version is `0.9.0-dev.927+eb5e4ac49`.

But the build step fails with

```bash
/Users/.../zls/src/main.zig:953:21: error: use of undeclared identifier 'ast'
fn hasComment(tree: ast.Tree, start_token: ast.TokenIndex, end_token: ast.TokenIndex) bool {
```

Any idea?

(New to zig... Trying to make my editor work with zig first)

**Comment by maxxnino** [comment]
You can download the build binary in the CI
https://github.com/zigtools/zls/actions/runs/1199878231

**Comment by paulstelian97** [comment]
I also have the same error. macOS 11.5.2.

**Comment by Sashiri** [comment]
Hi, it's caused by recent changes to Zig
For now you can switch to #392, if you need/want to compile with the newest version of zig, at least till some changes land on master ;D

**Comment by cincodenada** [comment]
To pull in Sashiri's changes from #392, you can do the following:
```
git remote add Sashiri https://github.com/Sashiri/zls
git pull Sashiri master
```
Or, in one step if you don't care to add another origin:
```
git pull https://github.com/Sashiri/zls master
```

**Comment by Sashiri** [comment]
#392 was merged

**Comment by haffla** [comment]
> #392 was merged

Yep built succeeds now! Thx
