### ISSUE TITLE
Building from Zig master results in compile error: missing field: 'addrspace_node'

### ISSUE THREAD

**Issue by japhib** [zigtools/zls#395]
Hi,

I cloned ZLS and downloaded the latest version of Zig master. Trying to compile ZLS from source resulted in the following compile error:

```
$ ../zig-macos-x86_64-0.9.0-dev/zig build -Drelease-safe

./src/ast.zig:65:31: error: missing field: 'addrspace_node'
    return fullPtrType(tree, .{
                              ^
./src/ast.zig:91:31: error: missing field: 'addrspace_node'
    return fullPtrType(tree, .{
                              ^
./src/ast.zig:105:31: error: missing field: 'addrspace_node'
    return fullPtrType(tree, .{
                              ^
./src/ast.zig:78:31: error: missing field: 'addrspace_node'
    return fullPtrType(tree, .{
                              ^
```

I was able to get it to compile by just going in and adding `.addrspace_node = 0` to each of the error locations. I have no idea if that's the right thing to do, so I'm not going to submit a PR.

This is on MacOS with the Zig compiler named `zig-macos-x86_64-0.9.0-dev.1133+d722f0cc6.tar.xz` from the main Zig downloads page.

**Comment by xpyxel** [comment]
This was fixed.
