### ISSUE TITLE
Can't rename struct property

### ISSUE THREAD

**Issue by dmbfm** [zigtools/zls#398]
When I try to rename the property of a struct nothing happens. 

https://user-images.githubusercontent.com/8743306/135007174-d9783621-a3c7-404b-8d52-db9dd51900a2.mov

I'm using neovim with lsp, and compiled zls from HEAD two days ago.

I'm quite new to Zig and zls, so I'm not sure if this is a bug or just a current limitation of zls.

**Comment by nektro** [comment]
if you highlight the field name is the behavior any different?

**Comment by nektro** [comment]
also potentially relevant: https://microsoft.github.io/language-server-protocol/specification#textDocument_rename

**Comment by dmbfm** [comment]
> if you highlight the field name is the behavior any different?

Not really. I don't think highlighting symbols in neovim would make any difference.

**Comment by Jarred-Sumner** [comment]
can confirm this is not working yet

<img width="1874" alt="image" src="https://user-images.githubusercontent.com/709451/209906460-e62c623a-49b7-4bab-af8c-5c3ae075a55a.png">

**Comment by Techatrix** [comment]
renaming struct fields appears to be working since 8b989e96afd5a3c669e2386810daf8719a1859c6 (see #1565)
There are probably many situation where it is still borked but those should be handled as new issue since the give example is working.
