### ISSUE TITLE
provide autocomplete for `@import("builtin");`

### ISSUE THREAD

**Issue by nektro** [zigtools/zls#401]
this can be done by saving a local copy of the output of `zig build-exe --show-builtin`

the individual values will be different per target but will make exploration of the fields much easier

**Comment by leecannon** [comment]
Just to note, a way of providing a builtin.zig per project was added in #344.
Using the native builtin as the fallback when that path is not provided makes alot of sense .

**Comment by nektro** [comment]
thanks for the tip! this will help a ton :)
