### ISSUE TITLE
recognize `@import` as a place for a path

### ISSUE THREAD

**Issue by nektro** [zigtools/zls#402]
reference for javascript support inside VS Code

![image](https://user-images.githubusercontent.com/5464072/135707291-dd286ed0-812c-4ffd-ad75-8097dd3d76f0.png)

**Comment by SuperAuguste** [comment]
This is not standardized by the Language Server Protocol as far as I know so it'll require a little more work; I'll start exploring! :)

**Comment by SuperAuguste** [comment]
![image](https://user-images.githubusercontent.com/19855629/178098802-005d9392-26fe-4382-9dbd-6ef953eaede8.png)

Hope this is what you wanted! :)
