### ISSUE TITLE
Package Windows releases as Zip, not TAR

### ISSUE THREAD

**Issue by Bellarmine-Head** [zigtools/zls#407]
`.tar.xz` is an uncommon format on Windows machines.  To extract a TAR on Windows, I usually install a program I don't want on my system - e.g. WinZip or File Viewer Plus - use it and then uninstall it.  These programs are a pain in that they hijack all my file associations, change their icons, they put up nag screens all the time etc.

(I have just found a `tar.exe` file on my system, but this isn't something most Windows users know about.  The common format for this type of thing on Windows is .zip, and Zip support is integrated deeply and is very easy to use.)

Please package the ZLS release for Windows as a Zip, which is what Ziglang itself does, as you can see here:- https://ziglang.org/download/

Thanks.

**Comment by rayray** [comment]
Just want to +1. While 7Zip worked for me, I had to do two extractions, one for xz, one for the tar, which is odd.

**Comment by Techatrix** [comment]
the latest ZLS 0.11.0 release now ships .zip files for windows
