### ISSUE TITLE
zls cannot locate zls.json file

### ISSUE THREAD

**Issue by palash25** [zigtools/zls#410]
hi, i was installing zls on a new machine and noticed this problem. this is what I did

built zls from source and than ran the configuration wizard. The config wizard successfully wrote the config to `/etc/zls.json`

after that I copied the zls binary that was built in zls-out directory to `/usr/local/bin`

then i installed the vscode extension for zls and set the following option in settings

```
"zigLanguageClient.path": "/usr/local/bin/zls"

```

and restarted zls from vscode and I get this in the logs

```
[info-main] No config file zls.json found.
[info-main] Server closing.
```

does zls not look for the config in the `/etc` directory?

**Comment by leecannon** [comment]
zls uses https://github.com/ziglibs/known-folders to fetch locations for configuration.

below is the code that checks both the local configuration and global configuration folders for the file
https://github.com/zigtools/zls/blob/80f09831bc4be779af8a1bf8fadda1357faa302e/src/main.zig#L1701-L1726

looking at known-folders shows global config to be defined as
```zig
.global_configuration = XdgFolderSpec{ .env = .{ .name = "XDG_CONFIG_DIRS", .user_dir = false, .suffix = null }, .default = "/etc" },
```

so unless you have the XDG_CONFIG_DIRS environment variable set to something it should default to /etc

**Comment by palash25** [comment]
hey thanks for the quick response, i see the env var you mentioned is indeed set, so if I understand correctly if this env var is unset zls will look for the config in `/etc/` ?


```
echo $XDG_CONFIG_DIRS
/etc/xdg/xdg-pop:/etc/xdg

```

**Comment by leecannon** [comment]
Yea looking at known-folders's code it will check for the the environment variable and if not found will fallback to the default, in the case of global configuration they have the env variable as `XDG_CONFIG_DIRS` and the default as `/etc`

I dont know enough about XDG to know if that is correct, if you dont think it is quite right raise an issue over there.
