### ISSUE TITLE
[BUG]: Building ZLS on Windows 10 machine fails

### ISSUE THREAD

**Issue by gp-97** [zigtools/zls#417]
**OS :** Microsoft Windows [Version 10.0.19043.1348]
**Zig Version :** 0.8.1
**ZLS build branch:** master

Following the steps as mentioned on [Downloading and Building ZLS](https://github.com/zigtools/zls/wiki/Downloading-and-Building-ZLS#cloning-with-git) results in this error:
```zsh
~> /g/Zig/zls> zig build -Drelease-safe
.\build.zig:10:26: error: no member named 'addOptions' in struct 'std.build.Builder'
    const exe_options = b.addOptions();
                         ^
G:\Zig\zig-windows-x86_64-0.8.1\lib\std\special\build_runner.zig:170:24: note: referenced here
        .ErrorUnion => try root.build(builder),
```

**Comment by leecannon** [comment]
zls master tracks zig master. The build option functionality changed in [this](https://github.com/ziglang/zig/commit/311797f68619f3de66cbdecabc2af7d2022e8874) commit.

**Comment by gp-97** [comment]
How to solve this issue?

**Comment by leecannon** [comment]
Either use an old commit of zls (5ddb92b8658e5e473bf5cc88083e55152880b28d is the commit just before the build option change).

Or use zig master (https://github.com/marler8997/zigup is like rustup and makes getting the latest master as easy as `zigup master`).
