### ISSUE TITLE
Doc-comments don't show up in on-hover box for inline functions

### ISSUE THREAD

**Issue by InKryption** [zigtools/zls#424]
When you hover the mouse over a symbol, a box pops up to display extra information about the declaration of that symbol, e.g. the doc-comment above it. But if that symbol happens to be an inline function, the box doesn't include the doc-comment. 

Context:
Using VSCode, on a Windows 10 machine.

**Comment by SuperAuguste** [comment]
This seems to be fixed; please reopen if the issue persists :)
