### ISSUE TITLE
Either update the releases, or stop recommending that people use them.

### ISSUE THREAD

**Issue by SpexGuy** [zigtools/zls#428]
The readme recommends using one of the official release builds, but these builds are highly out of date at this point.  Please either provide releases more frequently or remove this recommendation.

**Comment by nektro** [comment]
do they work if you use 0.8.x?

**Comment by numToStr** [comment]
I've installed v0.8.1 and even `textDocument/rename` is not working with `0.1.0` (maybe it wasn't implemented at that time).

I really wanna try zig but LSP is really lacking atm. I suppose I need to build it from source.

**Comment by SuperAuguste** [comment]
> maybe it wasn't implemented at that time
This is very likely - that version is indeed ancient.

Once the latest Allocgate-induced breakage is confirmed fix, I'll issue a new release :)

**Comment by numToStr** [comment]
@SuperAuguste Thanks for update. I really can't wait to try out zig :)

**Comment by SuperAuguste** [comment]
New release created, thanks for the feedback!
