### ISSUE TITLE
Memory leak and [potentially] an infinite loop

### ISSUE THREAD

**Issue by pixelherodev** [zigtools/zls#43]
For the past few days, I've been having occasional pauses where my computer locks up entirely. After leaving a small terminal running `top` in the background open, I noticed that every time this happens, ZLS is using 100% CPU and massive amounts of RAM, so I suspect there is a memory leak in an infinite loop somewhere.

This also explains why ZLS would sometimes become unresponsive...

**Comment by SuperAuguste** [comment]
Hi @pixelherodev! This is a known issue with the new incremental Zig parser. Are you on the master version of Zig? If so, we definitely need to figure out what's causing these infinite loops.

**Comment by pixelherodev** [comment]
Yeah, on master with both Zig and zls.

Haven't had one in a while, so it's possible they went away after updating at some point yesterday. If I don't see these again for the next day or so, I'll close this :)

**Comment by pixelherodev** [comment]
Better yet, closing now; I'll reopen if it shows up again.
