### ISSUE TITLE
Highlighting broken after if (condition) continue;

### ISSUE THREAD

**Issue by SpexGuy** [zigtools/zls#431]
Putting the line `if (condition) continue;` in a file breaks syntax highlighting after that point in the file.  Suggestions and other features still seem to work though.  Putting braces around the if body fixes highlighting as a workaround.
![image](https://user-images.githubusercontent.com/2281818/144462833-c7fecdb5-8f89-442b-b049-c6d2c6d06200.png)

**Comment by MineBill** [comment]
Are you using vscode? zls doesn't have anything to do with highlighting. I'm guessing you are using the [vscode-zig](https://github.com/ziglang/vscode-zig) extension. Maybe you should create an issue over there.

**Comment by nektro** [comment]
the extension simple acts as a middleman between zls and vscode. zls is definitely responsible for the highlighting

**Comment by leecannon** [comment]
The provided reproduction no longer has the issue with latest zls
