### ISSUE TITLE
VS Code no longer lets breakpoints to be set

### ISSUE THREAD

**Issue by paulevans** [zigtools/zls#433]
Following instructions along the lines of this video: https://www.youtube.com/watch?v=G170lsf551Q

VS Code has previously let me set breakpoints. Right now it does not... though I'm not sure which zig main build would go with which zls build. Zls doesn't seem to build with the latest zig main (zig-windows-x86_64-0.9.0-dev.1926+803178353 at time of writing with https://github.com/zigtools/zls/pull/432/commits)

**Comment by ryuukk** [comment]
It's an option in vscode, in your settings file

``"debug.allowBreakpointsEverywhere": true, ``

yes this is very stupid, after all vscode is an editor made primary for javascript people..

**Comment by ryuukk** [comment]
I wish vscode would set that option as default, that would save people a lot of time!

Since vscode evolved to be more than just an editor for JS/TS, it now supports a wide variety of languages, might be worth it to open a suggestion on their repo
