### ISSUE TITLE
zinput source missing from the 0.9.0 source tarball

### ISSUE THREAD

**Issue by toffaletti** [zigtools/zls#442]
> curl -L https://github.com/zigtools/zls/archive/refs/tags/0.9.0.tar.gz | tar xz

```
vscode ➜ ~/zls-0.9.0 $ zig build -Drelease-safe
error: Failed to add package at path /home/vscode/zls-0.9.0/src/zinput/src/main.zig: FileNotFound
```

**Comment by toffaletti** [comment]
Looks like all submodule source is missing, so `known-folders` is empty also.

**Comment by nektro** [comment]
that's the autogenerated tarball from GitHub, not something we can fix.
