### ISSUE TITLE
Bug: "Invalid symbol '|'" when parsing operator '<<|'

### ISSUE THREAD

**Issue by mjoerussell** [zigtools/zls#447]
When I use the operator '<<|' zls produces the error "Invalid symbol '|'". 

I believe this is happening for the other saturating operators as well, though I haven't thoroughly tested all of them.

**Comment by DoingGitStuff** [comment]
I can second this

**Comment by SuperAuguste** [comment]
I believe that this issue occurred due to a version conflict; please reopen if I'm wrong and this still persists with the latest zig and latest zls. :)
