### ISSUE TITLE
More Zig "std" implementations marked as zls(BadStyle) 

### ISSUE THREAD

**Issue by nlebedenco** [zigtools/zls#450]
VSCode produces multiple problem reports of  "Functions should be camelCase" when "zig-windows-x86_64-0.10.0-dev.444+0e6d2184c/lib/std/start.zig" is opened. This file may get opened for example when debugging the template exe generated after zig init-exe using stepping through or clicking on certain functions in the call stack.

This issue is related to #120 which appears to have been solved with hardcoding the analyzer to accept a trailing underscore in function names but start.zig has various forms of style violations. It is unavoidable that zig code shipped in std libs will violate style rules eventually. Regardless of how often one might expect this to happen (and for how long) it would be useful to have an exclusion list (folders and/or globs) in the extension settings for certain files to be ignored by the linter. This way one can silence lint errors that cannot normally be fixed by the user and reduce noise. Leaving the setting empty is backwards compatible and covers for the rare occasions a dev would be in fact working on std code.

**Comment by SuperAuguste** [comment]
> These are general rules of thumb; if it makes sense to do something different, do what makes sense. For example, if there is an established convention such as ENOENT, follow the established convention.

(see https://ziglang.org/documentation/master/#Names)
