### ISSUE TITLE
Semantic token for keyword 'undefined'

### ISSUE THREAD

**Issue by nlebedenco** [zigtools/zls#456]
Currently the keyword "undefined" is not classified. It could be tagged as a .keywordLiteral token similarly to how "unreachable" is handled in `fn handleToken(self: *Builder, tok: Ast.TokenIndex) !void. `

**Comment by nektro** [comment]
`undefined` is not a keyword https://ziglang.org/documentation/master/#Keyword-Reference

**Comment by haze** [comment]
the vim plugin marks `undefined` as a constant https://github.com/ziglang/zig.vim/blob/3538ae95b469bab6dc15d93067798c87f8968010/syntax/zig.vim#L48
