### ISSUE TITLE
No autocomplete for packages

### ISSUE THREAD

**Issue by Beyley** [zigtools/zls#465]
If i attempt to import a package (whether through `exe.addPackagePath` or with a `std.build.Pkg` with `exe.addPackage`), i get no autocompletion or any language features if i try to import said package in my `main.zig` file, ex `const glfw = @import("glfw");` even though it builds and runs fine, but if i import the package manually by file ex `const glfw = @import("../deps/mach-glfw/src/main.zig");`, completion does work, but it does not build due to a `import of file outside package path` error (which zls should probably show)

**Comment by nektro** [comment]
not a bug

**Comment by dxps** [comment]
> not a bug

That's not helpful either.

**Comment by GideonUng** [comment]
That essential features like this are ignored in zig tooling is one of the things holding zig back. 
If this is omitted by design then the design of zls is the bug.

**Comment by andrewrk** [comment]
Note that:

1. zls, while useful for many people, is not official zig tooling, and
2. a compiler server built into zig itself is planned.

**Comment by GideonUng** [comment]
It is the tooling currently available and its an issue on zls not zig so the issue is still relevant imho.
So until the zig compiler provides a ground truth for a language server this puts an obstacle in front of arguably good coding standards. (modularization and abstraction through modules/packages)

**Comment by nektro** [comment]
zig does a lot of great things, but its good to remember it is still in its early stages. tooling (both official and community) is in a "best effort" situation right now. if this is a issue of great inspiration to you, then research/a pr is very much welcome. sorry for being crude earlier, I was going through a lot of notifications at the time

**Comment by mifopen** [comment]
Works for me on the latest master (ab62e58515956a35e54ded9ba55f2e6484b556a1)

**Comment by leecannon** [comment]
@Beyley If you are still getting this issue can you check the output in vscode again as a much better error should be provided due to https://github.com/zigtools/zls/pull/569
