### ISSUE TITLE
building zls from source error

### ISSUE THREAD

**Issue by 1600** [zigtools/zls#466]
```
git clone --recurse-submodules https://github.com/zigtools/zls
cd zls
zig build -Drelease-safe
./zig-out/bin/zls config # Configure ZLS
```
error is :

./src/main.zig:1663:24: error: expected 2 argument(s), found 1
    while (args_it.next()) |arg| {
                       ^
/home/user/zig-linux-x86_64-0.9.1/lib/std/process.zig:477:9: note: declared here
    pub fn next(self: *ArgIterator, allocator: Allocator) ?(NextError![:0]u8) {
        ^
/home/user/zig-linux-x86_64-0.9.1/lib/std/hash_map.zig:337:13: error: Problems found with hash context type CompletionContext:
  CompletionContext.eql must be fn (self, CompletionItem, CompletionItem) bool
    but is actually fn(analysis.CompletionContext, types.CompletionItem, types.CompletionItem, usize) bool
            @compileError("Problems found with hash context type " ++ @typeName(Context) ++ ":" ++ errors);
            ^
/home/user/zig-linux-x86_64-0.9.1/lib/std/array_hash_map.zig:465:40: note: called from here
    comptime std.hash_map.verifyContext(Context, K, K, u32);
                                       ^
./src/analysis.zig:2304:52: note: called from here
pub const CompletionSet = std.ArrayHashMapUnmanaged(
                                                   ^
./src/analysis.zig:2304:52: note: called from here
pub const CompletionSet = std.ArrayHashMapUnmanaged(
                                                   ^
./src/DocumentStore.zig:38:5: note: while checking this field
    document_scope: analysis.DocumentScope,
    ^
./src/analysis.zig:1128:5: note: while checking this field
    handle: *DocumentStore.Handle,
    ^
/home/user/zig-linux-x86_64-0.9.1/lib/std/array_list.zig:41:9: note: while checking this field
        items: Slice,
        ^
zls...The following command exited with error code 1:
/home/user/zig-linux-x86_64-0.9.1/zig build-exe /home/user/zls/src/main.zig -OReleaseSafe --cache-dir /home/user/zls/zig-cache --global-cache-dir /home/user/.cache/zig --name zls --pkg-begin build_options /home/user/zls/zig-cache/options/uKZopIcuroF1h5GN4XSTLPx9Merwk3esZaDElqA89NfYzxkegeJ3i-pc9OQuwu55 --pkg-end --pkg-begin known-folders /home/user/zls/src/known-folders/known-folders.zig --pkg-end --pkg-begin zinput /home/user/zls/src/zinput/src/main.zig --pkg-end --enable-cache
error: the following build command failed with exit code 1:
/home/user/zls/zig-cache/o/f1848cd81a4d10c4b723179f3ce792ce/build /home/user/zig-linux-x86_64-0.9.1/zig /home/user/zls /home/user/zls/zig-cache /home/user/.cache/zig -Drelease-safe

**Comment by truemedian** [comment]
It looks like you're using the latest tagged release. However, zls's master branch is intended to be built on the latest zig master release

**Comment by leecannon** [comment]
As @truemedian as noted zls master tracks zig master. To build with zig 0.9.0 or 0.9.1 you need to biuild the `0.9.0` tag of zls.

**Comment by 1600** [comment]
it builds on windows with master but not tagged release 0.9.0, on linux the contrary.

**Comment by Jarred-Sumner** [comment]
imo: making zls master dependent on zig master makes it a poor DX to use tagged releases of zig

**Comment by nektro** [comment]
there's zls tags to use with zig tags

**Comment by izackp** [comment]
Should probably note that it's dependent on master or whatever respective branch in the readme :)

**Comment by nektro** [comment]
it is, https://github.com/zigtools/zls#from-source
