### ISSUE TITLE
Show type of variables on introspection

### ISSUE THREAD

**Issue by leighmcculloch** [zigtools/zls#469]
I've noticed that zls in vscode doesn't display the type when showing more information about a variable. Instead it shows the definition.

Here's an example of what I'm seeing with zls:
<img width="300" alt="zig-language-server" src="https://user-images.githubusercontent.com/351529/156963816-28d938cd-cf6a-4e9e-8ded-0c009b24741a.png">

Compared to the information typically shown in other langs (e.g. Go):
<img width="261" alt="go-language-server" src="https://user-images.githubusercontent.com/351529/156963831-9043fe6d-a3aa-4e27-b4f3-123033a62ab6.png">

According to the lovely folks in Discord ([discussion](https://discord.com/channels/605571803288698900/855801133061636136/950134090512879697)) this is by design and not a bug, but something that could be improved.

The value in improving this is largely driven by the fact that in Zig the types of values are not always found at the location of the declaration. This isn't unique of Zig, plenty of other languages allow for this. ZLS could help provide this introspection that the source itself does not make clear.

**Comment by SuperAuguste** [comment]
Ok so I lied about the call for PRs, I'm tackling this right now :)

Thoughts on this look?

![image](https://user-images.githubusercontent.com/19855629/178006360-8e22e7c1-7f9e-4c7b-a279-7f9deed567c3.png)
