### ISSUE TITLE
Missing: Goto definition/declaration for built-in functions

### ISSUE THREAD

**Issue by dxps** [zigtools/zls#470]
Hi everyone!

This is a great tool, and to me kinda critical for the developer experience. So, first of all, thank you for doing it! :pray: 
Just recently got into the Zig journey, hoping to stay here forever. :blush: 

### The Setup
- VSCode (ver. 1.65.2)
- [`zls-vscode`](https://marketplace.visualstudio.com/items?itemName=AugusteRame.zls-vscode) extension (ver. 1.0.4)
- `zls` (ver. 0.9.0)
- on a Linux distro (Pop!_OS 21.10, if relevant).

### The Features

Regaring the features:
- I'm having:
  - _Completions_ (at least, for my defined types)
  - _Hover_
  - (Auto on save) _Formatting_
  - _Syntax Highlighting_ (using [zig](https://marketplace.visualstudio.com/items?itemName=tiehuis.zig) extension)
- **I'm missing** (at least the ones I got into, and the reason of this issue):
  - _Goto definition/declaration_ for built-in functions (it's working for "local" / own defined functions, though)

### ZLS Config

I did the initial ZLS setup (make it executable for all and its init that generates the config file listed below.
And of course, full path to `zls` is provided to the `zls-vscode` extension, that's how some features

```shell
❯ cat ~/.config/zls.json 
{"zig_exe_path":"/snap/bin/zig","enable_snippets":true,"warn_style":true,"enable_semantic_tokens":true,"operator_completions":true,"include_at_in_builtins":false,"max_detail_length":1048576}
❯ 
```
or to have it nicely shown:
```shell
❯ cat ~/.config/zls.json | jq
{
  "zig_exe_path": "/snap/bin/zig",
  "enable_snippets": true,
  "warn_style": true,
  "enable_semantic_tokens": true,
  "operator_completions": true,
  "include_at_in_builtins": false,
  "max_detail_length": 1048576
}
❯
```

Any advice, please?
Thanks!

**Comment by leecannon** [comment]
The zls-vscode extension does not include syntax highlighting, [this](https://marketplace.visualstudio.com/items?itemName=tiehuis.zig) extension is recommended to be used in addition to zls and provides syntax highlighting.

**Comment by dxps** [comment]
@leecannon Thanks, Lee!
Got it! I had it in the past, just got mislead by another feedback. Reinstalled and syntax is nicely shown.
Updated this issue accordingly.

The only TBD remains why "Goto definition/declaration" does not work.

**Comment by nektro** [comment]
this was added after the 0.9.0 release

**Comment by dxps** [comment]
@nektro Thanks, Meghan!
You're absolutely right. Just compiled `zls` from source, updated the reference to it, and indeed _goto_ (ctrl+b) is working just fine.

To conclude, maybe the readme can include a note referred by the features that exists, but not yet included in the release.
