### ISSUE TITLE
can't build zls from tuto readme.md

### ISSUE THREAD

**Issue by xBLACKICEx** [zigtools/zls#487]
## compile errors
![image](https://user-images.githubusercontent.com/51036094/168401054-cf4c4a92-d3c8-460c-bfe3-fa0486c1a6ba.png)

### wsl archWSL
---
## zig version
![image](https://user-images.githubusercontent.com/51036094/168401339-6fa8e5c0-1f8b-42b3-8f4e-99017baf6402.png)
## xz version
![image](https://user-images.githubusercontent.com/51036094/168401159-8c4ab723-eddf-4c01-a7e4-fd89dc2adb71.png)

**Comment by truemedian** [comment]
zls only works on the latest master tarball, and currently we're waiting for a fix to a recent stdlib change <https://github.com/zigtools/zls/pull/481>
