### ISSUE TITLE
Compiling error in newest zig

### ISSUE THREAD

**Issue by heibor** [zigtools/zls#491]
In the newest zig version: **0.10.0-dev.2307+7b63f98cd**.
When I compile **zls**, I got these error message:
```
./src/main.zig:1457:48: error: expected error union type, found 'std.child_process.ChildProcess'
        var process = try std.ChildProcess.init(&[_][]const u8{ zig_exe_path, "fmt", "--stdin" }, allocator);
                                               ^
zls...The following command exited with error code 1:
/opt/homebrew/Cellar/zig/HEAD-7b63f98/bin/zig build-exe /Users/hurray/works/zig/zls/src/main.zig --cache-dir /Users/hurray/works/zig/zls/zig-cache --global-cache-dir /Users/hurray/.cache/zig --name zls --pkg-begin build_options /Users/hurray/works/zig/zls/zig-cache/options/H9AR0LKhRsNLPCkAU3kSn-zvYq8-9gC59lDnXgE_CH0psH885s1rdv7SSsAB5aNT --pkg-end --pkg-begin known-folders /Users/hurray/works/zig/zls/src/known-folders/known-folders.zig --pkg-end --pkg-begin zinput /Users/hurray/works/zig/zls/src/zinput/src/main.zig --pkg-end --enable-cache 
error: the following build command failed with exit code 1:
```

Is it because it is not yet compatible with the new zig version.

**Comment by leecannon** [comment]
There are three seperate PR's to fix zls upto zig master, but none of them are in a mergeable state :-1: 
https://github.com/zigtools/zls/pull/481
https://github.com/zigtools/zls/pull/485
https://github.com/zigtools/zls/pull/490

Looks like https://github.com/zigtools/zls/pull/481 is closest but the latest comment from 5 days ago hasn't been done.

**Comment by heibor** [comment]
Thank you for your help, I'll check them.

**Comment by neel-bp** [comment]
@leecannon after my latest commit i have tried running test locally and now nothing fails and this file uri thing seems to only happen on windows, i should try it again sorry for my lack of understanding about this.

**Comment by macsmol** [comment]
How are the fixes going? I really wanted to try out zig but I don't think it's worth it without debugging capabilities
