### ISSUE TITLE
Can't build master branch

### ISSUE THREAD

**Issue by macsmol** [zigtools/zls#497]
So I've pulled the master with the fix for issue #491. I run the
`zig build -Drelease-safe`
But it ends with an error message that some file is missing.
`c:\programy\zig\zls>zig build -Drelease-safe
error: Failed to add package at path C:\programy\zig\zls\src\zinput\src\main.zig: FileNotFound
zls...The following command exited with error code 1:
c:\programy\zig\zig-windows-x86_64-0.10.0-dev.2431+0e6285c8f\zig.exe build-exe C:\programy\zig\zls\src\main.zig -OReleaseSafe --cache-dir C:\programy\zig\zls\zig-cache --global-cache-dir C:\Users\macsmol\AppData\Local\zig --name zls --pkg-begin build_options C:\programy\zig\zls\zig-cache\options\H9AR0LKhRsNLPCkAU3kSn-zvYq8-9gC59lDnXgE_CH0psH885s1rdv7SSsAB5aNT --pkg-end --pkg-begin known-folders C:\programy\zig\zls\src\known-folders\known-folders.zig --pkg-end --pkg-begin zinput C:\programy\zig\zls\src\zinput\src\main.zig --pkg-end --enable-cache
error: the following build command failed with exit code 1:
c:\programy\zig\zls\zig-cache\o\35fe9664d2f923190d0b85dca46fbbc3\build.exe c:\programy\zig\zig-windows-x86_64-0.10.0-dev.2431+0e6285c8f\zig.exe c:\programy\zig\zls c:\programy\zig\zls\zig-cache C:\Users\macsmol\AppData\Local\zig -Drelease-safe
`

The file indeed is not there (the zinput folder is empty). I see that there's folder named "zinput @ 5e0d781" when I browse the repo on github. Looks like it has sth to do with that. I'm not sure what to make of it anyway.

I just expect that master branches simply build after being pulled. I guess it's a reasonable expectation.

What do I do to fix this?

**Comment by leecannon** [comment]
The missing file is a submodule `git submodule update --init`

**Comment by macsmol** [comment]
Alright! Built the binary! Thx! I've deleted the repo after encountering the other bug. When I cloned it again I missed the "git submodules magic" bit.
