### ISSUE TITLE
snippets no longer work

### ISSUE THREAD

**Issue by leecannon** [zigtools/zls#510]
Since #507 and using https://github.com/zigtools/zls-vscode/pull/33 snippets no longer work, upon accepting a completion only the function name is inserted with no parenthesis or argument placeholders, exactly the same as if snippet support were disabled.

I've looked at the changes and can't see any reason they would cause this.

Any ideas @ryuukk

**Comment by SuperAuguste** [comment]
`insertTextFormat` is always overridden to be `.PlainText` (for example, [here](https://github.com/ryuukk/zls/blob/acb339ab955a5d226d78316e17a557752adb5318/src/main.zig#L1254)), which I suspect causes this issue.

**Comment by SuperAuguste** [comment]
Tested with and without snippets, #512 should fix this! @leecannon please let me know if some snippets still break, thanks! Also, thank you so much for keeping zls alive, very much appreciated! :)
