### ISSUE TITLE
Off-by-one in enum parameter completion

### ISSUE THREAD

**Issue by Vexu** [zigtools/zls#521]
![Screenshot from 2022-07-11 16-56-03](https://user-images.githubusercontent.com/15308111/178280884-05b7e3c6-eb15-45f8-a565-807367501352.png)
Attempting to write `.a` will not remove the closing brace so you are left with `foo(.a})`.
```zig
fn foo(_: enum {a, b}) void {}
comptime {
    foo(_: enum{a, b})
}
```

**Comment by SuperAuguste** [comment]
Oof, another off-by-one :(

I'll take a jab at fixing this sooner rather than later :)

**Comment by SuperAuguste** [comment]
Seems to happen for all containers
```zig
fn foo(_: struct {a, b}) void {}
```
does the same thing
