### ISSUE TITLE
Broken when updating vscode-languageclient to latest version

### ISSUE THREAD

**Issue by ryuukk** [zigtools/zls#524]
Hello,

I'm trying to prepare zls for LSP 3.17, i updated vscode-languageclient to the latest version (8.0.1)

But then code completion is broken, something might have changed, but i don't know what, i'm not knowledgeable about npm stuff

**Comment by Techatrix** [comment]
the LSP types are now completely auto generated and no further issues around this have been reported so I assume this is now outdated.
