### ISSUE TITLE
error while building from source

### ISSUE THREAD

**Issue by norflin321** [zigtools/zls#541]
Following below instructions:

```
git clone --recurse-submodules https://github.com/zigtools/zls
cd zls
zig build -Drelease-safe
./zig-out/bin/zls config # Configure ZLS
```

I get this error:
<img width="860" alt="Screenshot 2022-07-16 at 11 32 16 AM" src="https://user-images.githubusercontent.com/33498670/179347289-4d23a74c-c7f2-4ed9-a3d6-7a9251ce1ac5.png">

zig version: 0.9.1
OS: Monterey 12.3.1 (arm)

**Comment by SuperAuguste** [comment]
Please use Zig master and reopen if the issue persists :)

**Comment by raix** [comment]
Get same issue on
zig version: 0.9.1
OS: Windows 10
zls: master (ba68a4d)

**Comment by SuperAuguste** [comment]
Please use **Zig master**; zls only builds with **Zig master**! Thank you! :)
