### ISSUE TITLE
Autocompletion for struct fields in function parameters

### ISSUE THREAD

**Issue by foxnne** [zigtools/zls#542]
`pub const Settings = struct { x: f32, y: f32 };`
` pub fn example (settings: Settings) void {}`

The goal would be to provide a list of the fields in `Settings` when pressing `.`  when calling the `example` function:
`example( .{  . //completion for x = f32 or y = f32 });`

**Comment by Techatrix** [comment]
this has been implemented by @nullptrdevs :rocket:
