### ISSUE TITLE
Useless_dot emitted incorrectly when using `..`

### ISSUE THREAD

**Issue by devins2518** [zigtools/zls#553]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/17111639/180014476-82b2456d-85dd-4ec9-ba8e-5c4262bc96ab.png">

**Comment by SuperAuguste** [comment]
Yep, spotted this too, I'll fix this later :)

**Comment by nektro** [comment]
`./` is not needed but should be recommended for file imports
