### ISSUE TITLE
ZLS: Don't showing `std.DynLib` members.

### ISSUE THREAD

**Issue by kassane** [zigtools/zls#556]
I am trying to implement an ongoing project using libloader from zig's standard library, but it is painful to have to manually review each line for its available members.

- https://github.com/kassane/zig-pkcs11/issues/2

**Comment by SuperAuguste** [comment]
zls can't deal with the [switch](https://github.com/ziglang/zig/blob/master/lib/std/dynamic_library.zig#L13-L18); common comptime issue.

**Comment by SuperAuguste** [comment]
See #1031 :)

**Comment by kassane** [comment]
> See #1031 :)

Wow! Nice. 🥳
