### ISSUE TITLE
No member 'source' in struct 'std.build.Pkg'

### ISSUE THREAD

**Issue by its-popplewell** [zigtools/zls#563]
I have been trying to download ZLS to run with the helix text editor. However, I have been unable to successfully download it because, whenever I do, when I go about building the downloaded folder, I get an error:

`./build.zig:47:48: error: no member named 'source' in struct 'std.build.Pkg'
    exe.addPackage(.{ .name = "known-folders", .source = .{ .path = known_folders_path } });`

Running on MacOS.

**Comment by haze** [comment]
I believe you need a more recent copy of zig, as the API has changed since 0.9.0.
Either install zig from the release tarball on the download page for zig, or use `brew install zig --HEAD`

**Comment by its-popplewell** [comment]
I will try this now! Thank you!

**Comment by its-popplewell** [comment]
After reinstalling zig using the command:
`brew install --head zig`
I got a new error! (yay)

`/opt/homebrew/Cellar/zig/HEAD-c8c7986_1/lib/zig/std/fmt.zig:492:17: error: cannot format optional without a specifier (i.e. {?} or {any})
                @compileError("cannot format optional without a specifier (i.e. {?} or {any})"); `

**Comment by haze** [comment]
unfortunately zig had another breaking change today 😭 you have to clone zig and compile it yourself, or wait for someone who maintains zls to fix the formatting. you can also do it yourself locally if you know what changed

**Comment by its-popplewell** [comment]
I reinstalled zig and I am now running on zig version `0.10.0-dev.3355+dfc7493dc`. I also reinstalled ZLS from the source and I still am running into the same error when I run zig run build_runner.zig.
@haze

**Comment by haze** [comment]
don’t run build runner, just do zig build

**Comment by its-popplewell** [comment]
@haze thank you so much for your help! I got it installed and finally figured out why zsh was not reading my .zshrc file. Thank you again!!
