### ISSUE TITLE
zls is running successfully but autocomplete (ctrl+space) doesn't show anything useful on VSCode/Mac

### ISSUE THREAD

**Issue by timfayz** [zigtools/zls#586]
Hi everyone! 

I'm trying to setup my first Zig experience with zls + vscode. Everything seems to be working...namely, on hovering elements I get good suggestions. For example:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/6209197/185664441-bf365fb8-7163-4ebb-8ab2-26e48c8f6f28.png">

<img width="943" alt="image" src="https://user-images.githubusercontent.com/6209197/185665212-38068e42-56cf-41c6-bdf0-0ffa28c4b4ab.png">

However, when I'm trying to get autocomplete (say, by pressing Ctrl+Space), I get the following:

<img width="903" alt="image" src="https://user-images.githubusercontent.com/6209197/185664682-e4b5bfa8-8f25-4484-b78a-f5aab23055d3.png">

Output from the extension on startup:
```
Attempting to use zls @ /Users/timfayz/zls/zls
[Info  - 7:15:52 PM] [info-main] Using zig executable /opt/homebrew/bin/zig
[Info  - 7:15:52 PM] [info-main] Using zig lib path '/opt/homebrew/Cellar/zig/0.9.1_1/lib/zig'
[Info  - 7:15:52 PM] [info-main] zls initialized
[Info  - 7:15:52 PM] [info-main] ClientCapabilities{ .supports_snippets = true, .supports_semantic_tokens = true, .hover_supports_md = true, .completion_doc_supports_md = true }
[Info  - 7:15:52 PM] [info-main] Using offset encoding: utf16
```

Environment:
```
(VSCode)
Version: 1.70.2 (Universal)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z (3 days ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.1.0, 12.0.1 (21A559)
```

VSCode is purely installed just today with two extensions: "Zig Language Server (zls) for VSCode" + "Zig".

**Any ideas?**

**Comment by Zzzen** [comment]
Having the same issue.

**Comment by leecannon** [comment]
It looked like the issue for @timfayz was caused by https://github.com/ziglang/zig/issues/12516, if you are on any target other than linux x86_64 the tarball has the incorrect location of the stdlib.

**Comment by leecannon** [comment]
@Zzzen @timfayz Is it possible for you to test https://github.com/zigtools/zls/pull/599

**Comment by timfayz** [comment]
@leecannon Sorry, what exactly should I test? I see that your PR to master was blocked. 

Anyway, as I mentioned in the discord/zig/#zig-help, the workaround (for `zig-macos-x86_64-0.10.0-dev.3659+e5e6eb983`) was to specify the explicit path to zig lib:

```
// settings.json
{
  ...
  "zls.zig_lib_path": "/home/username/zig_[version]/lib/zig",
  ...
}
```

**Comment by leecannon** [comment]
Don't worry I've been able to test on another system that PR does workaround the issue.

**Comment by Zzzen** [comment]
It works on my machine now. Thanks!
