### ISSUE TITLE
ZLS does not show function signature

### ISSUE THREAD

**Issue by noiryuh** [zigtools/zls#608]
### Zig Version

0.10.0-dev.3685+dae7aeb33

### Zig Language Server Version

8cf96fe27cfd235acdf301728f9cce7a7b265ca3

### Steps to Reproduce

Use [Helix](https://helix-editor.com) (`v22.05`),
`build_runner.zig` in the same directory as `zls` and `zls` is in `$PATH`.

ZLS config file:
```json
{
    "zig_exe_path": "/home/noiryuh/.local/bin/zig",
    "enable_snippets": true,
    "enable_unused_variable_warnings": true,
    "enable_import_embedfile_argument_completions": true,
    "warn_style": false,
    "enable_semantic_tokens": true,
    "enable_inlay_hints": true,
    "operator_completions": true,
    "include_at_in_builtins": false,
    "max_detail_length": 1048576
}
```

### Expected Behavior

ZLS should show function signatures for stdlib functions (like for builtin functions).
![20220826_14h16m57s_grim](https://user-images.githubusercontent.com/109846069/186845001-2ce75ffb-f21e-491a-9cb1-1e3804a4af7d.jpeg)

### Actual Behavior

ZLS doesn't show function signatures for stdlib.
![20220826_14h09m43s_grim](https://user-images.githubusercontent.com/109846069/186843790-a37ded71-cd76-4131-a544-c797104bc821.jpeg)

**Comment by nullptrdevs** [comment]
likely client side/plugin

vscode for comparison:
![zls_completion_screenshot_vscode](https://user-images.githubusercontent.com/16590917/186949058-5116f2af-78e8-4706-92d9-fa6462e60643.png)
![zls_completion_screenshot_vscode2](https://user-images.githubusercontent.com/16590917/186950474-19ac35f3-7670-4f0b-8abc-f346121af81f.png)

**Comment by noiryuh** [comment]
it's default config in Helix
```toml
theme = "tokyonight"

[editor]
line-number = "relative"

[editor.whitespace]
render = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
```

it used to work normally before, the only thing i update was ZLS.

**Comment by DivergentClouds** [comment]
Happening to me on helix too, I just checked and it's happening with the kakoune editor too

**Comment by DivergentClouds** [comment]
I can confirm that this issue does not happen with the 0.9.0 release of ZLS, so it is definitely on the ZLS end

**Comment by nullptrdevs** [comment]
ok,

I were able to achieve/approximate the functionality with the following changes:
```
diff --git a/src/Server.zig b/src/Server.zig
index 59eec00..94785a2 100644
--- a/src/Server.zig
+++ b/src/Server.zig
@@ -531,11 +531,15 @@ fn nodeToCompletion(
 
                 const is_type_function = analysis.isTypeFunction(handle.tree, func);
 
+                const fn_sig = analysis.getFunctionSignature(handle.tree, func);
+                const fn_name = handle.tree.tokenSlice(name_token);
+                const fn_name_pos = std.mem.indexOf(u8, fn_sig, fn_name) orelse 0;
+
                 try list.append(allocator, .{
-                    .label = handle.tree.tokenSlice(name_token),
+                    .label = fn_sig[fn_name_pos..],
                     .kind = if (is_type_function) .Struct else .Function,
                     .documentation = doc,
-                    .detail = analysis.getFunctionSignature(handle.tree, func),
+                    .detail = fn_sig,
                     .insertText = insert_text,
                     .insertTextFormat = if (use_snippets) .Snippet else .PlainText,
                 });
```
[or artifacts](https://github.com/nullptrdevs/zls/actions/runs/2941276148)

but this causes a lot more items to be included in the completion list ?..
