### ISSUE TITLE
Don't drop build_runner.zig next to executable

### ISSUE THREAD

**Issue by LordMZTE** [zigtools/zls#634]
### Zig Version

0.10.0-dev.3685+dae7aeb33

### Zig Language Server Version

38210d3e9183a77dfe10e0d0f4a79d2999ce3cf7

### Steps to Reproduce

Start `zls` in a project. If the `zls` binary is installed in a read-only directory, such as `/usr/bin` this will crash with a permission denied error.

### Expected Behavior

`zls` doesn't try to drop any files next to its executable, and instead uses some alternative path such as `zig-cache` or `/tmp`.

### Actual Behavior

`zls` tries to create a `build_runner.zig` file next to its executable. This often fails, for example when zls is installed in `/usr/bin` (tries to create `/usr/bin/build_runner.zig`), and needlessly pollutes the filesystem.

This was introduced in `38210d3e9183a77dfe10e0d0f4a79d2999ce3cf7`.

Once we agree on a solution, I'd very much like to implement it. Cheers!

**Comment by SuperAuguste** [comment]
We could use known-folders to drop it somewhere that makes sense rather than next to the executable perhaps?

**Comment by LordMZTE** [comment]
Sounds good! I think we should go with `[KnownFolder.runtime]/zls/build_runner.zig` (`/run/user/[uid]/zls/build_runner.zig` on linux, usually a tmpfs) or `[KnownFolder.cache]/zls/build_runner.zig` (`~/.cache/zls/build_runner.zig` on linux). Which one would you prefer?

**Comment by SuperAuguste** [comment]
I think cache might make more sense; thoughts @Techatrix? :)

**Comment by LordMZTE** [comment]
Also, it might be a good idea to only write the file if it doesn't exist yet. What do you think?

**Comment by SuperAuguste** [comment]
The problem is updating the build_runner when it changes; we could use hashes or something but that would be needlessly complex when we could just rewrite the build_runner imo.

**Comment by Techatrix** [comment]
I would be in favor of putting it in cache. And if you don't want zls to override it just specify `build_runner_path`
