### ISSUE TITLE
Install instructions for macOS are incomplete

### ISSUE THREAD

**Issue by OliverM** [zigtools/zls#639]
### Zig Version

0.10.0-dev.3978+4fd4c733d

### Zig Language Server Version

current master

### Steps to Reproduce

Follow the installation instructions for macOS. Set the path to the `zls` binary in your emacs config correctly.

### Expected Behavior

The ZLS LSP server should successfully launch on opening zig files

### Actual Behavior

The *lsp-log* buffer on emacs reports `Command "<verified path to zls>" is not present on the path.` and no LSP functionality is available for Zig files in my emacs (actually spacemacs) installation.

**Comment by OliverM** [comment]
The issue is that following the installation instructions doesn't set the exec flag on the downloaded binary. Running `chmod +x ./zls` sets the exec bit on the downloaded file and resolves the issue.

**Comment by SuperAuguste** [comment]
Understandable. Not sure how we could clarify this.
