### ISSUE TITLE
Show types of struct members in completions

### ISSUE THREAD

**Issue by Sergeeeek** [zigtools/zls#64]
Here's how the completion for struct fields currently look like:
![image](https://user-images.githubusercontent.com/3381399/82405076-9201ef80-9a6b-11ea-958b-cc92b1659479.png)

Fields are enumerated properly, but there's no type info.

**Comment by SuperAuguste** [comment]
Fixed! (6ae23ba2d0edfcb47c582de08f1cb43a846abcb3)
