### ISSUE TITLE
`--config` and `--version` are both unrecognized

### ISSUE THREAD

**Issue by HymanZHAN** [zigtools/zls#697]
### Zig Version

0.10.0-dev.4212+34835bbbc

### Zig Language Server Version

0.9.0 Latest

### Steps to Reproduce

- Install zls by following [this instruction](https://github.com/zigtools/zls#linux)
- Add zls path to $PATH
- Type `zls --version` or `zls --config` in the terminal
- Error shown

### Expected Behavior

`zls --version` should return the version number, and `zls --config` should let me config zls, according to the README file.

### Actual Behavior

![image](https://user-images.githubusercontent.com/26806995/193400541-d40011e8-b332-4c10-b330-c10a1b2a7464.png)

And it stops me from using zls in VS Code because VS Code calls `zls --version` to check if the language server has been installed.

![image](https://user-images.githubusercontent.com/26806995/193400031-d9c3d7d0-3a54-44af-85fd-c1fcdfc49ac5.png)

I am aware that `zls config` works, but the docs say otherwise.

As a side note, `zls --show-config-path` doesn't work either.

**Comment by Techatrix** [comment]
zls-vscode assumes you are using a build from master and not the old 0.9.0 release which is very outdated and should only be used if you are using the 0.9.x zig compiler as well.
You can either compile from source yourself ([instructions](https://github.com/zigtools/zls#from-source)) or use the command `Zig Language Server: Install Server` in vs-code which installs the latest prebuild binary for you.
