### ISSUE TITLE
`zls` doesn't respect `zls.json` `enable_autofix` config in nvim

### ISSUE THREAD

**Issue by HymanZHAN** [zigtools/zls#698]
### Zig Version

0.10.0-dev.4213+91b05ad47

### Zig Language Server Version

0.10.0-dev.314+ac6353a

### Steps to Reproduce

- Build `zig` and `zls` from master.
- Configure `zls` in Neovim with nvim-lspconfig

```json
{
    "$schema": "https://raw.githubusercontent.com/zigtools/zls/master/schema.json",
    "zig_exe_path": "/home/xzhan/Development/Packages/software/zig/zig",
    "enable_snippets": true,
    "enable_ast_check_diagnostics": true,
    "enable_autofix": false,
    "enable_import_embedfile_argument_completions": true,
    "warn_style": true,
    "enable_semantic_tokens": true,
    "enable_inlay_hints": true,
    "operator_completions": true,
    "include_at_in_builtins": false,
    "max_detail_length": 1048576
}
```

```lua
local nvim_lsp = require('lspconfig')

local on_attach = function(client, bufnr)
    local opts = { noremap = true, silent = true, buffer = bufnr }

    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'gh', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
    vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
    vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
    vim.keymap.set('n', '<F2>', vim.lsp.buf.rename, opts)
    vim.keymap.set('n', '<space>ca', vim.lsp.buf.code_action, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
    vim.keymap.set('n', '<space>e', vim.lsp.diagnostic.show_line_diagnostics, opts)
    vim.keymap.set('n', '[d', vim.lsp.diagnostic.goto_prev, opts)
    vim.keymap.set('n', ']d', vim.lsp.diagnostic.goto_next, opts)
    vim.keymap.set('n', '<space>q', vim.lsp.diagnostic.set_loclist, opts)
    vim.keymap.set('n', '<space>f', vim.lsp.buf.formatting, opts)
end

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)

local servers = { 'rust_analyzer', 'clangd', 'tsserver', 'sumneko_lua', 'pyright', 'zls' }
for _, lsp in ipairs(servers) do
    nvim_lsp[lsp].setup {
        capabilities = capabilities,
        on_attach = on_attach
    }
end
```
- Open a `zig` file and start editing
- The `zig` file gets auto-fixed every time I save it.

### Expected Behavior

`zls` should respect `zls.json` and doesn't automatically format `zig` files when I save them.

### Actual Behavior

`zls` auto-format `zig` files every time I save them.

[Screencast from 10-02-2022 12:48:02 PM.webm](https://user-images.githubusercontent.com/26806995/193438392-14698fde-e319-4773-b087-c4be72c9a90c.webm)

**Comment by SuperAuguste** [comment]
`enable_autofix` is not related to formatOnSave, that's an option you should configure from within your editor.

**Comment by HymanZHAN** [comment]
My editor (neovim) is not configured to do "format on save", and `zls` is the only language server showing this behavior. Please reopen the issue.

**Comment by SuperAuguste** [comment]
I can almost guarantee that this issue is not related to zls itself and I am 100% sure that `enable_autofix` is not the option for disabling auto-formatting.

**Comment by HymanZHAN** [comment]
I will do a little digging and provide the debug log later today.

**Comment by jcmoyer** [comment]
I can't reproduce the issue on a clean install of nvim + nvim-lspconfig. Did you perhaps also install [https://github.com/ziglang/zig.vim](zig.vim)? It has a setting for this.

**Comment by HymanZHAN** [comment]
@jcmoyer You are absolutely right. I did! Thank you very much for looking into this.
