### ISSUE TITLE
 enumeration value 'std.zig.Ast.Node.Tag.switch_case_inline_one' not handled in switch

### ISSUE THREAD

**Issue by dpogorzelski** [zigtools/zls#700]
### Zig Version

0.10.0-dev.4247+3234e8de3

### Zig Language Server Version

ac6353add7b1dc5fdee25333b02d8c52e589502a

### Steps to Reproduce

zig build -Drelease-safe

### Expected Behavior

Should compile

### Actual Behavior

./src/analysis.zig:2519:5: error: enumeration value 'std.zig.Ast.Node.Tag.switch_case_inline_one' not handled in switch
    switch (node_tag) {
    ^
./src/analysis.zig:2519:5: error: enumeration value 'std.zig.Ast.Node.Tag.switch_case_inline' not handled in switch
    switch (node_tag) {
    ^
./src/semantic_tokens.zig:299:5: error: enumeration value 'std.zig.Ast.Node.Tag.switch_case_inline_one' not handled in switch
    switch (tag) {
    ^
./src/semantic_tokens.zig:299:5: error: enumeration value 'std.zig.Ast.Node.Tag.switch_case_inline' not handled in switch
    switch (tag) {
    ^
./src/ast.zig:265:18: error: enumeration value 'std.zig.Ast.Node.Tag.switch_case_inline_one' not handled in switch
    while (true) switch (tags[n]) {
                 ^
./src/ast.zig:265:18: error: enumeration value 'std.zig.Ast.Node.Tag.switch_case_inline' not handled in switch
    while (true) switch (tags[n]) {
                 ^
./src/inlay_hints.zig:277:5: error: enumeration value 'std.zig.Ast.Node.Tag.switch_case_inline_one' not handled in switch
    switch (tag) {
    ^
./src/inlay_hints.zig:277:5: error: enumeration value 'std.zig.Ast.Node.Tag.switch_case_inline' not handled in switch
    switch (tag) {
    ^
./src/references.zig:95:5: error: enumeration value 'std.zig.Ast.Node.Tag.switch_case_inline_one' not handled in switch
    switch (node_tags[node]) {
    ^
./src/references.zig:95:5: error: enumeration value 'std.zig.Ast.Node.Tag.switch_case_inline' not handled in switch
    switch (node_tags[node]) {

**Comment by jonase** [comment]
There's a PR at https://github.com/zigtools/zls/pull/699. I'm not sure how complete it is, but it's been working ok for me.

**Comment by dpogorzelski** [comment]
Aha I did the same changes manually in the meanwhile and it solved it :)

**Comment by SuperAuguste** [comment]
Just addressed a small issue with it, it'll be merged soon :)
