### ISSUE TITLE
No native ZLS Build for arm64 Mac

### ISSUE THREAD

**Issue by BobG1983** [zigtools/zls#704]
## No native build for arm64 Mac

I would love it if we could get a native build for aarch64 mac that was output by CI so that the VSCode plugin could download and install it automatically.

**Comment by nektro** [comment]
yes there is

**Comment by nektro** [comment]
> that was output by CI

the CI does produce `aarch64-macos` builds. old releases aren't going to be modified after the fact.

**Comment by SuperAuguste** [comment]
What Meghan said; when a new Zig version drops we'll tag a new "stable" release that includes all CI artifact targets. For now, please click on the latest successful CI run and download the build artifacts.
