### ISSUE TITLE
Unable to build on Mac M1

### ISSUE THREAD

**Issue by jecolon** [zigtools/zls#708]
### Zig Version

0.10.0-dev.3880+e2bb92b2e

### Zig Language Server Version

cd88783

### Steps to Reproduce

1. Did git clone --recurse-submodules
2. Ran zig build

### Expected Behavior

Build successfully 

### Actual Behavior

Generates error:
./src/semantic_tokens.zig:115:13: error: enum 'std.zig.tokenizer.Token.Tag' has no field named 'number_literal'
            .number_literal => .number,
            ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.10.0-dev.3880+e2bb92b2e/lib/std/zig/tokenizer.zig:68:21: note: 'std.zig.tokenizer.Token.Tag' declared here
    pub const Tag = enum {
                    ^
./src/analysis.zig:2831:9: error: enum 'std.zig.Ast.Node.Tag' has no field named 'switch_case_inline'
        .switch_case_inline,
        ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.10.0-dev.3880+e2bb92b2e/lib/std/zig/Ast.zig:2587:21: note: 'std.zig.Ast.Node.Tag' declared here
    pub const Tag = enum {
                    ^
./src/semantic_tokens.zig:523:9: error: enum 'std.zig.Ast.Node.Tag' has no field named 'switch_case_inline_one'
        .switch_case_inline_one,
        ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.10.0-dev.3880+e2bb92b2e/lib/std/zig/Ast.zig:2587:21: note: 'std.zig.Ast.Node.Tag' declared here
    pub const Tag = enum {
                    ^
./src/ast.zig:440:9: error: enum 'std.zig.Ast.Node.Tag' has no field named 'switch_case_inline_one'
        .switch_case_inline_one,
        ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.10.0-dev.3880+e2bb92b2e/lib/std/zig/Ast.zig:2587:21: note: 'std.zig.Ast.Node.Tag' declared here
    pub const Tag = enum {
                    ^
./src/translate_c.zig:151:69: error: missing field: 'ptr'
        const target_info = std.zig.system.NativeTargetInfo.detect(.{}) catch break :blk null;
                                                                    ^
./src/translate_c.zig:151:69: error: missing field: 'vtable'
        const target_info = std.zig.system.NativeTargetInfo.detect(.{}) catch break :blk null;
                                                                    ^
./src/inlay_hints.zig:338:9: error: enum 'std.zig.Ast.Node.Tag' has no field named 'number_literal'
        .number_literal,
        ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.10.0-dev.3880+e2bb92b2e/lib/std/zig/Ast.zig:2587:21: note: 'std.zig.Ast.Node.Tag' declared here
    pub const Tag = enum {
                    ^
./src/analysis.zig:1616:9: error: enum 'std.zig.Ast.Node.Tag' has no field named 'number_literal'
        .number_literal,
        ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.10.0-dev.3880+e2bb92b2e/lib/std/zig/Ast.zig:2587:21: note: 'std.zig.Ast.Node.Tag' declared here
    pub const Tag = enum {
                    ^
./src/references.zig:180:9: error: enum 'std.zig.Ast.Node.Tag' has no field named 'switch_case_inline_one'
        .switch_case_inline_one,
        ^
/Users/jecolon/Downloads/zig-macos-aarch64-0.10.0-dev.3880+e2bb92b2e/lib/std/zig/Ast.zig:2587:21: note: 'std.zig.Ast.Node.Tag' declared here
    pub const Tag = enum {
                    ^
error: zls...
error: The following command exited with error code 1:
/Users/jecolon/Downloads/zig-macos-aarch64-0.10.0-dev.3880+e2bb92b2e/zig build-exe -fstage1 /Users/jecolon/code/zig/zls/src/main.zig --cache-dir /Users/jecolon/code/zig/zls/zig-cache --global-cache-dir /Users/jecolon/.cache/zig --name zls --pkg-begin build_options /Users/jecolon/code/zig/zls/zig-cache/options/Rw8koz0R4QflJ1WZKxl1Gy9WvvAoMn-4XaLY0T1sZSuoDxixgQNlYBbeFqEeHz8y --pkg-end --pkg-begin known-folders /Users/jecolon/code/zig/zls/src/known-folders/known-folders.zig --pkg-end --enable-cache 
error: the following build command failed with exit code 1:
/Users/jecolon/code/zig/zls/zig-cache/o/467b35930ec0cbaf929d5667c62b27df/build /Users/jecolon/Downloads/zig-macos-aarch64-0.10.0-dev.3880+e2bb92b2e/zig /Users/jecolon/code/zig/zls /Users/jecolon/code/zig/zls/zig-cache /Users/jecolon/.cache/zig

**Comment by Techatrix** [comment]
You need to use a newer zig compiler version.

**Comment by nektro** [comment]
latest is `zig-0.10.0-dev.4324+c23b3e6fd`

**Comment by jecolon** [comment]
Yep, that was it. Thanks!
