### ISSUE TITLE
`@cImport` completion is broken

### ISSUE THREAD

**Issue by leecannon** [zigtools/zls#721]
### Zig Version

0.10.0-dev.4587+710e2e7f1

### Zig Language Server Version

0.10.0-dev.352+befb2d1

### Steps to Reproduce

main.zig:
```zig
const std = @import("std");
const c = @cImport(@cInclude("foo.h"));

pub fn main() !void {
    std.debug.print("{}\n", .{c.a});
}
```
foo.h
```c
int a = 2;
```
build.zig
```zig
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardReleaseOptions();

    const exe = b.addExecutable("fff", "main.zig");
    exe.setTarget(target);
    exe.setBuildMode(mode);
    exe.linkLibC();
    exe.addIncludePath(".");

    const run_cmd = exe.run();
    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
}

```

### Expected Behavior

Typing `c.` should result in completions being provided from the translate-c file.

### Actual Behavior

No completions.

**Comment by leecannon** [comment]
@Techatrix This is broken by 0cfc7928496ba9a4764898760357d5892912aed3 as it works in the commit before 25ce5dd8aa28e8ea2f90f6cb6d722ab0f0d3fbac

**Comment by Techatrix** [comment]
i already know why, i will look into it...
