### ISSUE TITLE
Crash when clicking on a label (or moving the cursor there)

### ISSUE THREAD

**Issue by llogick** [zigtools/zls#728]
NOTE: To whomever tries to reproduce/work on this, you'll have to reenable the codepath
https://github.com/zigtools/zls/blob/84286521463259d8acc6c1fe70ab56d8f89caca4/src/Server.zig#L2243-L2246

### Zig Version

0.10.0-dev.4733+d02242661

### Zig Language Server Version

0.10.0-dev.359+7a7576c

### Steps to Reproduce

```zig
pub fn ohno() void {
    blk: {
        break :blk;
    }
}
```
click on the second `blk`

### Expected Behavior

not crash

### Actual Behavior

```
thread 14876 panic: index out of bounds
/home/workaccount/Work/zig/build/stage3/lib/zig/std/zig/Ast.zig:382:30: 0x33ea8c in std.zig.Ast.firstToken (zls)
    while (true) switch (tags[n]) {
                             ^
/home/workaccount/Work/zls/main/src/references.zig:23:38: 0x44ebba in references.labelReferences (zls)
    const first_tok = tree.firstToken(decl.decl.label_decl);
                                     ^
/home/workaccount/Work/zls/main/src/Server.zig:2211:39: 0x33cdf8 in Server.generalReferencesHandler (zls)
        try references.labelReferences(allocator, decl, server.offset_encoding, include_decl)
```

**Comment by SuperAuguste** [comment]
Could you inspect the value of `decl.decl.label_decl`? Might be zero or maxInt or something to that effect... :)

**Comment by SuperAuguste** [comment]
Nice catch, seems like a redundant `firstToken`; does removing `firstToken` and just using the `label_decl` straight up fix the issue?

**Comment by SuperAuguste** [comment]
You're right; I'll take more of a look at this eventually, a little swamped with #724 atm

**Comment by SuperAuguste** [comment]
Probably a good idea, thanks :P

Could you open a PR for that real quick it?

**Comment by SuperAuguste** [comment]
oops that first token shouldn't be there - `.label` is already a token!

**Comment by SuperAuguste** [comment]
Fixed and tested locally, should be good to go! Thanks for the test case btw!!
