### ISSUE TITLE
Type Inference does not infer types correctly with indirection

### ISSUE THREAD

**Issue by fengshaun** [zigtools/zls#729]
### Zig Version

0.10.0-dev.4437+1e963053d

### Zig Language Server Version

2ae113ddcfa216bcd91958ac6d73bbd4de982177

### Steps to Reproduce

In the sample code below, `zls`'s type inference doesn't seem to recognize that the type of `x` is `MyType`. Therefore, no completion candidates are shown.

```
const MyType = struct {
    fieldA: u32,
};

fn main() !void {
    var xs = []MyType{ MyType{ .fieldA = 42 } };
    var x = xs.items[0];
    x.
}
```

### Expected Behavior

Completion candidate `fieldA` would be shown for `x`.

### Actual Behavior

Type of `x` in indicated as `unknown` and no completion candidates are shown.

**Comment by SuperAuguste** [comment]
Type inference is broken in a lot of cases as it's essentially an ast hack.

**Comment by fengshaun** [comment]
Awww, any plans for future? Where does one get started with this?

**Comment by SuperAuguste** [comment]
You could probably use some completion logic to improve type inference's current state; I'm working on #724 which'll hopefully improve this.

**Comment by fengshaun** [comment]
Thanks. It seems like Autodoc (0.10.0 release notes) does some type inference as well which I could look into.

**Comment by SuperAuguste** [comment]
You could try but Autodoc uses an extremely different architecture than zls :)

**Comment by fengshaun** [comment]
Welp! Time to explore! I'll wait and see what #724 fix brings and see if I can make sense of zls's internals.

**Comment by Techatrix** [comment]
both of the following code samples work in ZLS master:
```zig
const MyType = struct { fieldA: u32 };
fn main() !void {
    var xs = []MyType{MyType{ .fieldA = 5 }};
    var x = xs[0];
    x. // cursor here
}
```
```zig
const MyType = struct { fieldA: u32 };
fn main() !void {
    var xs = @import("std").ArrayListUnmanaged(MyType){};
    var x = xs.items[0];
    x. // cursor here
}
```
