### ISSUE TITLE
Builtin documentation markdown isn't rendered correctly

### ISSUE THREAD

**Issue by InKryption** [zigtools/zls#736]
### Zig Version

0.11.0-dev.18+81c27677d

### Zig Language Server Version

0.11.0-dev.6+f7c3d22

### Steps to Reproduce

Hover your cursor over a builtin, e.g. `@TypeInfo`, in VSCode, or any other editor which doesn't render markdown as seen in zig builtin documentation.
This has been an issue for a while now, but only just noticed there's no issue open for it.

### Expected Behavior

Render something comparable to:
>![image](https://user-images.githubusercontent.com/59504965/199580780-172fe0af-f378-49cb-ab17-ebdc5e29b457.png)

### Actual Behavior

VSCode on-hover:
>![image](https://user-images.githubusercontent.com/59504965/199579899-7422430c-771a-430a-bfc4-482220779582.png)

**Comment by alexnask** [comment]
I will take at stab at improving this for both markdown and non-markdwon outputs tomorrow.  
Should mostly be a matter of improving generate-data.py and some small changes to the codebase
