### ISSUE TITLE
Question: Should the Nix file aim to build ZLS reproducibly?

### ISSUE THREAD

**Issue by sagehane** [zigtools/zls#738]
Related: https://github.com/NixOS/nixpkgs/issues/185665

Nix's selling point is reproducibility. However, Zig normally targets for the native system unless specified otherwise.
Nixpkgs addresses this by passing `-Dcpu=baseline`[0].

Our current `flake.nix` file doesn't do this[1], and I personally think it should be "fixed". This might affect setups like people using Cachix or similar to serve other users substitutes that they've built. Thoughts?

[0] - https://github.com/NixOS/nixpkgs/blob/8ff7b290e6dd47d7ed24c6d156ba60fc3c83f100/pkgs/development/tools/zls/default.nix#L21:L23
[1] - https://github.com/zigtools/zls/blob/master/flake.nix#L34:L37

**Comment by SuperAuguste** [comment]
I think that reproducible builds with baseline make sense :)
