### ISSUE TITLE
FoldingRanges break fold/unfold keybinds in vscode

### ISSUE THREAD

**Issue by Vexu** [zigtools/zls#740]
After installing a version of zls with the foldingranges feature vscode fold/unfold keybinds stopped working on larger files like `Sema.zig`. I'm guessing it's related to the hardcoded limit of 5000. I worked around this by deleting everything related to the feature.

**Comment by Vexu** [comment]
> Those can be increased, Settings -> editor.foldingMaximumRegions,

Changing that was the first thing I tried and had seemingly no effect.

**Comment by InKryption** [comment]
It should do, if it doesn't you should try restarting the language server.

**Comment by Vexu** [comment]
Seems like the issue is just zls being extremely slow as everything works as expected after waiting a minute after opening a larger file

**Comment by nektro** [comment]
did you also make sure to build zls in release mode locally?

**Comment by Vexu** [comment]
Yes, I always build zls with `-Drelease-fast`.
