### ISSUE TITLE
Implement runtime/comptime distinction

### ISSUE THREAD

**Issue by SuperAuguste** [zigtools/zls#746]
Currently, the comptime interpreter assumes that all values that we send it are comptime and known... this is a problem.

For example, `bruh(u8, 10)` works, but not `bruh(u8, runtime_value_that_we_know_is_a_u8)` or even `bruh(u8, some_unknown_type_value)`, both of which should just be coerced to some sort of "unknown runtime" type and continue to work.

Also, we don't consider the `comptime` keyword (params, decls, fields, etc.), `comptime` vs runtime scopes, and more.

**Comment by InKryption** [comment]
Also to note: the result of an `inline fn` can be `comptime`-known if the arguments are all `comptime`-known & the body of the function is all `comptime`-knowable.

**Comment by Techatrix** [comment]
The comptime interpreter has been discontinued :(
