### ISSUE TITLE
Add more testing to CI

### ISSUE THREAD

**Issue by pixelherodev** [zigtools/zls#76]
As far as I can tell, the only CI right now is building ZLS. Since ZLS responds to JSON, it might be worth writing a test binary that invokes ZLS, sends it example documents, and verifies the responses. This can be used to ensure that future changes don't break specific completions, goto definitions, and so on.

**Comment by alexnask** [comment]
#7

**Comment by pixelherodev** [comment]
Ah, right :)

Sorry, I missed that.
