### ISSUE TITLE
Open VSX support

### ISSUE THREAD

**Issue by neoq** [zigtools/zls#768]
It would be great to have this extension available on [Open VSX](https://open-vsx.org/) in addition to the VS Code marketplace.
I am currently using VS Code packaged for archlinux which cannot use the official marketplace: https://wiki.archlinux.org/title/Visual_Studio_Code#Extensions_support.
[VSCodium](https://vscodium.com/) and other editors relying on Open VSX would also be supported with this.
Unfortunately, I can't work on this myself.
The steps to publish an extension on Open VSX are documented [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Thank you for this extension!

**Comment by truemedian** [comment]
Duplicate of <https://github.com/zigtools/zls-vscode/issues/20>

**Comment by neoq** [comment]
Got it, thanks!
