### ISSUE TITLE
zsl crash

### ISSUE THREAD

**Issue by marvhus** [zigtools/zls#782]
### Zig Version

0.11.0-dev.251+7c527c6df

### Zig Language Server Version

aa14772cfeeacf75d65192e23798185cab0f4d10

### Steps to Reproduce

Use zls with emacs
type "pub fn"
zls crashes

### Expected Behavior

That zls would continue running

### Actual Behavior

That zls crashed.

Here is the error Emacs gave me from the zls::stderr buffer:
```
info : (config): Using zig executable /opt/zig/zig
info : (config): Using zig lib path '/opt/zig/lib'
info : (server): zls initializing
info : (server): Server.ClientCapabilities{ .supports_snippets = false, .supports_semantic_tokens = false, .supports_inlay_hints = false, .supports_will_save = true, .supports_will_save_wait_until = true, .hover_supports_md = true, .completion_doc_supports_md = true, .label_details_support = false, .supports_configuration = true }
info : (server): Using offset encoding: utf16
info : (server): Setting configuration...
info : (config): Using zig executable /opt/zig/zig
thread 334276 panic: switch on corrupt value

Process zls stderr finished
```

Video: https://youtu.be/tk0ZiwKHKdU

**Comment by SuperAuguste** [comment]
probably a stage2 issue... 

cc: @Techatrix 😅

**Comment by marvhus** [comment]
note: I just tested it with the 0.10.0 version and there it doesn't crash, but by using the latest commit (like the readme tells you) it crashes.

**Comment by Techatrix** [comment]
why do i keep breaking things :disappointed:

**Comment by SuperAuguste** [comment]
Reverted for now, I'll try and hunt some stage2 issues down later tonight; rip easy stage2 migration :(

**Comment by Techatrix** [comment]
https://github.com/ziglang/zig/pull/13647 has been merged
