### ISSUE TITLE
zls slowing down emacs when trying to use a c library (sdl)

### ISSUE THREAD

**Issue by marvhus** [zigtools/zls#787]
### Zig Version

0.11.0-dev.251+7c527c6df

### Zig Language Server Version

0.10.0-dev.364+7ef2244

### Steps to Reproduce

use a c library, for example SDL
```
const sdl = @cImport(@cInclude("SDL2/SDL.h"));
```
Have zls enabled on emacs.
Try to type anything after typing: `sdl.`
Emacs begins to use a lot of the cpu, and slows down.

### Expected Behavior

That it wouldn't slow down

### Actual Behavior

That emacs slows down.

Node: when I try to use a stantard c library, `stdio.h` for example, it doesn't slow down.
And it seams to slow down whenever a lsp sugestion for sdl shows up.

Also in the zls::stderr buffer it has a lot of the same warning showing up:
```
info : (config): Using zig executable /opt/zig/zig
info : (config): Using zig lib path '/opt/zig/lib'
info : (server): zls initializing
info : (server): Server.ClientCapabilities{ .supports_snippets = false, .supports_semantic_tokens = false, .supports_inlay_hints = false, .hover_supports_md = true, .completion_doc_supports_md = true, .label_details_support = false, .supports_configuration = true }
info : (server): Using offset encoding: utf16
info : (server): Setting configuration...
info : (config): Using zig executable /opt/zig/zig
warning: (server): method not mapped: $/cancelRequest
warning: (server): method not mapped: $/cancelRequest
warning: (server): method not mapped: $/cancelRequest
warning: (server): method not mapped: $/cancelRequest
warning: (server): method not mapped: $/cancelRequest
warning: (server): method not mapped: $/cancelRequest
warning: (server): method not mapped: $/cancelRequest
warning: (server): method not mapped: $/cancelRequest
warning: (server): method not mapped: $/cancelRequest
warning: (server): method not mapped: $/cancelRequest
```

**Comment by Techatrix** [comment]
Once you ask for completions on cImport's zls will run `zig translate-c` in the background. Maybe this processing takes a long time in your case or it contains a bug. I would recommend using a debug build of zls which has more log messages. This could help us with narrowing down the issue.

**Comment by svmhdvn** [comment]
I'm running into this now with https://github.com/minad/corfu as the completion package (mostly default settings). Is there a way to cache the results of `zig translate-c` so that subsequent completion requests are handled quickly? Most of the time, I am trying to `@cInclude` a read-only system-installed header file that will not change. Thus, it wouldn't make sense to keep running `zig translate-c` on every completion request (if that is what's happening, correct me if I'm wrong).

Example scenario I'm running into:
```
const c = @cImport(@cInclude("bearssl.h")); // a relatively large set of imported symbols from BearSSL

c.br_sha512_ // <--- I type up to this point and request a completion, which then hangs emacs for a good 2-3 seconds waiting for completion, and spikes CPU usage
```

Even after receiving the completions and rendering their result in the completion UI, future completion requests also hang emacs for the same amount of time and spike CPU usage again.

**Comment by Techatrix** [comment]
> Thus, it wouldn't make sense to keep running `zig translate-c` on every completion request (if that is what's happening, correct me if I'm wrong).

ZLS will cache the result of running `zig translate-c` even across multiple files.
I've tested a small cImport example and it worked without issues for me. (VS Code, x86_64-linux) (Zig 0.10.1, ZLS 0.10.0) and (Zig 0.11.0-dev, ZLS master)
> I would recommend using a debug build of zls which has more log messages. This could help us with narrowing down the issue.

**Comment by Techatrix** [comment]
I will close this since there is no more activity here and I did not get a response, if this issue still occurs, please open a new issue.
