### ISSUE TITLE
Release-build for Linux AARCH 64

### ISSUE THREAD

**Issue by grav** [zigtools/zls#794]
Would it be possible to produce a release-build for Linux AARCH 64 (aka ARM64)?

I tried to use the one from my package manager (in this case Arch AUR), but it's flaky, since it depends on whatever zig binary is installed (which is 0.9).

Having a dependable download directly from Github releases would probably be the simplest solution at this point.

**Comment by SuperAuguste** [comment]
Yep! Just modify <https://github.com/zigtools/zls/blob/master/.github/workflows/main.yml#L41> accordingly and you should be good to go! :)
