### ISSUE TITLE
Interpret build files instead of compiling them

### ISSUE THREAD

**Issue by SuperAuguste** [zigtools/zls#796]
To get build file info (packages) we usually compile and run them. Small problem: this takes ages, especially for larger projects, and kills interactivity. Interpreting them would likely be much faster.

Also: this brings us one step closer to zls being Zig executable free and thus closer to #771.

**Comment by Techatrix** [comment]
Since #1311 ZLS will run the build script in the background which removes the long start up delay. Do you think this is still necessary?

**Comment by SuperAuguste** [comment]
Good point! I think we'll have to eventually revisit this if https://github.com/ziglang/zig/issues/14286 ends up being implemented, but in the meantime I totally agree that this is not a necessary change.
