### ISSUE TITLE
Unable to build master, compilation error.

### ISSUE THREAD

**Issue by JimmyDeemo** [zigtools/zls#797]
### Zig Version

0.11.0-dev.399+44ee1c885

### Zig Language Server Version

6ab2c68355a317a80285cacf62f7ea71ba1d6bf8

### Steps to Reproduce

Run `[PATH]\zig-windows-x86_64-0.11.0-dev.399+44ee1c885\zig build -Drelease-safe`. at specified commit.

### Expected Behavior

ZLS builds.

Note: I am trying to get a build that includes the fix for #753. I decided to try and build from source; apologies if `master` is not considered stable apart from tagged releases.

### Actual Behavior

```
C:\zig\zig-windows-x86_64-0.11.0-dev.399+44ee1c885\lib\std\build.zig:540:29: error: expected type '?[]const []const u8', found 'error{OutOfMemory}![][]const u8'
            .enum_options = enum_options,
                            ^~~~~~~~~~~~
referenced by:
    build: C:\zig\zls\build.zig:27:10
    runBuild: C:\zig\zig-windows-x86_64-0.11.0-dev.399+44ee1c885\lib\build_runner.zig:231:32
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

C:\zig\zig-windows-x86_64-0.11.0-dev.399+44ee1c885\lib\std\build.zig:540:29: error: expected type '?[]const []const u8', found 'error{OutOfMemory}![][]const u8'
            .enum_options = enum_options,
                            ^~~~~~~~~~~~
```

**Comment by SuperAuguste** [comment]
Please update your Zig install to the latest version.

**Comment by JimmyDeemo** [comment]
Ah I see now, this error is with Zig itself. I will try the latest at the time of writing which is `zig-windows-x86_64-0.11.0-dev.449+665eba93c`

**Comment by JimmyDeemo** [comment]
I am able to build using the version above. Thank you.
