### ISSUE TITLE
URI escaping on windows does not correctly calculate length of resulting string

### ISSUE THREAD

**Issue by josephst** [zigtools/zls#804]
### Zig Version

0.11.0-dev.462+af4361f57

### Zig Language Server Version

0.11.0-dev.59+c2d6b95

### Steps to Reproduce

`src/uri.zig` has various methods for converting strings to URIs as well as `parse` to convert from a URI to a string

On Windows, a file path such as `C:\main.zig` will be converted to `file:///c%3A/main.zig` with the `:` character replaced with `%3A`. When converting back to a file path, `%3A` will be replaced by `:`. However, the `parse()` method does not take this 2 character length reduction into account which results in the final string having two extra characters at the end of the string consisting of uninitialized memory. 

The malformed string results in the language server ultimately failing to initialize and most features (autocomplete, go to definition, etc) are unavailable on Windows. 

Example: 
```
====== expected this output: =========
c:\main.zigΓÉâ

======== instead found this: =========
c:\main.zig¬¬ΓÉâ

======================================
First difference occurs on line 1:
expected:
c:\main.zig
           ^ (end of string)
found:
c:\main.zig¬¬
           ^ ('\xaa')
```

PR fixing this to come (including addition of a failing test demonstrating this issue)!

### Expected Behavior

Should replace %3A with : character and properly reduce size of allocated string. 

On a side note, there may be an underlying bug in zig with allocator.resize() - it is not properly resizing the allocated string at the end of the `parse()` function. The final call to `allocator.resize(uri, i);` in the `parse()` function seems like it should resize the allocated memory but when examining this loop with a debugger, even when `i` is i.e. 40, `uri.len` remains 42

### Actual Behavior

String is not resized and two bytes of uninitialized memory are included at the end of the string

**Comment by SuperAuguste** [comment]
Yep, this is the cause of #803, fixing it as I speak :)

**Comment by SuperAuguste** [comment]
So I just got a fix out ASAP but the issue seems to be that `len` isn't modified by the allocator - not sure if this is intentional behavior or not (it seems quite counterintuitive, especially when `shrink` did this) but yeah I'm not sure.

**Comment by josephst** [comment]
Ah thanks for getting that fixed so fast! Just sent in a PR with some tests I added that fail because of this bug. I think I was chasing the wrong thing - the colon mishandling on Windows is more a symptom of the problem with .resize() (and hard-coding in a case for `%3A` probably isn't the way to go about fixing this!).

**Comment by SuperAuguste** [comment]
Thanks for taking the time to hunt this down! I agree that hard-coding the colon probably isn't the best strategy but neither is allocating twice like my fix (I just went with the safe route). I think the end-game is just figuring out how `resize` now behaves and handling the boolean return + setting `.len` ourselves because it doesn't seem to do so properly.
