### ISSUE TITLE
aarch64 Build Error

### ISSUE THREAD

**Issue by criegger** [zigtools/zls#815]
### Zig Version

0.9.1

### Zig Language Server Version

9e658cdbb6d1d29b047a8698e062205bc341586d

### Steps to Reproduce

1. Attempt to run `zig build`. Failure was recorded on an aarch64 Arch Linux install on a Raspberry Pi 4. This bug happened regardless of `-Dsafe-release` flag.

### Expected Behavior

A successful build.

### Actual Behavior

Build fails with the following error:
```
./build.zig:72:43: error: no member named 'first' in struct 'std.mem.SplitIterator(u8)'
                const tagged_ancestor = it.first();
                                          ^
```

**Comment by nektro** [comment]
zls requires an updated master version of Zig

**Comment by criegger** [comment]
Oh, that is my bad. I assumed I had the correct version since I pulled from repository. Perhaps the readme could be updated to specify that you need the latest development release of zig?

**Comment by leecannon** [comment]
@criegger 
From https://github.com/zigtools/zls/blob/master/README.md#installation: `Building zls is very easy. You will need a build of Zig master to build zls.`

**Comment by criegger** [comment]
Yes, I did read through the readme. I understand that explanation is sufficient on a technical level, however it was not immediately obvious to me on the first read that "Zig master" referred to something other than the latest stable release. I was suggesting to improve clarity for users new to zig by describing what "Zig master" means (i.e. `the latest dev build under Zig master` instead of `a build of Zig master`). However, I don't really care to argue over this on a closed issue, so if the ZLS team thinks the clarification is unnecessary, you can ignore the suggestion.
