### ISSUE TITLE
garbageCollectionCImports panic: access of union field 'success' while field 'failure' is active

### ISSUE THREAD

**Issue by nullptrdevs** [zigtools/zls#821]
### Zig Version

0.11.0-dev.803+4af305b30

### Zig Language Server Version

0.11.0-dev.70+0ab34ab

### Steps to Reproduce

```zig
const c = @cImport(@cInclude("no_such.h"));
export fn a() usize { return @sizeOf(@TypeOf(c.whatev)); }
```
Make sure you've triggered the ast-check, ie you get the "'no_such.h' file not found zls(cImport)" diagnostic.
Close the file.

### Expected Behavior

-

### Actual Behavior

```
thread 12342 panic: access of union field 'success' while field 'failure' is active
/home/workaccount/Work/zls/master/src/DocumentStore.zig:320:59: 0x494522 in garbageCollectionCImports (zls)
        std.log.debug("Destroying cimport {s}", .{kv.value.success});
                                                          ^
/home/workaccount/Work/zls/master/src/DocumentStore.zig:184:35: 0x3d89bd in closeDocument (zls)
    self.garbageCollectionCImports() catch {};
                                  ^
/home/workaccount/Work/zls/master/src/Server.zig:1928:64: 0x390013 in closeDocumentHandler__anon_13950 (zls)
    server.document_store.closeDocument(req.params.textDocument.uri);
```

On a related note, zig now forwards cimport errors from clang so one gets double the "'no_such.h' file not found zls(cImport)" diagnostic.

**Comment by Techatrix** [comment]
> On a related note, zig now forwards cimport errors from clang so one gets double the "'no_such.h' file not found zls(cImport)" diagnostic.

From what i am able to tell the duplicate cimport errors were caused because the code that created them in zls was literally written twice.
https://github.com/zigtools/zls/blob/68ac6f9f30adcd44c0e22219ffcef5fbfd9606d8/src/Server.zig#L183-L201
https://github.com/zigtools/zls/blob/68ac6f9f30adcd44c0e22219ffcef5fbfd9606d8/src/Server.zig#L280-L298
