### ISSUE TITLE
unexpected null in analysis.zig:1616:74#getPositionContext()

### ISSUE THREAD

**Issue by travisstaloch** [zigtools/zls#832]
### Zig Version

0.11.0-dev.819+84a930393

### Zig Language Server Version

5d6f23b5f196faaec26182f5bd03bc3e4f9e3c30

### Steps to Reproduce

this was found while fuzzing. here is the fuzzer output (from sus/staging/markov/principal.zig) https://pastebin.com/KB5ZJ5BL 

note that i changed the fuzzer to wrap output in `pub fn main() void { ... }`

here is the final error log entry from sus/logs/stderr.log
```console
debug: (server): Took 0ms to process method textDocument/hover
thread 174102 panic: attempt to use null value
~/zls/src/analysis.zig:1616:74: 0x3429f1 in getPositionContext (zls)
                        .field_access = tokenLocAppend(curr_ctx.ctx.loc().?, tok),
                                                                         ^
~/zls/src/Server.zig:2043:89: 0x36a11b in gotoHandler__anon_14768 (zls)
    const pos_context = try analysis.getPositionContext(server.arena.allocator(), handle.text, source_index);
                                                                                        ^
~/zls/src/Server.zig:2065:27: 0x36ae92 in gotoDefinitionHandler__anon_14764 (zls)
    try server.gotoHandler(writer, id, req, true);
                          ^
~/zls/src/Server.zig:2915:35: 0x38a044 in processJsonRpc__anon_11341 (zls)
                    method_info[2](server, writer, id, request_obj) catch |err| {
                                  ^
~/zls/src/main.zig:51:34: 0x38f612 in loop (zls)
        try server.processJsonRpc(writer, buffer);
                                 ^
~/zls/src/main.zig:281:13: 0x38faee in main (zls)
    try loop(&server);
            ^
~/zig/lib/std/start.zig:614:37: 0x2f2759 in posixCallMainAndExit (zls)
            const result = root.main() catch |err| {
                                    ^
~/zig/lib/std/start.zig:376:5: 0x2f21c1 in _start (zls)
    @call(.never_inline, posixCallMainAndExit, .{});
    ^
```

### Expected Behavior

not sure

### Actual Behavior

boom

**Comment by Techatrix** [comment]
I can't reproduce this issue because i don't know the details of the goto definition request that has been send to zls. Without this i just have to guess where in the file the issue is.

**Comment by travisstaloch** [comment]
ok thanks. i wonder if that info is recoverable from the logs somehow? i've lost the logs now but i think the issue was on line 622.  sorry i'll try to post more info next time. please to close if there is nothing of value here.

**Comment by travisstaloch** [comment]
> I'd think it's line 623 given #754 .

I'm able to reproduce via goto definition on 623:60

**Comment by travisstaloch** [comment]
closing as duplicate of #754
