### ISSUE TITLE
Standard library completions not working

### ISSUE THREAD

**Issue by demizer** [zigtools/zls#85]
- `zls_version`: f5b30cfd6cf45f406d276b4ea17bbe533cbdeba2
- `neovim_version`: v0.5.0-508-gc37d9fa3d
- `nvim-lsp_version`: https://github.com/neovim/nvim-lsp/commit/205a9f0ca9e733d94f15f228b9e23b29a80af7cd
- `zls.json`:
   ```
   {"zig_lib_path": "/home/demizer/zig-linux-x86_64-0.6.0+0fd77c2de/lib/zig/std"}
   ```
   zls.json lives next to the zls binary.

When I type `std.` nothing happens. There are no arguments for logging that I can discern to see why this is happening.

![std_complete_not_working](https://user-images.githubusercontent.com/30035/82853694-41e7ba80-9ebb-11ea-81ea-423e458d04e1.gif)

**Comment by SuperAuguste** [comment]
Hi @demizer! Thanks for filing this issue! This seems to be an issue with your installation!

Try `{"zig_lib_path": "/home/demizer/zig-linux-x86_64-0.6.0+0fd77c2de/lib/zig"}` instead!

**Comment by demizer** [comment]
Cool thanks, I also just discovered what I did wrong. For those that may come by this later, I was able to view the neovim lsp logs (where I discovered this issue) by setting the log_level and message_level in `setup{}`:

```lua                                                                                                                                  
nvim_lsp[zls].setup {
    log_level = vim.lsp.protocol.MessageType.Log,                                                                                                            
    message_level = vim.lsp.protocol.MessageType.Log, 
}
```

And then I tailed the logs with the path provided by `:lua print(vim.inspect(vim.lsp.get_log_path()))`, which showed me it was located in `$HOME/.local/share/nvim/vim-lsp.log`. The message level set is probably not needed since this error was at an higher log level.

**Comment by ellisonleao** [comment]
I am having similar issues here, but the logs are showing a different msg upon start

![Screenshot from 2020-11-25 12-13-11](https://user-images.githubusercontent.com/178641/100246221-a4c41800-2f17-11eb-97ef-f6b612c76ef7.png)

completion is still not working. My current config is

zls : https://github.com/zigtools/zls/commit/bdcd2a1e85599882bc5522acd823f3976d725eab

zls.json

```json
{
  "zig_lib_path": "/usr/lib/zig",
  "enable_snippets": true,
  "warn_style": false,
  "enable_semantic_tokens": true,
  "operator_completions": true
}
```

zls config in nvim lspconfig

```lua
  zls = {
    log_level = vim.lsp.protocol.MessageType.Log,
    message_level = vim.lsp.protocol.MessageType.Log,
    cmd = {string.format("%s/zls/zls", vim.fn.stdpath("cache"))}, -- zls installation folder (~/.local/cache/nvim/zls folder)
  },
```

**Comment by alexnask** [comment]
@ellisonleao Thanks for reporting.  
It looks like the nvim client does not support semantic token highlighting, or at least it has issues with our response.  
zls should not send those responses if the client does not support them, so I suspect this is a client issue, however a quick workaround for you would may be to set `enable_semantic_tokens` to false in zls.json  

I will investigate and open an issue with the nvim folks if its on their end.

**Comment by ellisonleao** [comment]
hey @alexnask thanks for the quick response. I've disabled that option and now i can see the autocompletion. Thanks!
