### ISSUE TITLE
[Neovim] LSP diagnostics go to a split

### ISSUE THREAD

**Issue by paveloom** [zigtools/zls#856]
### Zig Version

0.11.0-dev.947+cf822c6dd

### Zig Language Server Version

61c0981294c52820d185afe41a0965a722c3e314

### Steps to Reproduce

So, this is an awkward one. I assume you are familiar with Neovim.

1) Here's a minimal configuration file for Neovim:
	```lua
	-- Set the local root path
	local root = vim.fn.fnamemodify("./.repro", ":p")
	
	-- Set the standard paths to use the local root path
	for _, name in ipairs({ "config", "data", "state", "cache" }) do
	  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
	end
	
	-- Bootstrap Lazy
	local lazypath = root .. "/plugins/lazy.nvim"
	if not vim.loop.fs_stat(lazypath) then
	  vim.fn.system({
	    "git",
	    "clone",
	    "--filter=blob:none",
	    "--single-branch",
	    "https://github.com/folke/lazy.nvim.git",
	    lazypath,
	  })
	end
	vim.opt.runtimepath:prepend(lazypath)
	
	-- Install plugins
	local plugins = {
	  "folke/tokyonight.nvim",
	  "neovim/nvim-lspconfig",
	}
	require("lazy").setup(plugins, {
	  root = root .. "/plugins",
	})
	
	-- Setup the theme
	vim.opt.termguicolors = true
	vim.cmd([[colorscheme tokyonight]])
	
	-- Setup the LSP
	local lspconfig = require("lspconfig")
	lspconfig.zls.setup({
	  root_dir = lspconfig.util.root_pattern(".git", "build.zig", "zls.json"),
	  settings = {
	    zls = {
	      enable_inlay_hints = true,
	      enable_snippets = true,
	      warn_style = true,
	    },
	  },
	})
	
	-- Open the `main.zig` file if exists
	local main_path = "src/main.zig"
	if vim.loop.fs_stat(main_path) then
	  vim.cmd(":edit " .. main_path)
	end
	```
	
	Save it as `init.lua`.
2) Run `zig init-exe`
3) Run `nvim -u init.lua`, restart after the plugins are installed
4) Add something to the code that would cause a diagnostic to appear and save the buffer

### Expected Behavior

The diagnostic should be treated as usual, that is, being displayed as virtual text:

![image](https://user-images.githubusercontent.com/49961859/209793018-4ea3d142-a5b6-456f-b646-5e3af673ac48.png)

This is the previous commit, 941882371cecc1e9abc0e866c1747d8ad682e7e2.

### Actual Behavior

Saving opened a split and LSP put a diagnostic there:

![image](https://user-images.githubusercontent.com/49961859/209792539-668dba59-cacf-4a54-88d7-dbe42a5477b1.png)

I've never seen this before, so no idea what is causing it, but the regression happened in the aforementioned commit.

**Comment by SuperAuguste** [comment]
Can confirm this happening in VSCode too.

**Comment by paveloom** [comment]
Turns out the split part happens in older versions, too, but I can't go beyond the 4276207 commit on the latest master because of some API changes in the compiler.

**Comment by paveloom** [comment]
Not sure what that means, but there is a similar snippet above in that function:

https://github.com/zigtools/zls/blob/61c0981294c52820d185afe41a0965a722c3e314/src/Server.zig#L432-L436

Anyway, adding it outside the while loop seemingly didn't change anything for me.

**Comment by Techatrix** [comment]
did #865 resolve this issue?

**Comment by paveloom** [comment]
> did #865 resolve this issue?

No.

**Comment by paveloom** [comment]
Indeed! Thanks for catching it, @garymjr.

**Comment by bpo217** [comment]
I was going down all kinds of rabbit holes trying to figure this out. I'm surprised it's the default... Thank you @garymjr
