### ISSUE TITLE
Error on function/field which doesn't exist

### ISSUE THREAD

**Issue by Jarred-Sumner** [zigtools/zls#868]
ZLS knows that the `Bin.NamesIterator` struct has no function named `foo` (it is missing from autocomplete):
<img width="563" alt="image" src="https://user-images.githubusercontent.com/709451/210126725-7391ac6c-7fa3-47ec-bbf0-88658e02b02f.png">

But no error is generated:
<img width="252" alt="image" src="https://user-images.githubusercontent.com/709451/210126744-2e1f1772-a957-438b-b884-1a09d882009f.png">

**Comment by Techatrix** [comment]
This is covered by build-on-save. Missing diagnostics that depend on semantic analysis are now tracked by https://github.com/zigtools/zls/issues/2017. There is no need to track this specific example separately.
