### ISSUE TITLE
Error on declaration that doesn't exist

### ISSUE THREAD

**Issue by Jarred-Sumner** [zigtools/zls#869]
There is no declaration named `iterato`, but zls doesn't report an error. 

<img width="573" alt="image" src="https://user-images.githubusercontent.com/709451/210126822-6b1dc7a6-5a9d-42c9-9181-6dbde34aeb1f.png">

**Comment by Techatrix** [comment]
This has been fixed in d86d05d969c6872f2fa0786a23ffe5e682985e6a. If you still don't get this error make sure you have zig in your path and check if `enable_ast_check_diagnostics` is enabled.
