### ISSUE TITLE
Handle unicode in Zig error output

### ISSUE THREAD

**Issue by SuperAuguste** [zigtools/zls#872]
Jarred brings up that Unicode codepoints byte sequence could include a `\n` byte which is a valid (albeit rare) point.

- [ ] ast-check
- [ ] Full compilation

**Comment by nektro** [comment]
what situation did he describe? `\n` is `0x0A` which is strictly less than `0x80` and therefore unambiguously the same in both ASCII and UTF-8

**Comment by SuperAuguste** [comment]
Thanks for the fact-check @nektro, you are correct :)

**Comment by Jarred-Sumner** [comment]
> 
what situation did he describe? \n is 0x0A which is strictly less than 0x80 and therefore unambiguously the same in both ASCII and UTF-8

Unicode codepoints are multiple bytes

If you only look for `\n` or `\r` in a []const u8, you might end up in the 2nd or 3rd byte of a unicode codepoint, which is not a newline character.

**Comment by truemedian** [comment]
> If you only look for \n or \r in a []const u8, you might end up in the 2nd or 3rd byte of a unicode codepoint, which is not a newline character even though the byte is the same as one.

This is only possible in UTF-16. UTF-8 does not have this problem (all multibyte codepoints have bit 7 set in all bytes) and Zig only accepts UTF-8.
