### ISSUE TITLE
ZLS not fully compiling

### ISSUE THREAD

**Issue by hgsbart** [zigtools/zls#876]
### Zig Version

0.11.0-dev.1023+1c711b0a6 x86_64

### Zig Language Server Version

latest

### Steps to Reproduce

![zls not compiling 0 11 0-dev 1023+1c711b0a6](https://user-images.githubusercontent.com/92278974/210187027-995865b6-b369-44d6-9b9d-94e12a007a32.png)

### Expected Behavior

being able to use ./zig-out/bin/zls --config to configure zls for a editor

### Actual Behavior

doesn't fully go to the process of compiling everything stops compiling on different zig files, it changes every time I've tried to compile it.

**Comment by SuperAuguste** [comment]
I've actually run into this on memory-constrained systems; how much RAM does your machine have?

**Comment by hgsbart** [comment]
@SuperAuguste 32GB RAM

**Comment by Techatrix** [comment]
I will close since this issue since there has not been any activity here and no one else has reported such an issue with compiling ZLS. Feel free to open a new issue if this still occurs.
