### ISSUE TITLE
tres.zig not found

### ISSUE THREAD

**Issue by Byteron** [zigtools/zls#883]
### Zig Version

0.11.0-dev.1183+2b9478ce1

### Zig Language Server Version

20baa592eb62fb49ae2127f2bcacc5da98072087

### Steps to Reproduce

1. run `zig build -Drelease-safe`

### Expected Behavior

should compile.

### Actual Behavior

doesn't compile.
![image](https://user-images.githubusercontent.com/24433899/210745000-e5662f3a-a8b0-457a-817f-f33542ba1959.png)

**Comment by leecannon** [comment]
You need to pull down submodules by cloning recursively `git clone --recursive https://github.com/zigtools/zls.git` or in an already cloned repository running `git submodule update --init`.
