### ISSUE TITLE
File contents may be replaced with JSON RPC response string if ZLS doesn't crash after format-on-save

### ISSUE THREAD

**Issue by drew-gpf** [zigtools/zls#888]
### Zig Version

0.11.0-dev.1239+7a2d7ff62

### Zig Language Server Version

2717b0fba19daba897f86dd6de4b8b590bfee516

### Steps to Reproduce

1. create a file ending in .zig in VS Code on windows 10
2. type "asd"
3. hit enter 5 times (or maybe just enough to have zig fmt do something from extra newlines before EOF?)
4. save with format-on-save enabled

### Expected Behavior

File contents are not replaced with JSON RPC response header

### Actual Behavior

![Code_2023-01-06_23-52-57](https://user-images.githubusercontent.com/3195312/211140277-ce98ed87-df81-4579-a7b4-633622c4f7a2.gif)

(The contents are clearer the longer the initial string is, but for some bizarre reason it may then only work once or twice. Maybe because the file was longer than the response string?)

--

A possibly related issue is that when I created a new executable and slightly edited the main.zig file, zls would read a dangling pointer and either segfault while stringifying some "extra" data for a JSON RPC response header or just do nothing. However it only seems to be happening for one specific file on my computer (???). A way to possibly recreate it is with this:

```zig
const std = @import("std");

pub fn main() void {
}
(newline at EOF)
```

and then save. The callstack I get in winDBG when it crashes is:
![image](https://user-images.githubusercontent.com/3195312/211140473-0082235b-17a6-4016-85b2-3b0113eea00a.png)
Which starts from a call to sendResponse at https://github.com/zigtools/zls/blob/2717b0fba19daba897f86dd6de4b8b590bfee516/src/Server.zig#L3076

**Comment by drew-gpf** [comment]
Actually even my example isn't all that consistent but if you just play with it a bit you'll eventually get it to trigger

**Comment by Techatrix** [comment]
@drew-gpf can you test if #890 fixes this issue for you?

**Comment by drew-gpf** [comment]
@Techatrix this seems to have worked, thanks
