### ISSUE TITLE
builtin completions stopped working in sublime text

### ISSUE THREAD

**Issue by travisstaloch** [zigtools/zls#923]
### Zig Version

0.11.0-dev.1327+b42bd759a

### Zig Language Server Version

0.11.0-dev.121+61fa980

### Steps to Reproduce

I rebuilt zig/zls two times this week and builtins completions have since stopped appearing in sublime text on linux. 

I'm using sublime version 4143 and LSP verison 1.21.0

### Expected Behavior

To repro, i just start typing any builtin such as `@ptr`.  It used to cause completions to appear but now it doesn't. 

### Actual Behavior

No completions appear.

**Comment by SuperAuguste** [comment]
Potentially related to #919.

**Comment by Techatrix** [comment]
@travisstaloch does  #924 fix this issue?

**Comment by travisstaloch** [comment]
yes it does! lets go. tysm! :+1: :smiley_cat:

**Comment by Binbiubiubiu** [comment]
not work in vscode ,why
