### ISSUE TITLE
Fix builtin-based completions such as with Vectors

### ISSUE THREAD

**Issue by data-man** [zigtools/zls#93]
I wonder why vector definitions isn't exists in std ast. :confused:

**Comment by SuperAuguste** [comment]
They do! Vectors are classified builtins, I believe. Also, they don't have their own builtin anymore, and use @Type(.Vector) now, so we'll have to add support for *that*.

**Comment by data-man** [comment]
Just `grep vector` in `lib/std/zig` :smile:

**Comment by SuperAuguste** [comment]
Oh! You mean the vector type in meta? That should definitely have completion. I guess the only time it shouldn't is when using builtins as at the moment, ZLS doesn't complete the result of builtins.

**Comment by SuperAuguste** [comment]
Just checked, `std.meta.Vector` actually *uses* builtins to create vectors, and that's why they don't receive completions within ZLS! I'll rename this issue accordingly!

**Comment by SuperAuguste** [comment]
And good question on why Vector doesn't exist in `std.ast`! No builtins exist in `std.ast`, as they are instead seemingly handled by the non-self-hosted portions of the code generator.

**Comment by data-man** [comment]
arrays is also builtin, but it exist in `std.ast`.
