### ISSUE TITLE
Inlay hint labels for arguments in call expressions should end with a `:` and ideally higher contrast

### ISSUE THREAD

**Issue by Jarred-Sumner** [zigtools/zls#942]
Currently, it's kind of hard to tell what is an inlay hint and what isn't 

<img width="790" alt="image" src="https://user-images.githubusercontent.com/709451/215005574-aee59f77-6464-4ed5-b61a-30cee145272a.png">

Compare with some screenshots from google:

![image](https://user-images.githubusercontent.com/709451/215005426-8650d341-03c6-4ced-a2ca-d5e618d00b35.png)
![image](https://user-images.githubusercontent.com/709451/215005452-3d688289-77ec-4344-beb1-971098a6e49d.png)
![image](https://user-images.githubusercontent.com/709451/215005486-0dfb9d51-8721-4b5f-bf8c-ab2cb8d7ead9.png)

**Comment by Techatrix** [comment]
This is how inlay hints look like for me after #944:
![Screenshot from 2023-01-27 15-21-15](https://user-images.githubusercontent.com/19954306/215109344-82d39d89-c32a-4f73-98ae-7922faf8851a.png)

How hints are colored depends on your editor/theme and not on ZLS. (I used Dark+)
There are also some settings that allow you to change how inlay hints should be colored without having to switch the theme is VS Code, i would have to do some digging to find them again.
