### ISSUE TITLE
Semantic highlighting bugs after editing file cause inlay hints to appear in the wrong places

### ISSUE THREAD

**Issue by Jarred-Sumner** [zigtools/zls#943]
### Zig Version

0.11.0-dev.1473+96a55f6ce

### Zig Language Server Version

e055f9d

### Steps to Reproduce

Edit this file a little

https://github.com/oven-sh/bun/blob/b136125bb0ad8b66e92322c143094deee4996bcd/src/watcher.zig#L570

### Expected Behavior

After reloading VSCode:

<img width="904" alt="image" src="https://user-images.githubusercontent.com/709451/215072585-ecbd5530-9489-435f-aa62-cd4d37503de1.png">

### Actual Behavior

Note line 476, 512, and 515

<img width="771" alt="image" src="https://user-images.githubusercontent.com/709451/215072496-ba1b5a96-705a-4ac5-80bb-f8f001badd4f.png">

**Comment by Techatrix** [comment]
Does this bug still occur? I was never able to reproduce it. If yes, can you provide list of steps that reproduce this.

**Comment by Techatrix** [comment]
This issue has gone stale, feel free to reopen if this issue still occurs.
