### ISSUE TITLE
Provide a nicer way for contributor to build the code

### ISSUE THREAD

**Issue by matklad** [zigtools/zls#952]
As an occasional contributor to ZLS, one of the problems I have is, every time I come back to it after a break, it is always:

```
$ ./zig build
  ...
  your compiler is outdated
$ nix build
  ...
  your compilear is outdated
$ manually opens the browser, clicks the download link for the laterst compiler, etc
```

It would really help if there was a single command which would just download the relevant compiler. 

How do you folks actually keep up-to-date with latest zig? Do you just build zig itself from source? 

I wonder if we should have either of:

* download-zig.sh bash script which curls the latest master and stashes it into a local directory
* download-zig.zig script which you can run with `zig run download-zig.zig`, which does the same, and is implemented in a sufficiently old zig such that distro's version works

**Comment by SuperAuguste** [comment]
This is out of scope for zls, sorry! There's already an easy way to build the code - `zig build` - installing the Zig compiler is ephemeral and on the user.

As a Windows user, I just use the website binaries because I don't like building w/ LLVM.

**Comment by matklad** [comment]
FWIW, I continue to feel the pain here. Today (f8e8371f04d4cf342a5e88b670cbfdc356e6d3d8 / 2023-06-21) I wanted to compile zls. I updated repository, and

```console
$ nix build
```

failed because the zig version was too old, and 

```console
# manually download and unpack zig
$ /zig-linux-x86_64-0.11.0-dev.3731+c6e2e1ae4/zig build 
```

failed because zig version was too new. 

At this point I guess I could look at the CI logs to learn which version of Zig can compile zls, but that's too much friction for me personally.
