### ISSUE TITLE
Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by Binbiubiubiu** [zigtools/zls#956]
### Zig Version

zig-windows-x86_64-0.11.0-dev.1507+6f13a725a

### Zig Language Server Version

master

### Steps to Reproduce

use vscode-zls by  save file

### Expected Behavior

Don't report error "Request textDocument/codeAction failed."

### Actual Behavior

info : ( main ): No config file zls.json found.
info : (config): Using zig executable D:\zig-windows-x86_64-0.11.0-dev.1507+6f13a725a\zig.exe
info : (config): Using zig lib path 'D:\zig-windows-x86_64-0.11.0-dev.1507+6f13a725a\lib'
info : (server): client is 'Visual Studio Code-1.74.3'
info : (server): zls initializing
info : (server): Server.ClientCapabilities{ .supports_snippets = true, .supports_apply_edits = true, .supports_will_save = true, .supports_will_save_wait_until = true, .supports_publish_diagnostics = true, .supports_code_action_fixall = true, .hover_supports_md = true, .completion_doc_supports_md = true, .label_details_support = true, .supports_configuration = true }
info : (server): Using offset encoding: utf-16
info : (server): Setting configuration...
info : (config): Using zig executable D:/zig-windows-x86_64-0.11.0-dev.1507+6f13a725a/zig.exe
[Error - 12:22:10] Request textDocument/codeAction failed.
  Message: InternalError
  Code: 109

**Comment by Binbiubiubiu** [comment]
sry

**Comment by hasit** [comment]
@Binbiubiubiu I see that you've close this issue. How did you resolve it?

**Comment by Binbiubiubiu** [comment]
@hasit Caused by formatting code of other vscode plug-ins

such as `eslint`
```
"editor.codeActionsOnSave": {
    // "source.fixAll.stylelint": true,
    // "source.fixAll.eslint": true
 }
```

**Comment by Binbiubiubiu** [comment]
You can open `zls.trace.server`, look at zls's log
