### ISSUE TITLE
Constant crashes referencing top-level @This()

### ISSUE THREAD

**Issue by pixelherodev** [zigtools/zls#96]
With `const name = @This();` at the top level of a file, anything attempting to complete from `name` - or from a parameter of type `name` - causes ZLS to crash.

This is actually one of the cases I had thought was an infinite loop; it's constantly dying and delaying the editor's lsp plugin as it restarts the server.

**Comment by SuperAuguste** [comment]
Hey @pixelherodev, Alex and I can't seem to reproduce this issue! Can you give me more details about your installation specifics?

**Comment by pixelherodev** [comment]
ZLS master built using Zig master.

Anything else?

**Comment by alexnask** [comment]
Closing this as it seems to have been fixed, @pixelherodev feel free to reopen if this is still an issue for you or it happens again in another file.
