### ISSUE TITLE
Only the last top-level doc comment gets highlighted, if at the start of a file.

### ISSUE THREAD

**Issue by TUSF** [zigtools/zls#968]
It seems that if there is no other code (aside from comments) then top-level comments seem to disable highlighting for anything that comes before them. That includes comments, and document comments alike. 

It's relatively minor, although still annoying to see.

![image](https://user-images.githubusercontent.com/8594356/210748205-5c68d689-b01d-43b8-929e-c36715dee462.png)

**Comment by Techatrix** [comment]
I can't reproduce this since this probably got fixed at some point.
