### ISSUE TITLE
formatting file with zls causes infinite loop in memory allocator

### ISSUE THREAD

**Issue by Jarred-Sumner** [zigtools/zls#979]
### Zig Version

0.11.0-dev.1393+38eebf3c4

### Zig Language Server Version

384f227cb752553f440f2d256e68858b65fb13fc

### Steps to Reproduce

When using zls to format files, it seems to infinite loop on certain input. Generally it seems to be more likely to happen on longer files. `zig fmt` works as expected.

[File that reproduces the issue](https://gist.github.com/Jarred-Sumner/f6eb3d35d41bbac8de84fe0f58336766) (too long to fit in an issue)

### Expected Behavior

Formats successfully, like `zig fmt`

### Actual Behavior

It infinite loops until it uses enough memory for the OOM killer to kill it. This type of issue is often caused by looping over or duplicating a slice that is undefined, in which cause the `len` field is something absurdly large (due to undefined memory)

<img width="367" alt="image" src="https://user-images.githubusercontent.com/709451/216866102-fd5cccaf-2754-419b-8011-c26bf9ae6bc5.png">

**Comment by Jarred-Sumner** [comment]
i don't know if this would work but

what if when the input is longer than say 8 KB and the buffer is to a file on the filesystem, it spawns `zig fmt` and does something simpler to find the cursor position diff? on my machine, `zig fmt` takes 26ms so it would probably have acceptable perf

**Comment by SuperAuguste** [comment]
I’ll try to optimize this tonight.

**Comment by SuperAuguste** [comment]
Reproduced and got a beautiful `GetLastError(1455): The paging file is too small for this operation to complete.`; confirmed that the error cause is `diff.edits`. I'll try and implement a better algorithm which should hopefully fix this up! :)

**Comment by Jarred-Sumner** [comment]
If the code is still using `page_allocator`, that would cause the issue. If my understanding of page_allocator is correct (it might be completely wrong), every allocation is a new page in memory. Allocating 32 bytes is actually allocating 4 KB or 16 KB.

That means using `c_allocator` would be a very significant performance improvement (and help with this issue, as it would take longer to OOM)

**Comment by Jarred-Sumner** [comment]
ah it's using GPA
<img width="1839" alt="image" src="https://user-images.githubusercontent.com/709451/217124184-4a040309-340f-46b4-9e26-87c560d9f335.png">

**Comment by SuperAuguste** [comment]
> If the code is still using `page_allocator`, that would cause the issue. If my understanding of page_allocator is correct (it might be completely wrong), every allocation is a new page in memory. Allocating 32 bytes is actually allocating 4 KB or 16 KB.
> 
> That means using `c_allocator` would be a very significant performance improvement (and help with this issue, as it would take longer to OOM)

That is incorrect. Firstly, we use an Arena, so this is practically a non-issue as far as I know. Secondly, the method that `diff.edits` uses performs an allocation of size `a.len * b.len` which for your input is essentially `176,489 * 176,489` after formatting, or in other words, it's attempting to allocate `31,148,367,121` bytes or memory, causing an OOM regardless of which allocator we're using.

**Comment by Jarred-Sumner** [comment]
to speed up mem.eql(u8, slice, slice), consider copying this function https://github.com/oven-sh/bun/blob/main/src/string_immutable.zig#L766-L824


to speed up ComptimeStringMap, consider copying this https://github.com/oven-sh/bun/blob/main/src/comptime_string_map.zig#L1

**Comment by SuperAuguste** [comment]
These optimizations are not useful in this scenario.
