### ISSUE TITLE
`applyContentChanges` correctness, performance concerns

### ISSUE THREAD

**Issue by SuperAuguste** [zigtools/zls#985]
[See comment](https://github.com/zigtools/zls/blob/e6c9bb137f987924d0659e7990d8f48865805824/src/diff.zig#L282-L285)

On top of that, in large files, this function can easily take 20 milliseconds if not more, which adds up when quickly modifying code.

The solution is probably just yoinking Go's implementation for this, too.

**Comment by Techatrix** [comment]
Are you sure this implementation is incorrect at its core?
Looking at the description of [TextDocumentContentChangeEvent](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#didChangeTextDocumentParams):
```
The actual content changes. The content changes describe single state
changes to the document. So if there are two content changes c1 (at
array index 0) and c2 (at array index 1) for a document in state S then
c1 moves the document from S to S' and c2 from S' to S''. So c1 is
computed on the state S and c2 is computed on the state S'.

To mirror the content of a document using change events use the following
approach:
- start with the same initial content
- apply the 'textDocument/didChange' notifications in the order you
  receive them.
- apply the `TextDocumentContentChangeEvent`s in a single notification
  in the order you receive them.
```

**Comment by Techatrix** [comment]
Closed, see previous comment for the reason.
