### ISSUE TITLE
ZLS panics while handling the config with LSP-mode

### ISSUE THREAD

**Issue by bereal** [zigtools/zls#994]
### Zig Version

0.11.0-dev.1594+a5d25fabd

### Zig Language Server Version

0e5e1fdb8ae5b2da813fd10937b12174854ee903

### Steps to Reproduce

Using the latest lsp-mode with Emacs 2.6.3, `zls.json` does not exist. Open a `.zig` file in a fresh Zig project, run `lsp-mode`.

### Expected Behavior

I'd expect it to run ZLS and work :)

### Actual Behavior

 When I open a zig file, ZLS crashes with the following log:

```
info : (server): client is 'emacs-GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu)
 of 2020-03-26, modified by Debian'
info : (server): zls initializing
info : (server): Using offset encoding: utf-16
info : (server): Setting configuration...
thread 31951 panic: Invalid configuration value
Process zls stderr finished
```

After adding some logging, it narrows down to the `i_haz_configuration` handling:

```
info : (server): json: {"jsonrpc":"2.0","id":"i_haz_configuration","result":["nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil","nil"]}

info : (server): response Server.Message.Message__struct_12910{ .id = lsp.RequestId{ .string = { 105, 95, 104, 97, 122, 95, 99, 111, 110, 102, 105, 103, 117, 114, 97, 116, 105, 111, 110 } }, .result = json.Value{ .Array = array_list.ArrayListAligned(json.Value,null){ .items = { ... }, .capacity = 38, .allocator = mem.Allocator{ ... } } }, .error = null }
info : (server): Setting configuration...
info : (server): field builtin.Type.StructField{ .name = { 101, 110, 97, 98, 108, 101, 95, 115, 110, 105, 112, 112, 101, 116, 115 }, .type = bool, .default_value = anyopaque@218fc8, .is_comptime = false, .alignment = 1 }=json.Value{ .String = { 110, 105, 108 } }
thread 31951 panic: Invalid configuration value
```
So it seems that `"nil"` value is not expected. It's literally my second attempt to do anything with Zig, so the conclusion might be wrong, but I'm quite certain that it crashes.

**Comment by SuperAuguste** [comment]
Let's be real here, this is absolutely a bug in lsp-mode as this is 100% a violation of the LSP specification. I think that a PR on our end is reasonable @nullptrdevs but we should probably reach out to the lsp-mode people about this issue on their end.
